# Generated by Django 5.2.10 on 2026-02-11 01:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0041_accountingsettings_correction_income_account_and_more'),
        ('treasury', '0048_remove_historicalpaymentmethod_terminal_vat_bridge_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('UNDER_REVIEW', 'En Revisión'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tax_periods', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Período Tributario',
                'verbose_name_plural': 'Períodos Tributarios',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalF29Declaration',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('declaration_date', models.DateField(blank=True, help_text='Fecha en que se presentó en el SII', null=True, verbose_name='Fecha de Declaración')),
                ('folio_number', models.CharField(blank=True, help_text='Número de folio asignado por el SII', max_length=50, verbose_name='Folio SII')),
                ('sales_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Monto neto de ventas afectas a IVA', max_digits=15, verbose_name='Ventas Afectas')),
                ('sales_exempt', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Ventas no afectas a IVA', max_digits=15, verbose_name='Ventas Exentas')),
                ('debit_notes_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Notas de Débito Afectas')),
                ('credit_notes_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Se restan de las ventas', max_digits=15, verbose_name='Notas de Crédito Afectas')),
                ('purchases_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Monto neto de compras afectas a IVA', max_digits=15, verbose_name='Compras Afectas')),
                ('purchases_exempt', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Compras Exentas')),
                ('purchase_debit_notes', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Notas de Débito Compras')),
                ('purchase_credit_notes', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Se restan de las compras', max_digits=15, verbose_name='Notas de Crédito Compras')),
                ('ppm_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Pagos Provisionales Mensuales', max_digits=15, verbose_name='PPM Pagado')),
                ('withholding_tax', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Impuesto único segunda categoría retenido', max_digits=15, verbose_name='Retenciones de Honorarios')),
                ('vat_credit_carryforward', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Crédito fiscal nominal del período anterior', max_digits=15, verbose_name='Remanente Mes Anterior')),
                ('vat_correction_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Aumento del remanente por actualización monetaria (Art. 31)', max_digits=15, verbose_name='Reajuste Remanente')),
                ('second_category_tax', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Impuesto Única 2da Categoría')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA aplicable (ej: 19.00)', max_digits=5, verbose_name='Tasa de IVA')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('tax_period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.taxperiod', verbose_name='Período Tributario')),
            ],
            options={
                'verbose_name': 'historical Declaración F29',
                'verbose_name_plural': 'historical Declaraciones F29',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='F29Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_date', models.DateField(blank=True, help_text='Fecha en que se presentó en el SII', null=True, verbose_name='Fecha de Declaración')),
                ('folio_number', models.CharField(blank=True, help_text='Número de folio asignado por el SII', max_length=50, verbose_name='Folio SII')),
                ('sales_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Monto neto de ventas afectas a IVA', max_digits=15, verbose_name='Ventas Afectas')),
                ('sales_exempt', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Ventas no afectas a IVA', max_digits=15, verbose_name='Ventas Exentas')),
                ('debit_notes_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Notas de Débito Afectas')),
                ('credit_notes_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Se restan de las ventas', max_digits=15, verbose_name='Notas de Crédito Afectas')),
                ('purchases_taxed', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Monto neto de compras afectas a IVA', max_digits=15, verbose_name='Compras Afectas')),
                ('purchases_exempt', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Compras Exentas')),
                ('purchase_debit_notes', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Notas de Débito Compras')),
                ('purchase_credit_notes', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Se restan de las compras', max_digits=15, verbose_name='Notas de Crédito Compras')),
                ('ppm_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Pagos Provisionales Mensuales', max_digits=15, verbose_name='PPM Pagado')),
                ('withholding_tax', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Impuesto único segunda categoría retenido', max_digits=15, verbose_name='Retenciones de Honorarios')),
                ('vat_credit_carryforward', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Crédito fiscal nominal del período anterior', max_digits=15, verbose_name='Remanente Mes Anterior')),
                ('vat_correction_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Aumento del remanente por actualización monetaria (Art. 31)', max_digits=15, verbose_name='Reajuste Remanente')),
                ('second_category_tax', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='Impuesto Única 2da Categoría')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA aplicable (ej: 19.00)', max_digits=5, verbose_name='Tasa de IVA')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f29_declaration', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='tax.taxperiod', verbose_name='Período Tributario')),
            ],
            options={
                'verbose_name': 'Declaración F29',
                'verbose_name_plural': 'Declaraciones F29',
                'ordering': ['-tax_period__year', '-tax_period__month'],
            },
        ),
        migrations.CreateModel(
            name='F29Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Pagado')),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CASH', 'Efectivo'), ('OTHER', 'Otro')], default='TRANSFER', max_length=20, verbose_name='Método de Pago')),
                ('reference', models.CharField(blank=True, help_text='Comprobante bancario u otra referencia', max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tax.f29declaration', verbose_name='Declaración F29')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f29_payment', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_payments', to='treasury.treasuryaccount', verbose_name='Cuenta de Pago')),
            ],
            options={
                'verbose_name': 'Pago F29',
                'verbose_name_plural': 'Pagos F29',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='tax_f29paym_payment_2bee45_idx'), models.Index(fields=['declaration'], name='tax_f29paym_declara_63f5f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['year', 'month'], name='tax_taxperi_year_9e4666_idx'),
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['status'], name='tax_taxperi_status_612196_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxperiod',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='f29declaration',
            index=models.Index(fields=['declaration_date'], name='tax_f29decl_declara_dbd6db_idx'),
        ),
    ]
