# Generated by Django 6.0.6 on 2026-07-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxperiod',
            options={'ordering': ['-year', '-month'], 'permissions': [('can_close_tax_period', 'Puede cerrar período tributario (F29)'), ('can_reopen_tax_period', 'Puede reabrir período tributario (F29)')], 'verbose_name': 'Período Tributario', 'verbose_name_plural': 'Períodos Tributarios'},
        ),
    ]
