# Generated by Django 5.2.10 on 2026-04-15 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('UNDER_REVIEW', 'En Revisión'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='Estado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('tax_period', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_period', to='tax.taxperiod', verbose_name='Periodo Tributario Asociado')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'ordering': ['-year', '-month'],
                'permissions': [('can_close_accounting_period', 'Can close accounting periods'), ('can_reopen_accounting_period', 'Can reopen closed accounting periods')],
                'indexes': [models.Index(fields=['year', 'month'], name='tax_account_year_c19b92_idx'), models.Index(fields=['status'], name='tax_account_status_02e4ea_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
