# Generated by Django 6.0.5 on 2026-07-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_add_permissions_to_taxperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f29payment',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta (Manual)'), ('DEBIT_CARD', 'Tarjeta Débito Empresa'), ('CREDIT_CARD', 'Tarjeta Crédito Empresa'), ('CARD_TERMINAL', 'Tarjeta (Terminal de cobro)'), ('OTHER', 'Otro')], default='TRANSFER', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
