# Generated by Django 5.2.10 on 2026-02-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_accountingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f29payment',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('OTHER', 'Otro')], default='TRANSFER', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
