# Generated by Django 5.2.12 on 2026-03-05 01:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_f29payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='f29declaration',
            name='ila_tax',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Impuesto Adicional (Licores, Bebidas analcohólicas, etc.)', max_digits=15, verbose_name='Impuesto ILA'),
        ),
        migrations.AddField(
            model_name='f29declaration',
            name='loan_retention',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Retención adicional 3% Préstamo Solidario (Código 177)', max_digits=15, verbose_name='Retención Préstamo Solidario'),
        ),
        migrations.AddField(
            model_name='f29declaration',
            name='vat_withholding',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='IVA retenido por compras o cambio de sujeto', max_digits=15, verbose_name='Retención IVA'),
        ),
        migrations.AddField(
            model_name='historicalf29declaration',
            name='ila_tax',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Impuesto Adicional (Licores, Bebidas analcohólicas, etc.)', max_digits=15, verbose_name='Impuesto ILA'),
        ),
        migrations.AddField(
            model_name='historicalf29declaration',
            name='loan_retention',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Retención adicional 3% Préstamo Solidario (Código 177)', max_digits=15, verbose_name='Retención Préstamo Solidario'),
        ),
        migrations.AddField(
            model_name='historicalf29declaration',
            name='vat_withholding',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='IVA retenido por compras o cambio de sujeto', max_digits=15, verbose_name='Retención IVA'),
        ),
    ]
