# Generated by Django 6.0.5 on 2026-07-02 20:02

import core.storages
import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_f29payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='f29declaration',
            name='document',
            field=models.FileField(blank=True, help_text='Formulario F29 (PDF) u otro comprobante', null=True, storage=core.storages.PrivateMediaStorage(), upload_to=core.utils.UploadPath('tax/f29_documents/'), validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Documento Declaración'),
        ),
        migrations.AddField(
            model_name='historicalf29declaration',
            name='document',
            field=models.TextField(blank=True, help_text='Formulario F29 (PDF) u otro comprobante', max_length=100, null=True, validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Documento Declaración'),
        ),
    ]
