# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_missing_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalf29payment',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='historicalf29payment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalf29payment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='historicalf29payment',
            name='treasury_account',
        ),
        migrations.RemoveField(
            model_name='historicaltaxperiod',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaxperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaxperiod',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accountingperiod',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='f29declaration',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='f29payment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalf29declaration',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taxperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taxperiod',
            name='deleted_at',
        ),
        migrations.DeleteModel(
            name='HistoricalAccountingPeriod',
        ),
        migrations.DeleteModel(
            name='HistoricalF29Payment',
        ),
        migrations.DeleteModel(
            name='HistoricalTaxPeriod',
        ),
    ]
