services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8100/api
    working_dir: /app-standalone
    command: [ "node", "server.js" ]
    # The volumes from the base file are merged by Compose, but by using 
    # /app-standalone as WORKDIR, we avoid the masking effect of the /app volume.
    volumes: []
    deploy:
      resources:
        limits:
          memory: 4096M
