services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=erpgrafico
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=postgres://postgres:postgres@db:5432/erpgrafico
      - REDIS_URL=redis://redis:6379/1

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/erpgrafico
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SKIP_MIGRATIONS=true

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/erpgrafico
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SKIP_MIGRATIONS=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: "root"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/.turbo
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_OTEL_FETCH_DISABLED=1
      - TURBO_CACHE_DIR=/tmp/.turbo
      - TURBO_DATABASE_DIR=/tmp/turbo-db

volumes:
  postgres_data:
