# Generated by Django 5.2.9 on 2025-12-31 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_remove_accountingsettings_default_tax_account_and_more'),
        ('purchasing', '0002_alter_purchaseorder_status'),
        ('sales', '0002_alter_saleorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_type', models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('BOLETA', 'Boleta Electrónica'), ('PURCHASE_INV', 'Factura de Compra')], max_length=20, verbose_name='Tipo DTE')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Folio')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.purchaseorder')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Factura/Boleta',
                'verbose_name_plural': 'Facturas y Boletas',
            },
        ),
    ]
