# Generated by Django 5.2.12 on 2026-04-04 00:10

import core.utils
import core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dte_type', models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('FACTURA_EXENTA', 'Factura No Afecta o Exenta'), ('BOLETA', 'Boleta Electrónica'), ('BOLETA_EXENTA', 'Boleta No Afecta o Exenta'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=25, verbose_name='Tipo DTE')),
                ('sii_document_code', models.IntegerField(blank=True, choices=[(33, 'Factura Electrónica'), (34, 'Factura Exenta'), (39, 'Boleta Electrónica'), (41, 'Boleta Exenta'), (56, 'Nota de Débito'), (61, 'Nota de Crédito')], help_text='Código oficial del tipo de DTE según SII de Chile', null=True, verbose_name='Código SII')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Folio')),
                ('document_attachment', models.TextField(blank=True, max_length=100, null=True, validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Adjunto de Documento')),
                ('date', models.DateField(default=core.utils.get_current_date, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total_discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Descuento Total')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('tax_period_closed', models.BooleanField(default=False, help_text='Indica si el período tributario de este documento está cerrado', verbose_name='Período Cerrado')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Factura/Boleta',
                'verbose_name_plural': 'historical Facturas y Boletas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_type', models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('FACTURA_EXENTA', 'Factura No Afecta o Exenta'), ('BOLETA', 'Boleta Electrónica'), ('BOLETA_EXENTA', 'Boleta No Afecta o Exenta'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=25, verbose_name='Tipo DTE')),
                ('sii_document_code', models.IntegerField(blank=True, choices=[(33, 'Factura Electrónica'), (34, 'Factura Exenta'), (39, 'Boleta Electrónica'), (41, 'Boleta Exenta'), (56, 'Nota de Débito'), (61, 'Nota de Crédito')], help_text='Código oficial del tipo de DTE según SII de Chile', null=True, verbose_name='Código SII')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Folio')),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to=core.utils.UploadPath('invoices/'), validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Adjunto de Documento')),
                ('date', models.DateField(default=core.utils.get_current_date, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total_discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Descuento Total')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('tax_period_closed', models.BooleanField(default=False, help_text='Indica si el período tributario de este documento está cerrado', verbose_name='Período Cerrado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura/Boleta',
                'verbose_name_plural': 'Facturas y Boletas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NoteWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('DRAFT', 'Borrador'), ('INVOICE_SELECTED', 'Factura Seleccionada'), ('ITEMS_SELECTED', 'Productos Seleccionados'), ('LOGISTICS_PENDING', 'Logística Pendiente'), ('LOGISTICS_COMPLETED', 'Logística Completada'), ('REGISTRATION_PENDING', 'Registro Pendiente'), ('PAYMENT_PENDING', 'Pago Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=30, verbose_name='Etapa Actual')),
                ('requires_logistics', models.BooleanField(default=False, help_text='True si hay productos stockeables que generan movimientos de inventario', verbose_name='Requiere Logística')),
                ('registration_deferred', models.BooleanField(default=False, help_text='True si el usuario eligió atrasar el registro contable', verbose_name='Registro Diferido')),
                ('selected_items', models.JSONField(blank=True, help_text='Lista de productos a devolver/ajustar: [{product_id, quantity, reason, unit_price, tax_amount}]', null=True, verbose_name='Productos Seleccionados')),
                ('logistics_data', models.JSONField(blank=True, help_text='Información de bodega, fecha, notas: {warehouse_id, date, notes}', null=True, verbose_name='Datos de Logística')),
                ('registration_data', models.JSONField(blank=True, help_text='Información de DTE: {dte_type, document_number, date}', null=True, verbose_name='Datos de Facturación')),
                ('payment_data', models.JSONField(blank=True, help_text='Información de pago/ajuste: {method, amount, account_id, apply_credit}', null=True, verbose_name='Datos de Pago')),
                ('reason', models.TextField(blank=True, help_text='Razón de la creación de esta nota', verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow de Nota',
                'verbose_name_plural': 'Workflows de Notas',
                'ordering': ['-created_at'],
            },
        ),
    ]
