# Generated by Django 5.2.9 on 2026-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Adjunto de Documento'),
        ),
    ]
