# Generated by Django 5.2.9 on 2026-01-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_document_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dte_type',
            field=models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('BOLETA', 'Boleta Electrónica'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=20, verbose_name='Tipo DTE'),
        ),
    ]
