# Generated by Django 5.2.9 on 2026-01-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_date'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.contact', verbose_name='Contacto'),
        ),
    ]
