# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('billing', '0004_initial'),
        ('contacts', '0002_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.contact', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, help_text='Documento original que esta nota rectifica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='billing.invoice', verbose_name='Factura Rectificada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Documento original que esta nota rectifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura Rectificada'),
        ),
        migrations.AddField(
            model_name='noteworkflow',
            name='corrected_invoice',
            field=models.ForeignKey(help_text='Factura POSTED que se está corrigiendo con esta nota', on_delete=django.db.models.deletion.PROTECT, related_name='correction_workflows', to='billing.invoice', verbose_name='Factura Original'),
        ),
        migrations.AddField(
            model_name='noteworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='noteworkflow',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='billing.invoice', verbose_name='Nota de Crédito/Débito'),
        ),
        migrations.AddField(
            model_name='noteworkflow',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_workflows', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='noteworkflow',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_workflows', to='sales.saleorder'),
        ),
    ]
