# Generated by Django 5.2.9 on 2026-01-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_contact'),
    ]

    operations = [
    ]
