# Generated by Django 5.2.12 on 2026-04-10 20:06

import core.storages
import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_attachment',
            field=models.FileField(blank=True, null=True, storage=core.storages.PrivateMediaStorage(), upload_to=core.utils.UploadPath('invoices/'), validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Adjunto de Documento'),
        ),
    ]
