# Generated by Django 5.2.12 on 2026-04-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_invoice_document_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='dte_type',
            field=models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('FACTURA_EXENTA', 'Factura No Afecta o Exenta'), ('BOLETA', 'Boleta Electrónica'), ('BOLETA_EXENTA', 'Boleta No Afecta o Exenta'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('COMPROBANTE_PAGO', 'Comprobante de Pago Electrónico')], max_length=25, verbose_name='Tipo DTE'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='sii_document_code',
            field=models.IntegerField(blank=True, choices=[(33, 'Factura Electrónica'), (34, 'Factura Exenta'), (39, 'Boleta Electrónica'), (41, 'Boleta Exenta'), (48, 'Comprobante de Pago Electrónico'), (56, 'Nota de Débito'), (61, 'Nota de Crédito')], help_text='Código oficial del tipo de DTE según SII de Chile', null=True, verbose_name='Código SII'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dte_type',
            field=models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('FACTURA_EXENTA', 'Factura No Afecta o Exenta'), ('BOLETA', 'Boleta Electrónica'), ('BOLETA_EXENTA', 'Boleta No Afecta o Exenta'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('COMPROBANTE_PAGO', 'Comprobante de Pago Electrónico')], max_length=25, verbose_name='Tipo DTE'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sii_document_code',
            field=models.IntegerField(blank=True, choices=[(33, 'Factura Electrónica'), (34, 'Factura Exenta'), (39, 'Boleta Electrónica'), (41, 'Boleta Exenta'), (48, 'Comprobante de Pago Electrónico'), (56, 'Nota de Débito'), (61, 'Nota de Crédito')], help_text='Código oficial del tipo de DTE según SII de Chile', null=True, verbose_name='Código SII'),
        ),
    ]
