# Generated by Django 5.2.9 on 2026-01-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
        ('billing', '0006_invoice_service_obligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='accounting.journalentry'),
        ),
    ]
