# Generated by Django 5.2.9 on 2026-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_invoice_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
    ]
