# Generated by Django 5.2.10 on 2026-01-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_invoice_total_alter_invoice_total_net_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id'], 'verbose_name': 'Factura/Boleta', 'verbose_name_plural': 'Facturas y Boletas'},
        ),
    ]
