# Generated by Django 5.2.10 on 2026-01-20 05:04

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_budget_options_alter_journalentry_options'),
        ('billing', '0009_alter_invoice_options'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('purchasing', '0014_alter_purchaseorder_options_and_more'),
        ('sales', '0018_alter_saledelivery_options_alter_saleorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dte_type', models.CharField(choices=[('FACTURA', 'Factura Electrónica'), ('BOLETA', 'Boleta Electrónica'), ('PURCHASE_INV', 'Factura de Compra'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito')], max_length=20, verbose_name='Tipo DTE')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Folio')),
                ('document_attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Adjunto de Documento')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Contacto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'historical Factura/Boleta',
                'verbose_name_plural': 'historical Facturas y Boletas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
