# Generated by Django 5.2.14 on 2026-05-08 02:06

from django.db import migrations


def forwards(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        SaleOrder = apps.get_model('sales', 'SaleOrder')
        sale_ct = ContentType.objects.get_for_model(SaleOrder)
    except LookupError:
        sale_ct = None

    try:
        PurchaseOrder = apps.get_model('purchasing', 'PurchaseOrder')
        purchase_ct = ContentType.objects.get_for_model(PurchaseOrder)
    except LookupError:
        purchase_ct = None

    for inv in Invoice.objects.filter(source_content_type__isnull=True).iterator():
        if inv.sale_order_id and sale_ct:
            inv.source_content_type_id = sale_ct.id
            inv.source_object_id = inv.sale_order_id
            inv.save(update_fields=['source_content_type', 'source_object_id'])
        elif inv.purchase_order_id and purchase_ct:
            inv.source_content_type_id = purchase_ct.id
            inv.source_object_id = inv.purchase_order_id
            inv.save(update_fields=['source_content_type', 'source_object_id'])


def backwards(apps, schema_editor):
    Invoice = apps.get_model('billing', 'Invoice')
    Invoice.objects.update(source_content_type=None, source_object_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_gfk_source_order'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
