# Generated by Django 5.2.10 on 2026-01-20 20:52

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_historicalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='document_attachment',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Adjunto de Documento'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.UploadPath('invoices/'), validators=[core.validators.validate_file_size, core.validators.validate_file_extension], verbose_name='Adjunto de Documento'),
        ),
    ]
