# Generated by Django 5.2.10 on 2026-01-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_historicalinvoice_document_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
    ]
