# Generated by Django 5.2.10 on 2026-01-22 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_historicalinvoice_document_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Documento original que esta nota rectifica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura Rectificada'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrected_invoice',
            field=models.ForeignKey(blank=True, help_text='Documento original que esta nota rectifica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='billing.invoice', verbose_name='Factura Rectificada'),
        ),
    ]
