# Generated by Django 5.2.10 on 2026-01-22 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_historicalinvoice_corrected_invoice_and_more'),
        ('purchasing', '0017_alter_purchaseline_unit_cost_and_more'),
        ('sales', '0022_saledeliveryline_unit_price_gross_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('DRAFT', 'Borrador'), ('INVOICE_SELECTED', 'Factura Seleccionada'), ('ITEMS_SELECTED', 'Productos Seleccionados'), ('LOGISTICS_PENDING', 'Logística Pendiente'), ('LOGISTICS_COMPLETED', 'Logística Completada'), ('REGISTRATION_PENDING', 'Registro Pendiente'), ('PAYMENT_PENDING', 'Pago Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=30, verbose_name='Etapa Actual')),
                ('requires_logistics', models.BooleanField(default=False, help_text='True si hay productos stockeables que generan movimientos de inventario', verbose_name='Requiere Logística')),
                ('registration_deferred', models.BooleanField(default=False, help_text='True si el usuario eligió atrasar el registro contable', verbose_name='Registro Diferido')),
                ('selected_items', models.JSONField(blank=True, help_text='Lista de productos a devolver/ajustar: [{product_id, quantity, reason, unit_price, tax_amount}]', null=True, verbose_name='Productos Seleccionados')),
                ('logistics_data', models.JSONField(blank=True, help_text='Información de bodega, fecha, notas: {warehouse_id, date, notes}', null=True, verbose_name='Datos de Logística')),
                ('registration_data', models.JSONField(blank=True, help_text='Información de DTE: {dte_type, document_number, date}', null=True, verbose_name='Datos de Facturación')),
                ('payment_data', models.JSONField(blank=True, help_text='Información de pago/ajuste: {method, amount, account_id, apply_credit}', null=True, verbose_name='Datos de Pago')),
                ('reason', models.TextField(blank=True, help_text='Razón de la creación de esta nota', verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_invoice', models.ForeignKey(help_text='Factura POSTED que se está corrigiendo con esta nota', on_delete=django.db.models.deletion.PROTECT, related_name='correction_workflows', to='billing.invoice', verbose_name='Factura Original')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_note_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='billing.invoice', verbose_name='Nota de Crédito/Débito')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_workflows', to='purchasing.purchaseorder')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note_workflows', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Workflow de Nota',
                'verbose_name_plural': 'Workflows de Notas',
                'ordering': ['-created_at'],
            },
        ),
    ]
