# Generated by Django 6.0.5 on 2026-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_historicalinvoice_payment_method_add_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
