# Generated by Django 5.2.11 on 2026-02-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_add_sii_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='tax_period_closed',
            field=models.BooleanField(default=False, help_text='Indica si el período tributario de este documento está cerrado', verbose_name='Período Cerrado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_period_closed',
            field=models.BooleanField(default=False, help_text='Indica si el período tributario de este documento está cerrado', verbose_name='Período Cerrado'),
        ),
    ]
