# Generated by Django 6.0.6 on 2026-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_historicalinvoice_deleted_at_invoice_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
