# Generated by Django 5.2.10 on 2026-02-13 00:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_historicalinvoice_tax_period_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
    ]
