# Generated by Django 5.2.12 on 2026-03-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_historicalinvoice_date_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Descuento Total'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Descuento Total'),
        ),
    ]
