# Generated by Django 5.2.12 on 2026-03-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_historicalinvoice_total_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
