# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_timestampedmodel_accounting_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='noteworkflow',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
