# Generated by Django 5.2.14 on 2026-05-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_transactional_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Orden de compras y servicios', 'verbose_name_plural': 'Ordenes de compras y servicios'},
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='number',
            field=models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
