# Generated by Django 5.2.9 on 2026-01-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingsettings_default_card_treasury_account_and_more'),
        ('inventory', '0003_merge_20260102_1735'),
        ('purchasing', '0003_purchaseorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total recibida de esta línea', max_digits=10, verbose_name='Cantidad Recibida'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción Planificada'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('RECEIVED', 'Recibido')], default='PENDING', max_length=20, verbose_name='Estado de Recepción'),
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('receipt_date', models.DateField(verbose_name='Fecha de Recepción')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipt', to='accounting.journalentry')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder')),
                ('warehouse', models.ForeignKey(help_text='Bodega de recepción', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, help_text='Cantidad recibida en esta recepción', max_digits=10, verbose_name='Cantidad Recibida')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Costo unitario real al momento de la recepción', max_digits=12, verbose_name='Costo Unitario Real')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Costo Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.product')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereceipt')),
                ('stock_move', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipt_line', to='inventory.stockmove')),
            ],
            options={
                'verbose_name': 'Línea de Recepción',
                'verbose_name_plural': 'Líneas de Recepción',
            },
        ),
    ]
