# Generated by Django 5.2.9 on 2026-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseline_quantity_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de Despacho/Guía'),
        ),
    ]
