# Generated by Django 5.2.9 on 2026-01-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('purchasing', '0005_purchasereceipt_delivery_reference'),
        ('treasury', '0006_remove_payment_customer_remove_payment_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.contact'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
