# Generated by Django 5.2.9 on 2026-01-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_uom_uomcategory_product_purchase_uom_product_uom_and_more'),
        ('purchasing', '0006_alter_purchaseorder_supplier_delete_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.uom', verbose_name='Unidad'),
        ),
    ]
