# Generated by Django 5.2.9 on 2026-01-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
        ('purchasing', '0007_purchaseline_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt', to='accounting.journalentry'),
        ),
    ]
