# Generated by Django 5.2.9 on 2026-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_alter_purchaseorder_journal_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, help_text='Costo unitario real al momento de la recepción', max_digits=12, verbose_name='Costo Unitario Real'),
        ),
    ]
