# Generated by Django 6.0.5 on 2026-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_alter_historicalpurchaseorder_payment_method_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchasereceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpurchasereturn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
