# Generated by Django 5.2.10 on 2026-01-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_stockmove_journal_entry_and_more'),
        ('purchasing', '0009_alter_purchaseline_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceiptline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inventory.uom', verbose_name='Unidad'),
        ),
    ]
