# Generated by Django 6.0.6 on 2026-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_historicalpurchaseorder_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereceipt',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereceipt',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereturn',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereturn',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
