# Generated by Django 5.2.10 on 2026-01-15 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_workordermaterial_is_outsourced_and_more'),
        ('purchasing', '0010_purchasereceiptline_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='production.workorder', verbose_name='Orden de Trabajo'),
        ),
    ]
