# Generated by Django 5.2.10 on 2026-01-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_add_subscription_activation_fields'),
        ('purchasing', '0011_purchaseorder_work_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Orden de compras y servicios', 'verbose_name_plural': 'Ordenes de compras y servicios'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Bodega de recepción', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.warehouse'),
        ),
    ]
