# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_timestampedmodel_sales_purchasing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpurchaseorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasereceipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasereceipt',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasereturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasereturn',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasereceipt',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchasereceiptline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturnline',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereceipt',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereceipt',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereturn',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasereturn',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
