# Generated by Django 5.2.10 on 2026-01-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_alter_purchaseorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total recibida de esta línea', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa Impuesto %'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad recibida en esta recepción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, help_text='Costo unitario real al momento de la recepción', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario Real'),
        ),
    ]
