# Generated by Django 5.2.10 on 2026-01-20 01:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_budget_options_alter_journalentry_options'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('inventory', '0043_alter_pricingrule_options_alter_product_options_and_more'),
        ('production', '0012_alter_billofmaterials_options_and_more'),
        ('purchasing', '0013_alter_purchaseline_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de compras y servicios', 'verbose_name_plural': 'Ordenes de compras y servicios'},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-id'], 'verbose_name': 'Recepción de Compra', 'verbose_name_plural': 'Recepciones de Compra'},
        ),
        migrations.CreateModel(
            name='HistoricalPurchaseOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número Interno')),
                ('supplier_reference', models.CharField(blank=True, help_text='Ej: Nro Factura Proveedor', max_length=50, verbose_name='Referencia Proveedor')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('RECEIVED', 'Recibido'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('receiving_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('RECEIVED', 'Recibido')], default='PENDING', max_length=20, verbose_name='Estado de Recepción')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción Planificada')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega de recepción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
                ('work_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.workorder', verbose_name='Orden de Trabajo')),
            ],
            options={
                'verbose_name': 'historical Orden de compras y servicios',
                'verbose_name_plural': 'historical Ordenes de compras y servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
