# Generated by Django 5.2.10 on 2026-01-20 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_historicalpurchasereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=16, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=16, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, help_text='Costo unitario real al momento de la recepción', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario Real'),
        ),
    ]
