# Generated by Django 5.2.10 on 2026-01-20 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_historicalpurchasereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, help_text='Costo unitario real al momento de la recepción', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario Real'),
        ),
    ]
