# Generated by Django 5.2.10 on 2026-01-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_noteworkflow'),
        ('purchasing', '0018_historicalpurchasereturn_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchasereceipt',
            name='related_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to='billing.invoice'),
        ),
    ]
