# Generated by Django 5.2.10 on 2026-02-13 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0020_add_related_note_to_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
