# Generated by Django 5.2.9 on 2026-01-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0011_accountingsettings_stock_input_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUT/Tax ID')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_payable', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_payables', to='accounting.account', verbose_name='Cuenta por Pagar')),
                ('account_receivable', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_receivables', to='accounting.account', verbose_name='Cuenta por Cobrar')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
    ]
