# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcontact',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_contribution_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta para aportes de capital de este socio (3.1.02.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta de Aportes del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_earnings_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta para utilidades del ejercicio asignadas a este socio (3.1.06.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Utilidades del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_provisional_withdrawal_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta (contra patrimonio) para retiros provisorios de este socio (3.1.05.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Retiros Provisorios del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_receivable_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta (activo) para capital suscrito pendiente de pago de este socio (1.1.05.XX).', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Capital por Cobrar'),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_partner': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_partner': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='stock_move',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Para aportes o retiros en especie (inventario).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmove', verbose_name='Movimiento de Stock'),
        ),
    ]
