# Generated by Django 5.2.10 on 2026-01-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_default_customer',
            field=models.BooleanField(default=False, verbose_name='Cliente por Defecto'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_default_vendor',
            field=models.BooleanField(default=False, verbose_name='Proveedor por Defecto'),
        ),
    ]
