# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contacts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='treasury_movement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería'),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por'),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='executed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutada por'),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
        migrations.AddField(
            model_name='partnerequitystake',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_stakes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerequitystake',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.PROTECT, related_name='equity_stakes', to='contacts.contact', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.PROTECT, related_name='partner_transactions', to='contacts.contact', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='stock_move',
            field=models.ForeignKey(blank=True, help_text='Para aportes o retiros en especie (inventario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='inventory.stockmove', verbose_name='Movimiento de Stock'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='treasury_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería'),
        ),
        migrations.AddField(
            model_name='partnerequitystake',
            name='source_transaction',
            field=models.ForeignKey(blank=True, help_text='Transacción que originó este cambio de participación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_stakes', to='contacts.partnertransaction', verbose_name='Transacción Origen'),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='source_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Transacción que originó este cambio de participación.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.partnertransaction', verbose_name='Transacción Origen'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='contacts.contact', verbose_name='Socio'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='partner_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_line', to='contacts.partnertransaction', verbose_name='Transacción Generada'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='treasury_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_lines', to='treasury.treasurymovement', verbose_name='Pago Generado'),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por'),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutada por'),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distributions', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contacts.profitdistributionresolution', verbose_name='Resolución'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='distribution_resolution',
            field=models.ForeignKey(blank=True, help_text='Resolución de distribución de utilidades que originó esta transacción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='contacts.profitdistributionresolution', verbose_name='Resolución de Distribución'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='distribution_resolution',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Resolución de distribución de utilidades que originó esta transacción.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.profitdistributionresolution', verbose_name='Resolución de Distribución'),
        ),
        migrations.AddIndex(
            model_name='partnerequitystake',
            index=models.Index(fields=['partner', 'effective_from'], name='contacts_pa_partner_51c851_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerequitystake',
            index=models.Index(fields=['effective_until'], name='contacts_pa_effecti_7c67b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='profitdistributionresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'APPROVED', 'EXECUTED'])), fields=('fiscal_year',), name='unique_active_distribution_per_year'),
        ),
    ]
