# Generated by Django 5.2.10 on 2026-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_default_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
    ]
