# Generated by Django 5.2.12 on 2026-04-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_fiscalyear_id_alter_historicalfiscalyear_id'),
        ('contacts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='fiscal_year_obj',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='El ejercicio contable cerrado del cual proviene esta distribución.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.fiscalyear', verbose_name='Ejercicio Fiscal Relacionado'),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='fiscal_year_obj',
            field=models.OneToOneField(blank=True, help_text='El ejercicio contable cerrado del cual proviene esta distribución.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profit_distribution', to='accounting.fiscalyear', verbose_name='Ejercicio Fiscal Relacionado'),
        ),
        migrations.AlterField(
            model_name='historicalprofitdistributionresolution',
            name='fiscal_year',
            field=models.IntegerField(help_text='Año del ejercicio (campo denormalizado para búsquedas rápidas).', verbose_name='Año Fiscal'),
        ),
        migrations.AlterField(
            model_name='profitdistributionresolution',
            name='fiscal_year',
            field=models.IntegerField(help_text='Año del ejercicio (campo denormalizado para búsquedas rápidas).', verbose_name='Año Fiscal'),
        ),
    ]
