# Generated by Hand

from django.db import migrations

def populate_contact_codes(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')
    # We use a simple loop because we want them to have sequential codes based on ID
    # This matches what SequenceService would do but in bulk
    contacts = Contact.objects.all().order_by('id')
    for i, contact in enumerate(contacts, 1):
        if not contact.code:
            contact.code = str(i).zfill(6)
            contact.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_add_contact_code'),
    ]

    operations = [
        migrations.RunPython(populate_contact_codes),
    ]
