# Generated by Django 5.2.12 on 2026-04-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_historicalprofitdistributionresolution_fiscal_year_obj_and_more'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='partner_transaction',
        ),
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='treasury_movement',
        ),
        migrations.CreateModel(
            name='ProfitDistributionLineDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('DIVIDEND', 'Dividendo a Pagar'), ('REINVEST', 'Reinversión en Capital'), ('RETAINED', 'Utilidades Retenidas'), ('LOSS', 'Absorción de Pérdidas')], max_length=20, verbose_name='Destino')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='Monto')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='contacts.profitdistributionline', verbose_name='Línea base')),
                ('partner_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_line_destinations', to='contacts.partnertransaction', verbose_name='Transacción Generada')),
            ],
            options={
                'verbose_name': 'Destino de Línea de Distribución',
                'verbose_name_plural': 'Destinos de Líneas de Distribución',
            },
        ),
        migrations.CreateModel(
            name='ProfitDistributionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='Monto Pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='contacts.contact', verbose_name='Socio')),
                ('partner_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distribution_payments', to='contacts.partnertransaction', verbose_name='Transacción de Pago en Cuenta')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contacts.profitdistributionresolution', verbose_name='Resolución de Origen')),
                ('treasury_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_distribution_payments', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería')),
            ],
            options={
                'verbose_name': 'Pago de Dividendos',
                'verbose_name_plural': 'Pagos de Dividendos',
            },
        ),
    ]
