# Generated by Django 5.2.12 on 2026-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_options_historicalcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='credit_days',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Plazo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='credit_enabled',
            field=models.BooleanField(default=False, verbose_name='Crédito Habilitado'),
        ),
        migrations.AddField(
            model_name='contact',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Límite de Crédito'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_days',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Días Plazo'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_enabled',
            field=models.BooleanField(default=False, verbose_name='Crédito Habilitado'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Límite de Crédito'),
        ),
    ]
