# Generated by Django 5.2.12 on 2026-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_credit_days_contact_credit_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='credit_blocked',
            field=models.BooleanField(default=False, help_text='Si se marca, el contacto no podrá usar crédito bajo ninguna circunstancia.', verbose_name='Crédito Bloqueado'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_blocked',
            field=models.BooleanField(default=False, help_text='Si se marca, el contacto no podrá usar crédito bajo ninguna circunstancia.', verbose_name='Crédito Bloqueado'),
        ),
    ]
