# Generated by Django 5.2.12 on 2026-04-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_fiscalyear_id_alter_historicalfiscalyear_id'),
        ('contacts', '0006_alter_historicalpartnertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='partner_dividends_payable_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta (pasivo) para dividendos pendientes de pago de este socio (2.1.07.XX).', limit_choices_to={'account_type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_dividends_payable_contacts', to='accounting.account', verbose_name='Cuenta Dividendos por Pagar'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_dividends_payable_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta (pasivo) para dividendos pendientes de pago de este socio (2.1.07.XX).', limit_choices_to={'account_type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Dividendos por Pagar'),
        ),
    ]
