# Generated by Django 5.2.14 on 2026-05-08 00:07

from django.db import migrations

def promote_existing_partners(apps, schema_editor):
    from contacts.services import ContactPartnerService
    from contacts.models import Contact as RealContact
    
    partners = RealContact.objects.filter(is_partner=True)
    for partner in partners:
        missing_accounts = not all([
            partner.partner_contribution_account_id,
            partner.partner_provisional_withdrawal_account_id,
            partner.partner_earnings_account_id,
            partner.partner_dividends_payable_account_id,
        ])
        
        if missing_accounts:
            try:
                ContactPartnerService.promote_to_partner(partner)
            except Exception as e:
                print(f"Warning: Could not promote existing partner {partner.name}: {e}")

def reverse_promotion(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_partner_dividends_payable_account_and_more'),
    ]

    operations = [
        migrations.RunPython(promote_existing_partners, reverse_promotion),
    ]
