# Generated by Django 5.2.12 on 2026-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_credit_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='credit_auto_blocked',
            field=models.BooleanField(default=False, help_text='El sistema bloquea temporalmente al cliente si excede los días de mora configurados.', verbose_name='Auto-Bloqueado por Mora'),
        ),
        migrations.AddField(
            model_name='contact',
            name='credit_last_evaluated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Evaluación Automática'),
        ),
        migrations.AddField(
            model_name='contact',
            name='credit_risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo Riesgo'), ('MEDIUM', 'Riesgo Medio'), ('HIGH', 'Alto Riesgo'), ('CRITICAL', 'Riesgo Crítico / Incobrable')], default='LOW', max_length=20, verbose_name='Nivel de Riesgo'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_auto_blocked',
            field=models.BooleanField(default=False, help_text='El sistema bloquea temporalmente al cliente si excede los días de mora configurados.', verbose_name='Auto-Bloqueado por Mora'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_last_evaluated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Evaluación Automática'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='credit_risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo Riesgo'), ('MEDIUM', 'Riesgo Medio'), ('HIGH', 'Alto Riesgo'), ('CRITICAL', 'Riesgo Crítico / Incobrable')], default='LOW', max_length=20, verbose_name='Nivel de Riesgo'),
        ),
    ]
