# Generated by Django 5.2.12 on 2026-03-27 15:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_accountingsettings_partner_capital_contribution_account_and_more'),
        ('contacts', '0008_contact_credit_auto_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Marcar si este contacto es socio/accionista de la empresa.', verbose_name='Es Socio'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta de patrimonio individual para este socio.', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_contacts', to='accounting.account', verbose_name='Cuenta Particular del Socio'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner_equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de participación societaria.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner_since',
            field=models.DateField(blank=True, null=True, verbose_name='Socio Desde'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='is_partner',
            field=models.BooleanField(default=False, help_text='Marcar si este contacto es socio/accionista de la empresa.', verbose_name='Es Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta de patrimonio individual para este socio.', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Particular del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de participación societaria.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_since',
            field=models.DateField(blank=True, null=True, verbose_name='Socio Desde'),
        ),
    ]
