# Generated by Django 5.2.12 on 2026-03-27 16:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_alter_journalitem_partner_name'),
        ('contacts', '0009_contact_is_partner_contact_partner_account_and_more'),
        ('inventory', '0058_alter_historicalstockmove_adjustment_reason_and_more'),
        ('treasury', '0057_alter_historicaltreasurymovement_justify_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPartnerTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Monto de la transacción (siempre positivo).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_partner': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Socio')),
                ('stock_move', models.ForeignKey(blank=True, db_constraint=False, help_text='Para aportes o retiros en especie (inventario).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmove', verbose_name='Movimiento de Stock')),
                ('treasury_movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería')),
            ],
            options={
                'verbose_name': 'historical Transacción de Socio',
                'verbose_name_plural': 'historical Transacciones de Socios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Monto de la transacción (siempre positivo).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transaction', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('partner', models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.PROTECT, related_name='partner_transactions', to='contacts.contact', verbose_name='Socio')),
                ('stock_move', models.ForeignKey(blank=True, help_text='Para aportes o retiros en especie (inventario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='inventory.stockmove', verbose_name='Movimiento de Stock')),
                ('treasury_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería')),
            ],
            options={
                'verbose_name': 'Transacción de Socio',
                'verbose_name_plural': 'Transacciones de Socios',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
