# Generated by Django 5.2.12 on 2026-03-27 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_accountingsettings_partner_capital_social_account'),
        ('contacts', '0010_historicalpartnertransaction_partnertransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER', 'Transferencia de Participación'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER', 'Transferencia de Participación'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
