# Generated by Django 5.2.12 on 2026-03-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_historicalpartnertransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('DIVIDEND', 'Distribución de Utilidades'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
