# Generated by Django 6.0.6 on 2026-07-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_remove_contact_account_payable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnerequitystake',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='historicalprofitdistributionresolution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerequitystake',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerequitystake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profitdistributionline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionlinedestination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionlinedestination',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profitdistributionlinedestination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profitdistributionpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AddField(
            model_name='profitdistributionresolution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
