# Generated by Django 5.2.12 on 2026-03-31 01:15

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_accountingsettings_partner_current_year_earnings_account_and_more'),
        ('contacts', '0012_alter_historicalpartnertransaction_transaction_type_and_more'),
        ('treasury', '0057_alter_historicaltreasurymovement_justify_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='partner_contribution_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta para aportes de capital de este socio (3.1.02.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_contribution_contacts', to='accounting.account', verbose_name='Cuenta de Aportes del Socio'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner_earnings_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta para utilidades del ejercicio asignadas a este socio (3.1.06.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_earnings_contacts', to='accounting.account', verbose_name='Cuenta Utilidades del Socio'),
        ),
        migrations.AddField(
            model_name='contact',
            name='partner_provisional_withdrawal_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta (contra patrimonio) para retiros provisorios de este socio (3.1.05.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_prov_withdrawal_contacts', to='accounting.account', verbose_name='Cuenta Retiros Provisorios del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_contribution_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta para aportes de capital de este socio (3.1.02.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta de Aportes del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_earnings_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta para utilidades del ejercicio asignadas a este socio (3.1.06.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Utilidades del Socio'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_provisional_withdrawal_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta (contra patrimonio) para retiros provisorios de este socio (3.1.05.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Retiros Provisorios del Socio'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='partner_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta de patrimonio individual para este socio (3.1.04.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_contacts', to='accounting.account', verbose_name='Cuenta Particular del Socio'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='partner_equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cache desnormalizado del % vigente. Fuente de verdad: PartnerEquityStake.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='partner_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta de patrimonio individual para este socio (3.1.04.XX).', limit_choices_to={'account_type': 'EQUITY'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Particular del Socio'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='partner_equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cache desnormalizado del % vigente. Fuente de verdad: PartnerEquityStake.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)'),
        ),
        migrations.AlterField(
            model_name='historicalpartnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.CreateModel(
            name='HistoricalPartnerEquityStake',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)')),
                ('effective_from', models.DateField(help_text='Fecha desde la que rige este porcentaje de participación.', verbose_name='Vigente Desde')),
                ('effective_until', models.DateField(blank=True, help_text='Null = vigente actualmente. Se cierra cuando se registra un nuevo stake.', null=True, verbose_name='Vigente Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_partner': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Socio')),
                ('source_transaction', models.ForeignKey(blank=True, db_constraint=False, help_text='Transacción que originó este cambio de participación.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.partnertransaction', verbose_name='Transacción Origen')),
            ],
            options={
                'verbose_name': 'historical Registro de Participación',
                'verbose_name_plural': 'historical Registros de Participación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfitDistributionResolution',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='Año del ejercicio cuyas utilidades se están distribuyendo.', verbose_name='Año Fiscal')),
                ('resolution_date', models.DateField(help_text='Fecha del acta o resolución de distribución.', verbose_name='Fecha de Resolución')),
                ('net_result', models.DecimalField(decimal_places=0, help_text='Positivo = utilidad. Negativo = pérdida.', max_digits=16, verbose_name='Resultado Neto del Ejercicio')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('EXECUTED', 'Ejecutada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('acta_number', models.CharField(blank=True, help_text='Referencia al acta o documento societario.', max_length=50, verbose_name='Número de Acta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutada por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
            ],
            options={
                'verbose_name': 'historical Resolución de Distribución de Utilidades',
                'verbose_name_plural': 'historical Resoluciones de Distribución',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProfitDistributionResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='Año del ejercicio cuyas utilidades se están distribuyendo.', verbose_name='Año Fiscal')),
                ('resolution_date', models.DateField(help_text='Fecha del acta o resolución de distribución.', verbose_name='Fecha de Resolución')),
                ('net_result', models.DecimalField(decimal_places=0, help_text='Positivo = utilidad. Negativo = pérdida.', max_digits=16, verbose_name='Resultado Neto del Ejercicio')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('EXECUTED', 'Ejecutada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('acta_number', models.CharField(blank=True, help_text='Referencia al acta o documento societario.', max_length=50, verbose_name='Número de Acta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutada por')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_distributions', to='accounting.journalentry', verbose_name='Asiento Contable')),
            ],
            options={
                'verbose_name': 'Resolución de Distribución de Utilidades',
                'verbose_name_plural': 'Resoluciones de Distribución',
                'ordering': ['-fiscal_year', '-resolution_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistributionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_at_date', models.DecimalField(decimal_places=2, help_text='Porcentaje de participación vigente a la fecha de corte.', max_digits=5, verbose_name='Participación a la Fecha (%)')),
                ('gross_amount', models.DecimalField(decimal_places=0, help_text='Monto que corresponde según el % de participación.', max_digits=16, verbose_name='Monto Bruto')),
                ('provisional_withdrawals_offset', models.DecimalField(decimal_places=0, default=0, help_text='Total de retiros provisorios realizados durante el ejercicio a liquidar.', max_digits=14, verbose_name='Retiros Provisorios a Descontar')),
                ('net_amount', models.DecimalField(decimal_places=0, help_text='gross - provisional_withdrawals_offset = neto a pagar/reinvertir.', max_digits=16, verbose_name='Monto Neto')),
                ('destination', models.CharField(choices=[('DIVIDEND', 'Dividendo a Pagar'), ('REINVEST', 'Reinversión en Capital'), ('RETAINED', 'Utilidades Retenidas'), ('LOSS', 'Absorción de Pérdidas')], default='DIVIDEND', max_length=20, verbose_name='Destino')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='contacts.contact', verbose_name='Socio')),
                ('partner_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_line', to='contacts.partnertransaction', verbose_name='Transacción Generada')),
                ('treasury_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_lines', to='treasury.treasurymovement', verbose_name='Pago Generado')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contacts.profitdistributionresolution', verbose_name='Resolución')),
            ],
            options={
                'verbose_name': 'Línea de Distribución',
                'verbose_name_plural': 'Líneas de Distribución',
                'ordering': ['resolution', 'partner__name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpartnertransaction',
            name='distribution_resolution',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Resolución de distribución de utilidades que originó esta transacción.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.profitdistributionresolution', verbose_name='Resolución de Distribución'),
        ),
        migrations.AddField(
            model_name='partnertransaction',
            name='distribution_resolution',
            field=models.ForeignKey(blank=True, help_text='Resolución de distribución de utilidades que originó esta transacción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_transactions', to='contacts.profitdistributionresolution', verbose_name='Resolución de Distribución'),
        ),
        migrations.CreateModel(
            name='PartnerEquityStake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Participación (%)')),
                ('effective_from', models.DateField(help_text='Fecha desde la que rige este porcentaje de participación.', verbose_name='Vigente Desde')),
                ('effective_until', models.DateField(blank=True, help_text='Null = vigente actualmente. Se cierra cuando se registra un nuevo stake.', null=True, verbose_name='Vigente Hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_stakes_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.PROTECT, related_name='equity_stakes', to='contacts.contact', verbose_name='Socio')),
                ('source_transaction', models.ForeignKey(blank=True, help_text='Transacción que originó este cambio de participación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_stakes', to='contacts.partnertransaction', verbose_name='Transacción Origen')),
            ],
            options={
                'verbose_name': 'Registro de Participación',
                'verbose_name_plural': 'Registros de Participación',
                'ordering': ['-effective_from', '-id'],
                'indexes': [models.Index(fields=['partner', 'effective_from'], name='contacts_pa_partner_51c851_idx'), models.Index(fields=['effective_until'], name='contacts_pa_effecti_7c67b7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profitdistributionresolution',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'APPROVED', 'EXECUTED'])), fields=('fiscal_year',), name='unique_active_distribution_per_year'),
        ),
    ]
