# Generated by Django 5.2.12 on 2026-03-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contact_partner_contribution_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='partner_account',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='partner_account',
        ),
    ]
