# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contact_created_by_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpartnerequitystake',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpartnerequitystake',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalpartnertransaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpartnertransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalprofitdistributionresolution',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='partnerequitystake',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='partnerequitystake',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partnertransaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='partnertransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionlinedestination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionlinedestination',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionlinedestination',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionpayment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionpayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profitdistributionresolution',
            name='deleted_at',
        ),
    ]
