# Generated by Django 6.0.6 on 2026-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_remove_contact_created_by_remove_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('RETAINED', 'Utilidades Retenidas (Asignación)'), ('RETAINED_MOB', 'Movilización de Utilidades Retenidas (Salida)'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('CONTRIB_TRANSFER_IN', 'Aporte por Transferencia (Entrada)'), ('CONTRIB_TRANSFER_OUT', 'Aporte por Transferencia (Salida)'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('RETAINED', 'Utilidades Retenidas (Asignación)'), ('RETAINED_MOB', 'Movilización de Utilidades Retenidas (Salida)'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('CONTRIB_TRANSFER_IN', 'Aporte por Transferencia (Entrada)'), ('CONTRIB_TRANSFER_OUT', 'Aporte por Transferencia (Salida)'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
