# Generated by Django 5.2.12 on 2026-03-31 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_remove_accountingsettings_partner_current_account_and_more'),
        ('contacts', '0014_remove_contact_partner_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='partner_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Subcuenta (activo) para capital suscrito pendiente de pago de este socio (1.1.05.XX).', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_receivable_contacts', to='accounting.account', verbose_name='Cuenta Capital por Cobrar'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_receivable_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Subcuenta (activo) para capital suscrito pendiente de pago de este socio (1.1.05.XX).', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Capital por Cobrar'),
        ),
        migrations.AlterField(
            model_name='historicalpartnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('RETAINED', 'Utilidades Retenidas (Asignación)'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CAPITAL_CASH', 'Aporte de Capital (Efectivo)'), ('CAPITAL_INVENTORY', 'Aporte de Capital (Inventario)'), ('CAPITAL_RETURN', 'Devolución de Capital'), ('PROV_WITHDRAWAL', 'Retiro Provisorio (Anticipo Utilidades)'), ('WITHDRAWAL', 'Retiro de Utilidades'), ('LOAN_IN', 'Préstamo del Socio a la Empresa'), ('LOAN_OUT', 'Préstamo de la Empresa al Socio'), ('DIVIDEND', 'Distribución de Utilidades (Asignación)'), ('DIVIDEND_PAY', 'Pago de Dividendo'), ('REINVESTMENT', 'Reinversión de Utilidades'), ('RETAINED', 'Utilidades Retenidas (Asignación)'), ('LOSS_ABSORB', 'Absorción de Pérdidas'), ('SUBSCRIPTION', 'Suscripción de Capital'), ('TRANSFER_IN', 'Transferencia Recibida'), ('TRANSFER_OUT', 'Transferencia Entregada'), ('REDUCTION', 'Reducción de Capital'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Transacción'),
        ),
    ]
