# Generated by Django 5.2.12 on 2026-03-31 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_remove_accountingsettings_partner_current_account_and_more'),
        ('contacts', '0015_contact_partner_receivable_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capital_receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Capital por Cobrar (Activo)')),
                ('current_period_earnings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Utilidad del Ejercicio Actual')),
                ('dividends_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Dividendos por Pagar (Pasivo)')),
                ('retained_earnings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Utilidades Retenidas (Consolidada)')),
                ('root_capital_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Cuenta Raíz de Capital Social')),
            ],
            options={
                'verbose_name': 'Configuración de Socios',
                'verbose_name_plural': 'Configuraciones de Socios',
            },
        ),
    ]
