# Generated by Django 5.2.12 on 2026-03-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_partnersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerSettings',
        ),
    ]
