# Generated by Django 5.2.9 on 2025-12-30 23:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('state', models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Libro Diario',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: 1.1.01.001', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20, verbose_name='Tipo')),
                ('is_reconcilable', models.BooleanField(default=False, verbose_name='Conciliable')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, help_text='Cliente o Proveedor asociado', max_length=255, verbose_name='Socio/Empresa')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Etiqueta')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Haber')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Apunte Contable',
                'verbose_name_plural': 'Apuntes Contables',
            },
        ),
    ]
