# Generated by Django 5.2.9 on 2025-12-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_tax_account',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='asset_prefix',
            field=models.CharField(default='1', max_length=5, verbose_name='Prefijo Activos'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='code_format',
            field=models.CharField(default='X.X.XX.XXX', max_length=50, verbose_name='Formato de Código'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tax_payable', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_tax_receivable', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='equity_prefix',
            field=models.CharField(default='3', max_length=5, verbose_name='Prefijo Patrimonio'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expense_prefix',
            field=models.CharField(default='5', max_length=5, verbose_name='Prefijo Gastos'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='income_prefix',
            field=models.CharField(default='4', max_length=5, verbose_name='Prefijo Ingresos'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='liability_prefix',
            field=models.CharField(default='2', max_length=5, verbose_name='Prefijo Pasivos'),
        ),
    ]
