# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('contacts', '0003_initial'),
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournalentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.accountingperiod', verbose_name='Periodo Contable'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='tax.accountingperiod', verbose_name='Periodo Contable'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Contacto asociado a este apunte contable (socio, cliente o proveedor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_items', to='contacts.contact', verbose_name='Socio/Contacto'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget', 'account', 'year', 'month')},
        ),
    ]
