# Generated by Django 5.2.9 on 2025-12-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_accountingsettings_default_tax_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_card_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_card', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_cash', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_transfer', to='accounting.account'),
        ),
    ]
