# Generated by Django 5.2.9 on 2025-12-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accountingsettings_default_card_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Número'),
        ),
    ]
