# Generated by Django 5.2.12 on 2026-04-13 20:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_fiscalyear_id_alter_historicalfiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Tasa porcentual a aplicar (ej. 19.00) para desglosar el neto del IVA.', max_digits=5, verbose_name='Tasa de IVA por Defecto (%)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bs_category',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Activo Corriente'), ('INVENTORY', 'Inventario'), ('NON_CURRENT_ASSET', 'Activo No Corriente'), ('CURRENT_LIABILITY', 'Pasivo Corriente'), ('NON_CURRENT_LIABILITY', 'Pasivo No Corriente'), ('EQUITY', 'Patrimonio')], max_length=30, null=True, verbose_name='Categoría Balance'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='bs_category',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Activo Corriente'), ('INVENTORY', 'Inventario'), ('NON_CURRENT_ASSET', 'Activo No Corriente'), ('CURRENT_LIABILITY', 'Pasivo Corriente'), ('NON_CURRENT_LIABILITY', 'Pasivo No Corriente'), ('EQUITY', 'Patrimonio')], max_length=30, null=True, verbose_name='Categoría Balance'),
        ),
    ]
