# Generated by Django 5.2.9 on 2026-01-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_journalentry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, help_text='Ej: 1.1.01.001', max_length=20, unique=True, verbose_name='Código'),
        ),
    ]
