# Generated by Django 5.2.12 on 2026-04-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_accountingsettings_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='billing_model',
            field=models.CharField(choices=[('ALWAYS_BOLETA', 'Modelo A: Siempre emitir boleta (Incluso con pago electrónico)'), ('TERMINAL_AS_BOLETA', 'Modelo B: Terminal reemplaza boleta (No emitir DTE 39/41 si hay comprobante DTE 48)')], default='ALWAYS_BOLETA', help_text='Determina si se debe emitir boleta cuando se recibe un comprobante de pago electrónico de máquina en el POS.', max_length=20, verbose_name='Modelo de Emisión POS'),
        ),
    ]
