# Generated by Django 5.2.9 on 2026-01-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('AVERAGE', 'Promedio Ponderado'), ('FIFO', 'FIFO (Primero en entrar, primero en salir)'), ('LIFO', 'LIFO (Último en entrar, primero en salir)')], default='AVERAGE', max_length=20, verbose_name='Método de Valoración de Inventario'),
        ),
    ]
