# Generated by Django 5.2.9 on 2026-01-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingsettings_inventory_valuation_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_card_account',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_cash_account',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_transfer_account',
        ),
    ]
