# Generated by Django 5.2.9 on 2026-01-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_accountingsettings_default_card_account_and_more'),
        ('treasury', '0005_alter_payment_account_treasuryaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_card_treasury_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Predeterminada (Tarjeta)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_cash_treasury_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treasury.treasuryaccount', verbose_name='Caja Predeterminada (Efectivo)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_transfer_treasury_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Predeterminada (Transferencia)'),
        ),
    ]
