# Generated by Django 5.2.9 on 2026-01-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingsettings_default_card_treasury_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_card_treasury_account',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_cash_treasury_account',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='default_transfer_treasury_account',
        ),
    ]
