# Generated by Django 5.2.9 on 2026-01-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_accountingsettings_default_card_treasury_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='stock_input_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de Pasivo (ej: Proveedores por Facturar) usada como contrapartida en recepciones.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_stock_input', to='accounting.account', verbose_name='Cuenta de Entrada de Stock (Puente)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='stock_output_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta usada como contrapartida en salidas no facturadas (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_stock_output', to='accounting.account', verbose_name='Cuenta de Salida de Stock (Puente)'),
        ),
    ]
