# Generated by Django 5.2.9 on 2026-01-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_accountingsettings_stock_input_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_advance_payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_advances', to='accounting.account', verbose_name='Cuenta de Anticipos de Clientes (Pasivo)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_prepayment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_prepayments', to='accounting.account', verbose_name='Cuenta de Anticipos a Proveedores (Activo)'),
        ),
    ]
