# Generated by Django 5.2.14 on 2026-05-08 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_timestampedmodel_t14'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 16, 44, 318456, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 16, 44, 318789, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
