# Generated by Django 5.2.14 on 2026-05-08 01:59
# T-41 — Backfill JournalEntry.source_document (GFK) from legacy reverse FKs.
#
# Bugfix 2026-05-08: declared explicit cross-app dependencies on the
# migrations that introduce `journal_entry` field on each consulted model.
# Without these, Django's topological migration sort could run this data
# migration before the FK columns exist on a fresh DB (broke
# `manage.py test` test-database creation).

from django.db import migrations


def _has_journal_entry(model_cls) -> bool:
    """Defensive check: the historical model has a `journal_entry` field."""
    try:
        model_cls._meta.get_field('journal_entry')
        return True
    except Exception:
        return False


def forwards(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    def process_model(app_label, model_name):
        try:
            ModelClass = apps.get_model(app_label, model_name)
        except LookupError:
            return
        # Skip silently if the historical schema doesn't yet have
        # journal_entry — happens if dependency ordering shifts.
        if not _has_journal_entry(ModelClass):
            return

        ct = ContentType.objects.get_for_model(ModelClass)

        for obj in ModelClass.objects.exclude(journal_entry__isnull=True).iterator():
            je = obj.journal_entry
            if not je.source_content_type_id:
                je.source_content_type_id = ct.id
                je.source_object_id = obj.id
                je.save(update_fields=['source_content_type', 'source_object_id'])

    process_model('billing', 'Invoice')
    process_model('treasury', 'TreasuryMovement')
    process_model('sales', 'SaleOrder')
    process_model('purchasing', 'PurchaseOrder')
    process_model('inventory', 'StockMove')


def backwards(apps, schema_editor):
    JournalEntry = apps.get_model('accounting', 'JournalEntry')
    JournalEntry.objects.update(source_content_type=None, source_object_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_journal_entry_gfk_source'),
        ('contenttypes', '0002_remove_content_type_name'),
        # Cross-app dependencies — guarantee `journal_entry` field exists on
        # every model consulted by `forwards()`. Each entry points to the
        # migration that establishes that field's schema or the post-
        # TransactionalDocument migration where it is redeclared.
        ('billing', '0008_invoice_transactional_document'),
        ('sales', '0006_saleorder_transactional_document'),
        ('purchasing', '0002_purchaseorder_transactional_document'),
        ('inventory', '0001_initial'),
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
