# Generated by Django 5.2.9 on 2026-01-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_budget_budgetitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='month',
            field=models.IntegerField(default=1, help_text='Mes del presupuesto (1-12)', verbose_name='Mes'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget', 'account', 'month')},
        ),
    ]
