# Generated by Django 5.2.14 on 2026-05-08 01:59

from django.db import migrations

def forwards(apps, schema_editor):
    JournalEntry = apps.get_model('accounting', 'JournalEntry')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    def process_model(app_label, model_name):
        try:
            ModelClass = apps.get_model(app_label, model_name)
            ct = ContentType.objects.get_for_model(ModelClass)
        except LookupError:
            return

        for obj in ModelClass.objects.exclude(journal_entry__isnull=True).iterator():
            je = obj.journal_entry
            if not je.source_content_type_id:
                je.source_content_type_id = ct.id
                je.source_object_id = obj.id
                je.save(update_fields=['source_content_type', 'source_object_id'])

    process_model('billing', 'Invoice')
    process_model('treasury', 'TreasuryMovement')
    process_model('sales', 'SaleOrder')
    process_model('purchasing', 'PurchaseOrder')
    process_model('inventory', 'StockMove')


def backwards(apps, schema_editor):
    JournalEntry = apps.get_model('accounting', 'JournalEntry')
    JournalEntry.objects.update(source_content_type=None, source_object_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_journal_entry_gfk_source'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
