# Generated by Django 5.2.9 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_budgetitem_unique_together_budgetitem_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cf_category',
            field=models.CharField(blank=True, choices=[('OPERATING', 'Actividades de Operación'), ('INVESTING', 'Actividades de Inversión'), ('FINANCING', 'Actividades de Financiación'), ('DEP_AMORT', 'Depreciación y Amortización (No Efectivo)')], max_length=30, null=True, verbose_name='Categoría Flujo de Caja'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_category',
            field=models.CharField(blank=True, choices=[('REVENUE', 'Ingresos Operacionales'), ('COST_OF_SALES', 'Costo de Ventas'), ('OPERATING_EXPENSE', 'Gastos Operacionales'), ('NON_OPERATING_REVENUE', 'Ingresos No Operacionales'), ('NON_OPERATING_EXPENSE', 'Gastos No Operacionales'), ('TAX_EXPENSE', 'Impuesto a la Renta')], max_length=30, null=True, verbose_name='Categoría Estado Resultados'),
        ),
    ]
