# Generated by Django 5.2.9 on 2026-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_account_cf_category_account_is_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_selectable',
            field=models.BooleanField(default=True, help_text='Si es falso, la cuenta solo servirá como categoría estructural y no podrá recibir asientos.', verbose_name='Es Seleccionable'),
        ),
    ]
