# Generated by Django 5.2.9 on 2026-01-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_account_is_selectable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_selectable',
        ),
    ]
