# Generated by Django 5.2.9 on 2026-01-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_account_is_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bs_category',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Activo Corriente'), ('NON_CURRENT_ASSET', 'Activo No Corriente'), ('CURRENT_LIABILITY', 'Pasivo Corriente'), ('NON_CURRENT_LIABILITY', 'Pasivo No Corriente'), ('EQUITY', 'Patrimonio')], max_length=30, null=True, verbose_name='Categoría Balance'),
        ),
    ]
