# Generated by Django 5.2.10 on 2026-01-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_account_bs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_consumable_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto usada por defecto para productos consumibles (tintas, papel, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_consumable', to='accounting.account', verbose_name='Cuenta de Gastos Consumibles'),
        ),
    ]
