# Generated by Django 5.2.9 on 2026-01-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='adjustment_expense_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto para registrar mermas o pérdidas de inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_adjustment_expense', to='accounting.account', verbose_name='Cuenta de Gasto por Ajuste (Mermas)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='adjustment_income_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de ingreso para registrar ganancias de inventario (ej: Otros Ingresos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_adjustment_income', to='accounting.account', verbose_name='Cuenta de Ingreso por Ajuste (Sobrantes)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='initial_inventory_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta usada como contrapartida al cargar el stock por primera vez.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_initial_inventory', to='accounting.account', verbose_name='Cuenta de Inventario Inicial (Patrimonio/Contrapartida)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='revaluation_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta usada para ajustes de costo sin cambio físico en stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_revaluation', to='accounting.account', verbose_name='Cuenta de Revalorización'),
        ),
    ]
