# Generated by Django 6.0.5 on 2026-06-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_journalentry_is_manual_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='check_portfolio_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de activo (documentos por cobrar) donde se registran los cheques de terceros recibidos hasta su depósito/cobro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_check_portfolio', to='accounting.account', verbose_name='Cuenta Cheques en Cartera'),
        ),
    ]
