# Generated by Django 5.2.9 on 2026-01-12 19:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_accountingsettings_adjustment_expense_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Monto Presupuestado'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, verbose_name='Haber'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, verbose_name='Debe'),
        ),
    ]
