# Generated by Django 5.2.10 on 2026-01-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_budgetitem_amount_alter_journalitem_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_service_expense_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto usada por defecto para productos de tipo servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_service_expense', to='accounting.account', verbose_name='Cuenta de Gastos por Servicios'),
        ),
    ]
