# Generated by Django 6.0.5 on 2026-06-06 02:08

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0023_accountingsettings_loan_commission_expense_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingsettings",
            name="card_minimum_payment_block",
            field=models.BooleanField(
                default=False,
                help_text="Si True, rechaza pagos parciales menores al `minimum_payment` del statement con ValidationError. Si False (default), permite cualquier pago parcial positivo.",
                verbose_name="Bloquear Pago Parcial < Mínimo",
            ),
        ),
        migrations.AddField(
            model_name="accountingsettings",
            name="card_punitory_monthly_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="Tasa mensual que cobra el emisor sobre el saldo impago del statement después del due_date (ej. 0.05 = 5%/mes). 0 = desactiva el cálculo automático.",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Tasa Punitoria Mensual Tarjeta (0–1)",
            ),
        ),
    ]
