# Generated by Django 5.2.10 on 2026-01-15 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_add_type_based_inventory_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, help_text='⚠️ DEPRECATED: Use cuentas específicas por tipo de producto. Se mantiene como fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_inventory', to='accounting.account', verbose_name='Cuenta Inventario General (Deprecated)'),
        ),
    ]
