# Generated by Django 5.2.10 on 2026-01-15 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_accountingsettings_default_inventory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_service_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de ingreso usada por defecto para productos de tipo servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_service_revenue', to='accounting.account', verbose_name='Cuenta de Ingresos por Servicios'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_subscription_expense_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto usada por defecto para productos de tipo suscripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_subscription_expense', to='accounting.account', verbose_name='Cuenta de Gastos por Suscripciones'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_subscription_revenue_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de ingreso usada por defecto para productos de tipo suscripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_subscription_revenue', to='accounting.account', verbose_name='Cuenta de Ingresos por Suscripciones'),
        ),
    ]
