# Generated by Django 5.2.10 on 2026-01-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_accountingsettings_default_service_revenue_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Año'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget', 'account', 'year', 'month')},
        ),
    ]
