# Generated by Django 5.2.10 on 2026-01-17 19:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_budgetitem_unique_together_budgetitem_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Presupuestado'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haber'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debe'),
        ),
    ]
