# Generated by Django 5.2.10 on 2026-01-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_budgetitem_amount_alter_journalitem_credit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-id'], 'verbose_name': 'Presupuesto', 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-id'], 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Libro Diario'},
        ),
    ]
