# Generated by Django 5.2.10 on 2026-01-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_historicaljournalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='inventory_valuation_method',
            field=models.CharField(choices=[('AVERAGE', 'Promedio Ponderado')], default='AVERAGE', max_length=20, verbose_name='Método de Valoración de Inventario'),
        ),
    ]
