# Generated by Django 5.2.10 on 2026-01-20 21:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_accountingsettings_inventory_valuation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Presupuestado'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haber'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Debe'),
        ),
    ]
