# Generated by Django 5.2.10 on 2026-01-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_accountingsettings_inventory_valuation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='manufactured_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 5.1.02 - Para productos MANUFACTURABLE fabricados internamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_manufactured_cogs', to='accounting.account', verbose_name='Cuenta Costo de Producción'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='merchandise_cogs_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 5.1.01 - Para productos STORABLE comprados para reventa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_merchandise_cogs', to='accounting.account', verbose_name='Cuenta Costo de Mercaderías'),
        ),
    ]
