# Generated by Django 5.2.15 on 2026-06-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0031_remove_default_tax_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingsettings",
            name="default_consumable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de gasto usada por defecto para productos consumibles (tintas, papel, etc.) - ej: 5.2.05",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_consumable",
                to="accounting.account",
                verbose_name="Default Expense - Consumibles (CONSUMABLE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="default_service_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de gasto usada por defecto para productos de tipo servicio (ej: 5.1.03).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_service_expense",
                to="accounting.account",
                verbose_name="Default Expense - Servicios (SERVICE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="default_service_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingreso usada por defecto para productos de tipo servicio (ej: 4.1.02).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_service_revenue",
                to="accounting.account",
                verbose_name="Default Revenue - Servicios (SERVICE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="default_subscription_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de gasto usada por defecto para productos de tipo suscripción (ej: 5.1.04).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_subscription_expense",
                to="accounting.account",
                verbose_name="Default Expense - Suscripciones (SUBSCRIPTION)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="default_subscription_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingreso usada por defecto para productos de tipo suscripción (ej: 4.1.03).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_subscription_revenue",
                to="accounting.account",
                verbose_name="Default Revenue - Suscripciones (SUBSCRIPTION)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="manufacturable_inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de activo para productos MANUFACTURABLE (ej: 1.1.03.03)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_manufacturable_inventory",
                to="accounting.account",
                verbose_name="Inventory Asset - Fabricables (MANUFACTURABLE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="manufactured_cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta 5.1.02 - Costo de ventas para productos MANUFACTURABLE fabricados internamente",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_manufactured_cogs",
                to="accounting.account",
                verbose_name="Default COGS - Fabricados (MANUFACTURABLE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="merchandise_cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta 5.1.01 - Costo de ventas para productos STORABLE comprados para reventa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_merchandise_cogs",
                to="accounting.account",
                verbose_name="Default COGS - Mercaderías (STORABLE)",
            ),
        ),
        migrations.AlterField(
            model_name="accountingsettings",
            name="storable_inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de activo para productos STORABLE (ej: 1.1.03.01)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_storable_inventory",
                to="accounting.account",
                verbose_name="Inventory Asset - Almacenables (STORABLE)",
            ),
        ),
    ]
