# Generated by Django 5.2.10 on 2026-02-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_accountingsettings_manufactured_cogs_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='bank_commission_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar diferencias por comisiones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_bank_commission', to='accounting.account', verbose_name='Cuenta de Comisiones Bancarias'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='error_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar errores de registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_error_adj', to='accounting.account', verbose_name='Cuenta de Ajuste por Error'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='exchange_difference_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar diferencias por tipo de cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_exchange_diff', to='accounting.account', verbose_name='Cuenta de Diferencia de Cambio'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='interest_income_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar diferencias por intereses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_interest_income', to='accounting.account', verbose_name='Cuenta de Intereses Ganados'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='miscellaneous_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta por defecto para otros ajustes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_misc_adj', to='accounting.account', verbose_name='Cuenta de Ajustes Varios'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='rounding_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar diferencias de redondeo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_rounding', to='accounting.account', verbose_name='Cuenta de Ajuste por Redondeo'),
        ),
    ]
