# Generated by Django 6.0.6 on 2026-07-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_accountingsettings_default_consumable_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_category', models.CharField(blank=True, choices=[('REVENUE', 'Ingresos Operacionales'), ('COST_OF_SALES', 'Costo de Ventas'), ('OPERATING_EXPENSE', 'Gastos Operacionales'), ('NON_OPERATING_REVENUE', 'Ingresos No Operacionales'), ('NON_OPERATING_EXPENSE', 'Gastos No Operacionales'), ('TAX_EXPENSE', 'Impuesto a la Renta')], max_length=30, null=True, verbose_name='Categoría ER (snapshot)')),
                ('bs_category', models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Activo Corriente'), ('INVENTORY', 'Inventario'), ('NON_CURRENT_ASSET', 'Activo No Corriente'), ('CURRENT_LIABILITY', 'Pasivo Corriente'), ('NON_CURRENT_LIABILITY', 'Pasivo No Corriente'), ('EQUITY', 'Patrimonio')], max_length=30, null=True, verbose_name='Categoría Balance (snapshot)')),
                ('cf_category', models.CharField(blank=True, choices=[('OPERATING', 'Actividades de Operación'), ('INVESTING', 'Actividades de Inversión'), ('FINANCING', 'Actividades de Financiación'), ('DEP_AMORT', 'Depreciación y Amortización (No Efectivo)')], max_length=30, null=True, verbose_name='Categoría Flujo Caja (snapshot)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_year_mappings', to='accounting.account')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Mapeo de cuenta por ejercicio',
                'verbose_name_plural': 'Mapeos de cuentas por ejercicio',
                'indexes': [models.Index(fields=['fiscal_year', 'account'], name='accounting__fiscal__0026b0_idx')],
                'unique_together': {('fiscal_year', 'account')},
            },
        ),
    ]
