# Generated by Django 5.2.10 on 2026-02-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_accountingsettings_bank_commission_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='card_commission_account',
            field=models.ForeignKey(blank=True, help_text='Para justificar diferencias por comisiones de tarjetas (Transbank, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_card_commission', to='accounting.account', verbose_name='Cuenta de Comisiones de Tarjeta'),
        ),
    ]
