# Generated by Django 5.2.10 on 2026-02-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_accountingsettings_card_commission_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_cash_difference_gain_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de ingreso para registrar sobrantes de caja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_diff_gain', to='accounting.account', verbose_name='Cuenta Ganancia Diferencia Caja POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_cash_difference_loss_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto para registrar faltantes de caja.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_diff_loss', to='accounting.account', verbose_name='Cuenta Pérdida Diferencia Caja POS'),
        ),
    ]
