# Generated by Django 6.0.6 on 2026-07-01 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_fiscal_year_account_mapping_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('RECONCILIATION', 'Conciliación'), ('VALUATION', 'Valorización'), ('ADJUSTMENT', 'Ajuste'), ('DOCUMENT', 'Documentación'), ('OTHER', 'Otro')], max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Item de Cierre',
                'verbose_name_plural': 'Plantillas de Items de Cierre',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYearClosingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_fiscal_year_checklists', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closing_checklist', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Checklist de Cierre de Ejercicio',
                'verbose_name_plural': 'Checklists de Cierre de Ejercicio',
            },
        ),
        migrations.CreateModel(
            name='ClosingChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='accounting.fiscalyear')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounting.closingchecklisttemplate')),
            ],
            options={
                'verbose_name': 'Item de Checklist de Cierre',
                'verbose_name_plural': 'Items de Checklist de Cierre',
                'unique_together': {('fiscal_year', 'template')},
            },
        ),
    ]
