# Generated by Django 5.2.10 on 2026-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_add_pos_diff_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_cash_difference_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Montos mayores a este valor requieren aprobación manual.', max_digits=12, verbose_name='Umbral de Aprobación de Diferencias POS'),
        ),
    ]
