# Generated by Django 5.2.10 on 2026-02-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_accountingsettings_pos_cash_difference_approval_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_other_inflow_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para otros ingresos de efectivo en el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_other_inflow', to='accounting.account', verbose_name='Cuenta Otros Ingresos POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_other_outflow_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para otros egresos de efectivo en el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_other_outflow', to='accounting.account', verbose_name='Cuenta Otros Egresos POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_partner_withdrawal_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar retiros de socios desde el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_withdrawal', to='accounting.account', verbose_name='Cuenta Retiro Socio POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_theft_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar faltantes por robo detectados en el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_theft', to='accounting.account', verbose_name='Cuenta Faltante por Robo POS'),
        ),
    ]
