# Generated by Django 5.2.11 on 2026-02-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_accountingsettings_pos_other_inflow_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_cashback_error_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar diferencias por vueltos incorrectos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_cashback', to='accounting.account', verbose_name='Cuenta Vuelto Incorrecto POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_counting_error_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar diferencias por errores de conteo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_counting', to='accounting.account', verbose_name='Cuenta Error de Conteo POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_rounding_adjustment_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar diferencias por redondeo en el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_rounding', to='accounting.account', verbose_name='Cuenta Redondeo POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_system_error_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar diferencias por errores del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_system_error', to='accounting.account', verbose_name='Cuenta Error de Sistema POS'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_tip_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar propinas recibidas en el POS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_pos_tip', to='accounting.account', verbose_name='Cuenta Propinas POS'),
        ),
    ]
