# Generated by Django 6.0.6 on 2026-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_account_deleted_at_accountingsettings_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
