# Generated by Django 5.2.11 on 2026-02-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingsettings_pos_cashback_error_account_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='accountingsettings',
                    name='card_commission_account',
                ),
            ],
        ),
    ]
