# Generated by Django 5.2.10 on 2026-02-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_accountingsettings_card_commission_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='terminal_commission_bridge_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de activo/puente para retenciones de comisión sin factura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_terminal_comm_bridge', to='accounting.account', verbose_name='Cuenta Puente Comisión Terminales'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='terminal_iva_bridge_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de activo/puente para el IVA de comisiones sin factura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_terminal_iva_bridge', to='accounting.account', verbose_name='Cuenta Puente IVA Terminales'),
        ),
    ]
