# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_missing_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='accountingsettings',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='closingchecklistinstance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='closingchecklistinstance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='closingchecklistinstance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='closingchecklisttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='closingchecklisttemplate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='closingchecklisttemplate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearaccountmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearaccountmapping',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearaccountmapping',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearclosingchecklist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearclosingchecklist',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='fiscalyearclosingchecklist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalfiscalyear',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalfiscalyear',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicaljournalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaljournalentry',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='journalitem',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='accountingsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
