# Generated by Django 5.2.11 on 2026-02-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_accountingsettings_terminal_commission_bridge_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='ppm_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 1.1.04.04 - Pagos Provisionales Mensuales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_ppm', to='accounting.account', verbose_name='Cuenta PPM por Recuperar'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='vat_carryforward_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 1.1.04.02 - Crédito fiscal a favor para próximo período', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vat_carryforward', to='accounting.account', verbose_name='Cuenta IVA Remanente'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='vat_payable_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 2.1.02.02 - IVA resultante a pagar al SII', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vat_payable', to='accounting.account', verbose_name='Cuenta IVA por Pagar'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='withholding_tax_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 1.1.04.03 - Retenciones de honorarios (2da categoría)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_withholding_tax', to='accounting.account', verbose_name='Cuenta Retenciones de Impuestos'),
        ),
    ]
