# Generated by Django 5.2.10 on 2026-02-11 01:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_accountingsettings_ppm_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='correction_income_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar aumentos de remanente por reajuste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_correction_income', to='accounting.account', verbose_name='Cuenta Ingreso por Corrección Monetaria'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Porcentaje de IVA usado en cálculos generales.', max_digits=5, verbose_name='Tasa de IVA por Defecto'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='second_category_tax_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 2.1.02.04 - Impuesto único a los trabajadores por pagar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_second_category_tax', to='accounting.account', verbose_name='Cuenta Impuesto Único 2da Categoría'),
        ),
    ]
