# Generated by Django 5.2.10 on 2026-04-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_accountingsettings_correction_income_account_and_more'),
        ('tax', '0002_accountingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljournalentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.accountingperiod', verbose_name='Periodo Contable'),
        ),
        migrations.AddField(
            model_name='historicaljournalentry',
            name='period_closed',
            field=models.BooleanField(default=False, help_text='Indica si el asiento pertenece a un periodo cerrado', verbose_name='Periodo Cerrado'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='accounting_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='tax.accountingperiod', verbose_name='Periodo Contable'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period_closed',
            field=models.BooleanField(default=False, help_text='Indica si el asiento pertenece a un periodo cerrado', verbose_name='Periodo Cerrado'),
        ),
    ]
