# Generated by Django 5.2.12 on 2026-03-05 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_alter_historicaljournalentry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='ila_tax_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 2.1.02.06 - Impuesto Adicional (Licores, Bebidas, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_ila_tax', to='accounting.account', verbose_name='Cuenta ILA por Pagar'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='loan_retention_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 2.1.02.05 - Retención adicional 3% Préstamo Solidario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_loan_retention', to='accounting.account', verbose_name='Cuenta Retención Préstamo Solidario'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='vat_withholding_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta 2.1.02.07 - IVA retenido a terceros (Factura de Compra)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vat_withholding', to='accounting.account', verbose_name='Cuenta Retención IVA por Pagar'),
        ),
    ]
