# Generated by Django 5.2.12 on 2026-03-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_accountingsettings_ila_tax_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='pos_cash_difference_approval_threshold',
        ),
    ]
