# Generated by Django 5.2.12 on 2026-03-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_remove_pos_cash_difference_approval_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='pos_default_credit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de la venta que se puede asignar como crédito por defecto si el cliente no tiene línea de crédito.', max_digits=5, verbose_name='Porcentaje de Crédito Fallback POS'),
        ),
    ]
