# Generated by Django 5.2.12 on 2026-03-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_accountingsettings_pos_default_credit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='pos_default_credit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de la venta que se puede asignar como crédito por defecto si el cliente no tiene línea de crédito.', max_digits=5, verbose_name='Crédito Preaprobado POS (%)'),
        ),
    ]
