# Generated by Django 5.2.12 on 2026-03-12 19:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_alter_accountingsettings_pos_default_credit_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Ej: 1.1.01.001', max_length=20, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20, verbose_name='Tipo')),
                ('is_reconcilable', models.BooleanField(default=False, verbose_name='Conciliable')),
                ('is_category', models.CharField(blank=True, choices=[('REVENUE', 'Ingresos Operacionales'), ('COST_OF_SALES', 'Costo de Ventas'), ('OPERATING_EXPENSE', 'Gastos Operacionales'), ('NON_OPERATING_REVENUE', 'Ingresos No Operacionales'), ('NON_OPERATING_EXPENSE', 'Gastos No Operacionales'), ('TAX_EXPENSE', 'Impuesto a la Renta')], max_length=30, null=True, verbose_name='Categoría Estado Resultados')),
                ('cf_category', models.CharField(blank=True, choices=[('OPERATING', 'Actividades de Operación'), ('INVESTING', 'Actividades de Inversión'), ('FINANCING', 'Actividades de Financiación'), ('DEP_AMORT', 'Depreciación y Amortización (No Efectivo)')], max_length=30, null=True, verbose_name='Categoría Flujo de Caja')),
                ('bs_category', models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Activo Corriente'), ('NON_CURRENT_ASSET', 'Activo No Corriente'), ('CURRENT_LIABILITY', 'Pasivo Corriente'), ('NON_CURRENT_LIABILITY', 'Pasivo No Corriente'), ('EQUITY', 'Patrimonio')], max_length=30, null=True, verbose_name='Categoría Balance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'historical Cuenta Contable',
                'verbose_name_plural': 'historical Plan de Cuentas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
