# Generated by Django 5.2.12 on 2026-03-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_historicalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='credit_auto_block_days',
            field=models.IntegerField(blank=True, default=60, help_text='Días máximos de mora antes de bloquear automáticamente la capacidad de crédito. Dejar en blanco para desactivar el auto-bloqueo.', null=True, verbose_name='Días de Mora para Auto-Bloqueo'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='credit_risk_classification_enabled',
            field=models.BooleanField(default=True, help_text='Si se activa, el sistema evaluará periódicamente el nivel de riesgo crediticio de los clientes.', verbose_name='Habilitar Clasificación de Riesgo'),
        ),
    ]
