# Generated by Django 5.2.12 on 2026-03-14 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_accountingsettings_credit_auto_block_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_uncollectible_expense_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de gasto para castigar deudas incobrables.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_uncollectible', to='accounting.account', verbose_name='Cuenta de Gasto por Incobrabilidad'),
        ),
    ]
