# Generated by Django 5.2.12 on 2026-03-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_accountingsettings_default_uncollectible_expense_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='credit_risk_classification_enabled',
        ),
    ]
