# Generated by Django 5.2.12 on 2026-03-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_remove_accountingsettings_credit_risk_classification_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljournalentry',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('POSTED', 'Publicado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
