# Generated by Django 5.2.12 on 2026-03-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_remove_historicaljournalentry_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='allowed_dte_types_emit',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de documentos electrónicos seleccionables en el flujo de venta y POS.', verbose_name='DTEs Permitidos a Emitir (Ventas/POS)'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='allowed_dte_types_receive',
            field=models.JSONField(blank=True, default=list, help_text='Tipos de documentos electrónicos seleccionables en el flujo de compras.', verbose_name='DTEs Permitidos a Recibir (Compras)'),
        ),
    ]
