# Generated by Django 5.2.12 on 2026-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0054_accountingsettings_allowed_dte_types_emit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='code_format',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='code_separator',
            field=models.CharField(default='.', help_text='Símbolo usado para separar niveles.', max_length=1, verbose_name='Separador'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='hierarchy_levels',
            field=models.PositiveSmallIntegerField(default=4, help_text='Cantidad total de niveles (2-5).', verbose_name='Niveles de Jerarquía'),
        ),
    ]
