# Generated by Django 5.2.12 on 2026-03-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0055_remove_accountingsettings_code_format_and_more'),
        ('contacts', '0008_contact_credit_auto_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_capital_contribution_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre de patrimonio para aportes de capital de socios (ej: 3.1.02).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_contribution', to='accounting.account', verbose_name='Cuenta Aportes de Capital'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_current_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre de patrimonio para cuenta corriente de socios (ej: 3.1.04).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_current', to='accounting.account', verbose_name='Cuenta Particular de Socios'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_withdrawal_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre de patrimonio para retiros de socios (ej: 3.1.03).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_withdrawal', to='accounting.account', verbose_name='Cuenta Retiros de Socios'),
        ),
        migrations.RenameField(
            model_name='journalitem',
            old_name='partner',
            new_name='partner_name',
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Campo legacy para preservar datos históricos de texto.', max_length=255, null=True, verbose_name='Nombre Socio (Legacy)'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Contacto asociado a este apunte contable (socio, cliente o proveedor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_items', to='contacts.contact', verbose_name='Socio/Contacto'),
        ),
    ]
