# Generated by Django 5.2.12 on 2026-03-27 15:36

from django.db import migrations


def populate_partner(apps, schema_editor):
    JournalItem = apps.get_model('accounting', 'JournalItem')
    Contact = apps.get_model('contacts', 'Contact')
    
    # Cache contacts to avoid excessive queries
    contact_map = {c.name.strip(): c for c in Contact.objects.all() if c.name}
    
    items_to_update = []
    for item in JournalItem.objects.exclude(partner_name__isnull=True).exclude(partner_name=''):
        contact = contact_map.get(item.partner_name.strip())
        if contact:
            item.partner = contact
            items_to_update.append(item)
            
    if items_to_update:
        JournalItem.objects.bulk_update(items_to_update, ['partner'])

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_accountingsettings_partner_capital_contribution_account_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_partner, reverse_populate),
    ]
