# Generated by Django 5.2.12 on 2026-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_populate_partner_from_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Campo legacy para preservar datos históricos de texto.', max_length=255, verbose_name='Nombre Socio (Legacy)'),
        ),
    ]
