# Generated by Django 5.2.12 on 2026-03-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_alter_journalitem_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_capital_social_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta global de patrimonio para el capital social de la empresa (ej: 3.1.01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_capital_social', to='accounting.account', verbose_name='Cuenta de Capital Social'),
        ),
    ]
