# Generated by Django 5.2.12 on 2026-03-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_accountingsettings_partner_capital_social_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='initial_inventory_account',
        ),
    ]
