# Generated by Django 5.2.12 on 2026-03-31 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_remove_initial_inventory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_current_year_earnings_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de patrimonio para las utilidades del ejercicio vigente (ej: 3.2.02).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_current_earnings', to='accounting.account', verbose_name='Cuenta Utilidades del Ejercicio'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_dividends_payable_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de pasivo corriente para dividendos declarados pendientes de pago (ej: 2.1.07).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_dividends', to='accounting.account', verbose_name='Cuenta Dividendos por Pagar'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_provisional_withdrawal_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta padre de patrimonio (contra) para retiros provisorios de socios (ej: 3.1.05).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_prov_withdrawal', to='accounting.account', verbose_name='Cuenta Retiros Provisorios'),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_retained_earnings_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de patrimonio para utilidades retenidas (ej: 3.2.01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_retained', to='accounting.account', verbose_name='Cuenta Utilidades Retenidas'),
        ),
    ]
