# Generated by Django 5.2.12 on 2026-03-31 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_accountingsettings_partner_current_year_earnings_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingsettings',
            name='partner_current_account',
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='partner_capital_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de activo donde se registran las deudas de los socios por capital suscrito no pagado (ej: 1.1.04).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_partner_receivable', to='accounting.account', verbose_name='Cuenta por Cobrar Aportes Socios'),
        ),
    ]
