# Generated by Django 5.2.12 on 2026-03-11 16:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='fonasa_percentage',
        ),
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='sc_empleador_indefinido',
        ),
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='sc_empleador_plazo_fijo',
        ),
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='sc_trabajador_indefinido',
        ),
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='sis_percentage',
        ),
        migrations.AddField(
            model_name='payrollconcept',
            name='formula',
            field=models.TextField(blank=True, help_text='Ej: IMPONIBLE * 0.07 o BASE + 50000', verbose_name='Fórmula / Expresión'),
        ),
        migrations.AlterField(
            model_name='payrollconcept',
            name='formula_type',
            field=models.CharField(choices=[('FIXED', 'Monto Fijo (Manual)'), ('PERCENTAGE', 'Porcentaje de Base Imponible'), ('EMPLOYEE_SPECIFIC', 'Monto por Ficha Empleado'), ('FORMULA', 'Fórmula Matemática'), ('CHILEAN_LAW', 'Legislación Chilena (Cálculo Automático Legacy)')], default='FIXED', max_length=20, verbose_name='Tipo de Cálculo'),
        ),
        migrations.CreateModel(
            name='EmployeeConceptAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mensual')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_amounts', to='hr.payrollconcept')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_amounts', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Monto por Ficha',
                'verbose_name_plural': 'Montos por Ficha',
                'unique_together': {('employee', 'concept')},
            },
        ),
    ]
