# Generated by Django 5.2.12 on 2026-03-11 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_alter_accountingsettings_pos_default_credit_percentage'),
        ('hr', '0002_remove_globalhrsettings_fonasa_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhrsettings',
            name='account_anticipos',
            field=models.ForeignKey(blank=True, help_text='Cuenta de activo para registrar adelantos a trabajadores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_global_anticipos', to='accounting.account', verbose_name='Cuenta Anticipos de Remuneraciones'),
        ),
        migrations.AlterField(
            model_name='payrollconcept',
            name='category',
            field=models.CharField(choices=[('HABER_IMPONIBLE', 'Haber Imponible'), ('HABER_NO_IMPONIBLE', 'Haber No Imponible'), ('DESCUENTO_LEGAL_TRABAJADOR', 'Descuento Legal (Cargo Trabajador)'), ('DESCUENTO_LEGAL_EMPLEADOR', 'Descuento Legal (Cargo Empleador)'), ('OTRO_DESCUENTO', 'Otro Descuento')], max_length=30, verbose_name='Categoría'),
        ),
    ]
