# Generated by Django 5.2.12 on 2026-03-11 18:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_globalhrsettings_account_anticipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhrsettings',
            name='min_wage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Valor del sueldo mínimo legal para el período.', max_digits=10, verbose_name='Sueldo Mínimo Actual'),
        ),
    ]
