# Generated by Django 5.2.12 on 2026-03-11 19:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_globalhrsettings_min_wage_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeconceptamount',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mensual'),
        ),
        migrations.AlterField(
            model_name='payrollconcept',
            name='default_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Monto por defecto'),
        ),
    ]
