# Generated by Django 6.0.5 on 2026-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_hr_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhrsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
