# Generated by Django 5.2.12 on 2026-03-11 23:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employeeconceptamount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='asignacion_familiar',
            field=models.CharField(choices=[('A', 'Tramo A'), ('B', 'Tramo B'), ('C', 'Tramo C'), ('D', 'Sin derecho (Tramo D)')], default='D', max_length=2, verbose_name='Asignación Familiar'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cargas_familiares',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Cargas'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dias_pactados',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Días Pactados'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gratificacion',
            field=models.BooleanField(default=True, verbose_name='Gratificación Legal'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jornada_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('44.0'), max_digits=5, verbose_name='Horas de Jornada'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jornada_type',
            field=models.CharField(choices=[('ORDINARIA_22', 'Ordinaria Art. 22'), ('PARCIAL_40BIS', 'Parcial Art 40 BIS'), ('EXENTA_22', 'Exenta Art. 22'), ('EXTRAORDINARIA_30', 'Extraordinaria Art. 30')], default='ORDINARIA_22', max_length=20, verbose_name='Tipo de Jornada'),
        ),
        migrations.AddField(
            model_name='employee',
            name='trabajo_agricola',
            field=models.BooleanField(default=False, verbose_name='Trabajo Agrícola'),
        ),
        migrations.AddField(
            model_name='employee',
            name='trabajo_pesado',
            field=models.BooleanField(default=False, verbose_name='Trabajo Pesado'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='asignacion_familiar',
            field=models.CharField(choices=[('A', 'Tramo A'), ('B', 'Tramo B'), ('C', 'Tramo C'), ('D', 'Sin derecho (Tramo D)')], default='D', max_length=2, verbose_name='Asignación Familiar'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='cargas_familiares',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Cargas'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='dias_pactados',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Días Pactados'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='gratificacion',
            field=models.BooleanField(default=True, verbose_name='Gratificación Legal'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='jornada_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('44.0'), max_digits=5, verbose_name='Horas de Jornada'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='jornada_type',
            field=models.CharField(choices=[('ORDINARIA_22', 'Ordinaria Art. 22'), ('PARCIAL_40BIS', 'Parcial Art 40 BIS'), ('EXENTA_22', 'Exenta Art. 22'), ('EXTRAORDINARIA_30', 'Extraordinaria Art. 30')], default='ORDINARIA_22', max_length=20, verbose_name='Tipo de Jornada'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='trabajo_agricola',
            field=models.BooleanField(default=False, verbose_name='Trabajo Agrícola'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='trabajo_pesado',
            field=models.BooleanField(default=False, verbose_name='Trabajo Pesado'),
        ),
        migrations.AddField(
            model_name='historicalpayroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Días Inasistencia'),
        ),
        migrations.AddField(
            model_name='historicalpayroll',
            name='agreed_days',
            field=models.IntegerField(default=30, verbose_name='Días Pactados'),
        ),
        migrations.AddField(
            model_name='historicalpayroll',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='Días Trabajados'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Días Inasistencia'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='agreed_days',
            field=models.IntegerField(default=30, verbose_name='Días Pactados'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name='Días Trabajados'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('AUSENTISMO', 'Ausentismo'), ('LICENCIA', 'Licencia Médica'), ('PERMISO_SIN_GOCE', 'Permiso sin goce de sueldo'), ('AUSENCIA_HORAS', 'Ausencia de horas')], max_length=20, verbose_name='Tipo de Inasistencia')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('days', models.DecimalField(decimal_places=2, help_text='Cantidad de días o fracción (ej: 0.5 para medio día).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Días de Ausencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='hr.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Inasistencia',
                'verbose_name_plural': 'Inasistencias',
                'ordering': ['-start_date'],
            },
        ),
    ]
