# Generated by Django 5.2.12 on 2026-03-12 01:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_alter_accountingsettings_pos_default_credit_percentage'),
        ('hr', '0006_employee_asignacion_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollconcept',
            name='category',
            field=models.CharField(choices=[('HABER_IMPONIBLE', 'Haber Imponible'), ('HABER_NO_IMPONIBLE', 'Haber No Imponible'), ('DESCUENTO_LEGAL_TRABAJADOR', 'Descuento Legal (Cargo Trabajador)'), ('DESCUENTO_LEGAL_EMPLEADOR', 'Aporte del Empleador'), ('OTRO_DESCUENTO', 'Otro Descuento')], max_length=30, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('SALARIO', 'Pago de Remuneración'), ('PREVIRED', 'Pago de Previred')], default='SALARIO', max_length=10, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Pagado')),
                ('date', models.DateField(verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.payroll', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Pago de Remuneración',
                'verbose_name_plural': 'Pagos de Remuneración',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha del Anticipo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_discounted', models.BooleanField(default=False, verbose_name='Descontado en Liquidación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='hr.employee', verbose_name='Empleado')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('payroll', models.ForeignKey(blank=True, help_text='Si ya fue descontado de una liquidación, se vincula aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='hr.payroll', verbose_name='Liquidación Asociada')),
            ],
            options={
                'verbose_name': 'Anticipo de Sueldo',
                'verbose_name_plural': 'Anticipos de Sueldo',
                'ordering': ['-date'],
            },
        ),
    ]
