# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_missing_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='afp',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employeeconceptamount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeeconceptamount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employeeconceptamount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='globalhrsettings',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalpayroll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalpayroll',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payrollconcept',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payrollconcept',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payrollconcept',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payrollpayment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='salaryadvance',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='globalhrsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='globalhrsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
