# Generated by Django 5.2.9 on 2026-01-05 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0012_accountingsettings_default_advance_payment_account_and_more'),
        ('billing', '0004_alter_invoice_date'),
        ('contacts', '0001_initial'),
        ('treasury', '0006_remove_payment_customer_remove_payment_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Ej: ARR, SB, SEG', max_length=20, unique=True, verbose_name='Código')),
                ('requires_provision', models.BooleanField(default=False, verbose_name='Requiere Provisión Mensual')),
                ('is_tax_deductible', models.BooleanField(default=True, verbose_name='Es Deducible de Impuestos')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_categories_expense', to='accounting.account', verbose_name='Cuenta de Gasto por Defecto')),
                ('payable_account', models.ForeignKey(limit_choices_to={'account_type': 'LIABILITY'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_categories_payable', to='accounting.account', verbose_name='Cuenta por Pagar por Defecto')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Contrato')),
                ('name', models.CharField(help_text='Ej: Arriendo Oficina Central', max_length=200, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('recurrence_type', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual'), ('BIWEEKLY', 'Quincenal'), ('WEEKLY', 'Semanal'), ('ONE_TIME', 'Único (No Recurrente)')], default='MONTHLY', max_length=20, verbose_name='Frecuencia')),
                ('payment_day', models.PositiveSmallIntegerField(default=1, help_text='Día del mes (1-31)', verbose_name='Día de Pago')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Base')),
                ('is_amount_variable', models.BooleanField(default=False, help_text='Si se marca, el monto base es solo referencial', verbose_name='Monto Variable')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Término')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovación Automática')),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, verbose_name='Días Aviso Renovación')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('EXPIRED', 'Vencido'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Archivo Contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='services.servicecategory', verbose_name='Categoría')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_expenses', to='accounting.account', verbose_name='Cuenta de Gasto')),
                ('payable_account', models.ForeignKey(limit_choices_to={'account_type': 'LIABILITY'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_payables', to='accounting.account', verbose_name='Cuenta por Pagar')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='contacts.contact', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contrato de Servicio',
                'verbose_name_plural': 'Contratos de Servicio',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Fecha Vencimiento')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Inicio Período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Fin Período')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Pagado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('invoiced_date', models.DateField(blank=True, null=True, verbose_name='Fecha Facturación')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='services.servicecontract')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_obligations', to='billing.invoice', verbose_name='Factura Recibida')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_obligations', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_obligations', to='treasury.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Obligación de Servicio',
                'verbose_name_plural': 'Obligaciones de Servicio',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['due_date', 'status'], name='services_se_due_dat_61a16c_idx'), models.Index(fields=['contract', 'status'], name='services_se_contrac_ae4f5b_idx')],
            },
        ),
    ]
