# Generated by Django 5.2.9 on 2026-01-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_tax_deductible',
        ),
    ]
