# Generated by Django 5.2.9 on 2026-01-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_accountingsettings_default_advance_payment_account_and_more'),
        ('services', '0002_remove_servicecategory_is_tax_deductible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='expense_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_expenses', to='accounting.account', verbose_name='Cuenta de Gasto'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='payable_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'LIABILITY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_payables', to='accounting.account', verbose_name='Cuenta por Pagar'),
        ),
    ]
