export {
  getGlobalHRSettings,
  updateGlobalHRSettings,
  getAFPs,
  getEmployees,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getPayrolls,
  getPayrollDetail,
  createPayroll,
  deletePayroll,
  getAbsences,
  createAbsence,
  updateAbsence,
  deleteAbsence,
  getSalaryAdvances,
  createSalaryAdvance,
  updateSalaryAdvance,
  deleteSalaryAdvance,
  getPayrollConcepts,
  getPayrollPayments,
} from './hrApi'
