export {
  getGlobalHRSettings,
  updateGlobalHRSettings,
  getAFPs,
  getEmployees,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getPayrolls,
  createPayroll,
  deletePayroll,
  getAbsences,
  createAbsence,
  updateAbsence,
  deleteAbsence,
  getAdvances,
  createAdvance,
  updateAdvance,
  deleteAdvance,
  getPayrollConcepts,
  getPayrollPayments,
} from './hrApi'
