# Generated by Django 5.2.9 on 2025-12-31 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Almacén/Bodega',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('asset_account', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_assets', to='accounting.account')),
                ('expense_account', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_expenses', to='accounting.account')),
                ('income_account', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_incomes', to='accounting.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código/SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('product_type', models.CharField(choices=[('STORABLE', 'Almacenable'), ('CONSUMABLE', 'Consumible'), ('SERVICE', 'Servicio')], default='STORABLE', max_length=20, verbose_name='Tipo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Venta')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('move_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='accounting.journalentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Kardex',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
