# Generated by Django 5.2.9 on 2026-01-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Costo Ponderado'),
        ),
    ]
