# Generated by Django 5.2.13 on 2026-04-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='mfg_default_delivery_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfg_default_delivery_days',
        ),
    ]
