# Generated by Django 5.2.9 on 2026-01-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_manufacturable_type'),
        ('inventory', '0002_alter_product_cost_price'),
    ]

    operations = [
    ]
