# Generated by Django 5.2.14 on 2026-05-08 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_timestampedmodel_t14'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductattribute',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 887677, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproductattributevalue',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 887890, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproductattributevalue',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 888000, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproductcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 888097, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproductcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 888212, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluom',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 7, 888308, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluom',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 36, 283991, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluomcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 36, 284694, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluomcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 36, 284873, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Actualizado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproductattribute',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
    ]
