# Generated by Django 5.2.9 on 2026-01-07 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productattribute_product_variant_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('uom_type', models.CharField(choices=[('REFERENCE', 'Referencia para esta categoría'), ('BIGGER', 'Más grande que la referencia'), ('SMALLER', 'Más pequeño que la referencia')], default='REFERENCE', max_length=20, verbose_name='Tipo')),
                ('ratio', models.DecimalField(decimal_places=5, default=1.0, max_digits=12, verbose_name='Ratio')),
                ('rounding', models.DecimalField(decimal_places=5, default=0.01, max_digits=12, verbose_name='Redondeo')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='UoMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Medida',
                'verbose_name_plural': 'Categorías de Medida',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, help_text='Unidad por defecto para compras', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='inventory.uom', verbose_name='UdM Compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unidad base para gestión de stock', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.uom', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='uom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='inventory.uomcategory'),
        ),
    ]
