# Generated by Django 5.2.14 on 2026-05-08 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalproductattribute_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_auto_finalize', models.BooleanField(default=False, help_text='Si se activa, la OT se marcará como Terminada automáticamente al generarse (Flujo Express)', verbose_name='Finalizar Automáticamente')),
                ('mfg_enable_prepress', models.BooleanField(default=False, verbose_name='Habilitar Pre-Impresión')),
                ('mfg_enable_press', models.BooleanField(default=False, verbose_name='Habilitar Impresión')),
                ('mfg_enable_postpress', models.BooleanField(default=False, verbose_name='Habilitar Post-Impresión')),
                ('mfg_prepress_design', models.BooleanField(default=False, verbose_name='Pre-Impresión: Diseño Requerido')),
                ('mfg_prepress_specs', models.BooleanField(default=False, verbose_name='Pre-Impresión: Especificaciones')),
                ('mfg_prepress_folio', models.BooleanField(default=False, verbose_name='Pre-Impresión: Folio')),
                ('mfg_press_offset', models.BooleanField(default=False, verbose_name='Impresión: Offset')),
                ('mfg_press_digital', models.BooleanField(default=False, verbose_name='Impresión: Digital')),
                ('mfg_press_special', models.BooleanField(default=False, verbose_name='Impresión: Especial')),
                ('mfg_postpress_finishing', models.BooleanField(default=False, verbose_name='Post-Impresión: Acabados')),
                ('mfg_postpress_binding', models.BooleanField(default=False, verbose_name='Post-Impresión: Encuadernación/Troquelado')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_profile', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Perfil de Fabricación',
                'verbose_name_plural': 'Perfiles de Fabricación',
            },
        ),
    ]
