# Generated by Django 5.2.9 on 2026-01-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_uom_uomcategory_product_purchase_uom_product_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Nombre del icono de Lucide (ej: Package, Coffee)', max_length=50, null=True, verbose_name='Icono'),
        ),
    ]
