# Generated by Django 5.2.14 on 2026-05-08 02:11

from django.db import migrations

MFG_FIELDS = [
    'mfg_auto_finalize',
    'mfg_enable_prepress', 'mfg_enable_press', 'mfg_enable_postpress',
    'mfg_prepress_design', 'mfg_prepress_specs', 'mfg_prepress_folio',
    'mfg_press_offset', 'mfg_press_digital', 'mfg_press_special',
    'mfg_postpress_finishing', 'mfg_postpress_binding',
]


def forwards(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    ProductManufacturingProfile = apps.get_model('inventory', 'ProductManufacturingProfile')

    to_create = []
    for product in Product.objects.filter(product_type='MANUFACTURABLE').iterator():
        # Only create if not already exists
        if not ProductManufacturingProfile.objects.filter(product=product).exists():
            profile = ProductManufacturingProfile(product=product)
            for field in MFG_FIELDS:
                setattr(profile, field, getattr(product, field, False))
            to_create.append(profile)

    if to_create:
        ProductManufacturingProfile.objects.bulk_create(to_create, ignore_conflicts=True)


def backwards(apps, schema_editor):
    ProductManufacturingProfile = apps.get_model('inventory', 'ProductManufacturingProfile')
    ProductManufacturingProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_t44_product_manufacturing_profile'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
