# Generated by Django 5.2.9 on 2026-01-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_image_productcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Regla')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Cantidad Mínima')),
                ('rule_type', models.CharField(choices=[('FIXED', 'Precio Fijo'), ('DISCOUNT_PERCENTAGE', 'Porcentaje de Descuento')], default='FIXED', max_length=20, verbose_name='Tipo de Regla')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Fijo')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Descuento %')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad más alta se aplica primero', verbose_name='Prioridad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='inventory.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Regla de Precio',
                'verbose_name_plural': 'Reglas de Precio',
                'ordering': ['-priority', 'min_quantity'],
            },
        ),
    ]
