# Generated by Django 5.2.10 on 2026-01-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_pricingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_of',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
