# Generated by Django 5.2.10 on 2026-01-07 16:55

from django.db import migrations, models


def migrate_manufacturable_types(apps, schema_editor):
    """Migrate existing MANUFACTURABLE products to MANUFACTURABLE_STANDARD"""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(product_type='MANUFACTURABLE').update(
        product_type='MANUFACTURABLE_STANDARD'
    )


def set_track_inventory_defaults(apps, schema_editor):
    """Set track_inventory defaults based on product type"""
    Product = apps.get_model('inventory', 'Product')
    
    # Disable inventory tracking for manufacturable types (no final product stock)
    Product.objects.filter(
        product_type__in=['MANUFACTURABLE_STANDARD', 'MANUFACTURABLE_CUSTOM']
    ).update(track_inventory=False)
    
    # Disable for services
    Product.objects.filter(product_type='SERVICE').update(track_inventory=False)
    
    # Enable for storables and consumables (default is already True)


def reverse_migrate_types(apps, schema_editor):
    """Reverse migration: Convert back to MANUFACTURABLE"""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(
        product_type__in=['MANUFACTURABLE_STANDARD', 'MANUFACTURABLE_CUSTOM']
    ).update(product_type='MANUFACTURABLE')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_productattributevalue_attribute_and_more'),
    ]

    operations = [
        # First, alter field to accept new choices
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumible'), ('STORABLE', 'Almacenable'), ('MANUFACTURABLE', 'Fabricable'), ('MANUFACTURABLE_STANDARD', 'Fabricable Estándar'), ('MANUFACTURABLE_CUSTOM', 'Fabricable Customizado'), ('SERVICE', 'Servicio')], default='STORABLE', max_length=30, verbose_name='Tipo'),
        ),
        # Add new fields
        migrations.AddField(
            model_name='product',
            name='custom_fields_schema',
            field=models.JSONField(blank=True, help_text='Define campos adicionales requeridos al vender (ej: tamaño, copias, folio inicial)', null=True, verbose_name='Esquema de Campos Customizados'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Desactivar para productos que no requieren control de inventario (fabricables, servicios)', verbose_name='Controlar Stock'),
        ),
        # Migrate existing data
        migrations.RunPython(migrate_manufacturable_types, reverse_migrate_types),
        migrations.RunPython(set_track_inventory_defaults, migrations.RunPython.noop),
        # Finally, update field to only allow new choices
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumible'), ('STORABLE', 'Almacenable'), ('MANUFACTURABLE_STANDARD', 'Fabricable Estándar'), ('MANUFACTURABLE_CUSTOM', 'Fabricable Customizado'), ('SERVICE', 'Servicio')], default='STORABLE', max_length=30, verbose_name='Tipo'),
        ),
    ]
