# Generated by Django 6.0.5 on 2026-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_product_uom_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productuomprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
