# Generated by Django 5.2.9 on 2026-01-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_refine_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Solo usado para el operador 'Entre'", max_digits=12, null=True, verbose_name='Cantidad Máxima / Hasta'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='operator',
            field=models.CharField(choices=[('GT', 'Mayor que (>)'), ('LT', 'Menor que (<)'), ('EQ', 'Igual a (=)'), ('GE', 'Mayor o Igual (>=)'), ('LE', 'Menor o Igual (<=)'), ('BT', 'Entre (Rango)')], default='GE', max_length=5, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.uom', verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='min_quantity',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, verbose_name='Cantidad Mínima / Desde'),
        ),
    ]
