# Generated by Django 5.2.10 on 2026-01-07 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_pricingrule_max_quantity_pricingrule_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_uom',
            field=models.ForeignKey(blank=True, help_text='Unidad por defecto para ventas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_sale', to='inventory.uom', verbose_name='UdM Venta'),
        ),
    ]
