# Generated by Django 5.2.9 on 2026-01-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_sale_uom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Campo')),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto'), ('SELECT_SINGLE', 'Selección Única'), ('SELECT_MULTIPLE', 'Selección Múltiple')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción/Ayuda')),
                ('options', models.JSONField(blank=True, help_text="Lista de opciones para campos de selección (ej: ['Opción 1', 'Opción 2'])", null=True, verbose_name='Opciones')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Campo Personalizado',
                'verbose_name_plural': 'Plantillas de Campos Personalizados',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_bom',
            field=models.BooleanField(default=False, help_text='Indica si este producto tiene componentes definidos que se asignarán a órdenes de trabajo', verbose_name='Tiene Lista de Materiales'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_advanced_manufacturing',
            field=models.BooleanField(default=False, help_text='Habilita campos personalizados al vender este producto desde POS o notas de venta', verbose_name='Requiere Fabricación Avanzada'),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom', to='inventory.product', verbose_name='Componente/Material')),
                ('product', models.ForeignKey(limit_choices_to={'product_type__in': ['MANUFACTURABLE_STANDARD', 'MANUFACTURABLE_CUSTOM']}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.product', verbose_name='Producto Fabricable')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.uom', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Línea de Lista de Materiales',
                'verbose_name_plural': 'Listas de Materiales',
                'ordering': ['product', 'component'],
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_fields', to='inventory.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_associations', to='inventory.customfieldtemplate')),
            ],
            options={
                'verbose_name': 'Campo Personalizado del Producto',
                'verbose_name_plural': 'Campos Personalizados del Producto',
                'ordering': ['order', 'template__name'],
                'unique_together': {('product', 'template')},
            },
        ),
    ]
