# Generated by Django 5.2.9 on 2026-01-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_customfieldtemplate_product_has_bom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='prefix',
            field=models.CharField(blank=True, help_text='Usado para generar el código interno (ej: IMP, DIS)', max_length=10, null=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código/SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumible'), ('STORABLE', 'Almacenable'), ('MANUFACTURABLE', 'Fabricable'), ('SERVICE', 'Servicio')], default='STORABLE', max_length=30, verbose_name='Tipo'),
        ),
    ]
