# Generated by Django 5.2.15 on 2026-06-19 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_remove_historicalproduct_expense_account_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productcustomfield",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productcustomfield",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productcustomfield",
            name="template",
        ),
        migrations.DeleteModel(
            name="CustomFieldTemplate",
        ),
        migrations.DeleteModel(
            name="ProductCustomField",
        ),
    ]
