# Generated by Django 5.2.10 on 2026-01-08 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_internal_code_productcategory_prefix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfMaterials',
        ),
    ]
