# Generated by Django 6.0.5 on 2026-07-08 21:02

from django.db import migrations
from django.db.models import Sum
from decimal import Decimal

def populate_stock(apps, schema_editor):
    StockMove = apps.get_model('inventory', 'StockMove')
    Stock = apps.get_model('inventory', 'Stock')
    
    # Get distinct product/warehouse combinations
    combinations = StockMove.objects.values('product', 'warehouse').distinct()
    
    for combo in combinations:
        product_id = combo['product']
        warehouse_id = combo['warehouse']
        
        in_qty = StockMove.objects.filter(
            product_id=product_id, 
            warehouse_id=warehouse_id, 
            move_type='IN'
        ).aggregate(total=Sum('quantity'))['total'] or Decimal('0')
        
        out_qty = StockMove.objects.filter(
            product_id=product_id, 
            warehouse_id=warehouse_id, 
            move_type='OUT'
        ).aggregate(total=Sum('quantity'))['total'] or Decimal('0')
        
        adj_qty = StockMove.objects.filter(
            product_id=product_id, 
            warehouse_id=warehouse_id, 
            move_type='ADJ'
        ).aggregate(total=Sum('quantity'))['total'] or Decimal('0')
        
        total_qty = in_qty - out_qty + adj_qty
        
        Stock.objects.update_or_create(
            product_id=product_id,
            warehouse_id=warehouse_id,
            defaults={'quantity': total_qty}
        )

def reverse_populate(apps, schema_editor):
    Stock = apps.get_model('inventory', 'Stock')
    Stock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stock'),
    ]

    operations = [
        migrations.RunPython(populate_stock, reverse_populate),
    ]

