# Generated by Django 5.2.10 on 2026-01-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_billofmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_sale_uoms',
            field=models.ManyToManyField(blank=True, help_text='Unidades de medida explícitas permitidas para la venta de este producto.', related_name='allowed_sale_products', to='inventory.uom', verbose_name='Unidades de Venta Permitidas'),
        ),
    ]
