# Generated by Django 6.0.5 on 2026-07-08 21:08

import core.utils
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_remove_contact_account_payable_and_more'),
        ('inventory', '0015_populate_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Recepción'), ('DELIVERY', 'Entrega'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste'), ('PRODUCTION', 'Producción')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('date', models.DateField(default=core.utils.get_current_date, verbose_name='Fecha')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('confirmed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'historical Documento de Inventario',
                'verbose_name_plural': 'historical Documentos de Inventario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Recepción'), ('DELIVERY', 'Entrega'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste'), ('PRODUCTION', 'Producción')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('date', models.DateField(default=core.utils.get_current_date, verbose_name='Fecha')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_inventory_docs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_docs', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_documents', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Documento de Inventario',
                'verbose_name_plural': 'Documentos de Inventario',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Unitario')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.inventorydocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_details', to='inventory.product')),
                ('source_warehouse', models.ForeignKey(blank=True, help_text='Solo aplicable para transferencias. Bodega de origen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_source_details', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_details', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Detalle de Documento',
                'verbose_name_plural': 'Detalles de Documento',
            },
        ),
    ]
