# Generated by Django 5.2.10 on 2026-01-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_allowed_sale_uoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfg_default_delivery_days',
            field=models.IntegerField(default=3, help_text='Días a sumar a la fecha actual para la fecha estimada de entrega', verbose_name='Días de Entrega por Defecto'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_show_contacts',
            field=models.BooleanField(default=True, help_text='Indica si se debe permitir asociar contactos en el modal de venta', verbose_name="Mostrar 'Contactos Asociados'"),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_show_design_needed',
            field=models.BooleanField(default=True, help_text='Indica si se debe preguntar por diseño en el modal de venta', verbose_name="Mostrar 'Necesidad de Diseño'"),
        ),
    ]
