# Generated by Django 5.2.10 on 2026-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_mfg_default_delivery_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mfg_show_contacts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfg_show_design_needed',
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_enable_postpress',
            field=models.BooleanField(default=False, help_text='Activa la etapa de post-impresión en el flujo de fabricación', verbose_name='Habilitar Post-Impresión'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_enable_prepress',
            field=models.BooleanField(default=False, help_text='Activa la etapa de pre-impresión en el flujo de fabricación', verbose_name='Habilitar Pre-Impresión'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_enable_press',
            field=models.BooleanField(default=False, help_text='Activa la etapa de impresión en el flujo de fabricación', verbose_name='Habilitar Impresión'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_postpress_binding',
            field=models.BooleanField(default=False, help_text='Solicitar información de encuadernación o troquelado', verbose_name='Post-Impresión: Encuadernación/Troquelado'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_postpress_finishing',
            field=models.BooleanField(default=False, help_text='Solicitar información de acabados', verbose_name='Post-Impresión: Acabados'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_prepress_design',
            field=models.BooleanField(default=False, help_text='Solicitar diseño en la etapa de pre-impresión', verbose_name='Pre-Impresión: Diseño Requerido'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_prepress_folio',
            field=models.BooleanField(default=False, help_text='Solicitar folio en la etapa de pre-impresión', verbose_name='Pre-Impresión: Folio'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_prepress_specs',
            field=models.BooleanField(default=False, help_text='Solicitar especificaciones en la etapa de pre-impresión', verbose_name='Pre-Impresión: Especificaciones'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_press_digital',
            field=models.BooleanField(default=False, help_text='Solicitar información de impresión digital', verbose_name='Impresión: Digital'),
        ),
        migrations.AddField(
            model_name='product',
            name='mfg_press_offset',
            field=models.BooleanField(default=False, help_text='Solicitar información de impresión offset', verbose_name='Impresión: Offset'),
        ),
    ]
