# Generated by Django 5.2.15 on 2026-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_historicalinventorydocument_inventorydocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorydocument',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Recepción'), ('DELIVERY', 'Entrega'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste'), ('PRODUCTION', 'Producción'), ('PARTNER_CONTRIBUTION', 'Aporte de Socio'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalstockmove',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario')], max_length=20, null=True, verbose_name='Motivo de Ajuste'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='document_type',
            field=models.CharField(choices=[('RECEIPT', 'Recepción'), ('DELIVERY', 'Entrega'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste'), ('PRODUCTION', 'Producción'), ('PARTNER_CONTRIBUTION', 'Aporte de Socio'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario')], max_length=20, null=True, verbose_name='Motivo de Ajuste'),
        ),
    ]
