# Generated by Django 5.2.15 on 2026-07-10 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_remove_contact_account_payable_and_more'),
        ('inventory', '0017_alter_historicalinventorydocument_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('location_type', models.CharField(choices=[('VENDOR', 'Proveedor'), ('CUSTOMER', 'Cliente'), ('INTERNAL', 'Interna (Bodega)'), ('VIRTUAL', 'Virtual (Ajustes, Socios, Producción)')], max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='contacts.contact')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='historicalstockmove',
            name='destination_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='historicalstockmove',
            name='source_location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorydocumentdetail',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_moves_in', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorydocumentdetail',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_moves_out', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='inventory.location'),
        ),
    ]
