# Generated by Django 5.2.15 on 2026-07-10 01:29

from django.db import migrations


def create_seed_locations(apps, schema_editor):
    Location = apps.get_model("inventory", "Location")
    Warehouse = apps.get_model("inventory", "Warehouse")

    # 1. Virtual Locations
    virtuals = [
        {"name": "Proveedores", "location_type": "VENDOR"},
        {"name": "Clientes", "location_type": "CUSTOMER"},
        {"name": "Ajuste por Merma/Pérdida", "location_type": "VIRTUAL"},
        {"name": "Ajuste por Sobrante/Ganancia", "location_type": "VIRTUAL"},
        {"name": "Capital de Socios", "location_type": "VIRTUAL"},
        {"name": "Revalorización", "location_type": "VIRTUAL"},
    ]

    for v in virtuals:
        Location.objects.get_or_create(
            name=v["name"],
            location_type=v["location_type"]
        )

    # 2. Internal Locations for existing Warehouses
    for warehouse in Warehouse.objects.all():
        Location.objects.get_or_create(
            name=f"Bodega Central - {warehouse.name}",
            location_type="INTERNAL",
            warehouse=warehouse
        )


def reverse_seed_locations(apps, schema_editor):
    Location = apps.get_model("inventory", "Location")
    Location.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_location_model_dual_write'),
    ]

    operations = [
        migrations.RunPython(create_seed_locations, reverse_seed_locations)
    ]
