# Generated by Django 5.2.10 on 2026-01-10 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_migrate_uom_to_allowed_sale_uoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allowed_sale_uoms',
            field=models.ManyToManyField(blank=True, help_text='Unidades de medida permitidas para la venta de este producto (además de la unidad base).', related_name='allowed_sale_products', to='inventory.uom', verbose_name='Unidades de Venta Permitidas'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, help_text="⚠️ DEPRECATED: Use 'allowed_sale_uoms' en su lugar. Este campo se mantendrá solo para compatibilidad.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='inventory.uom', verbose_name='UdM Compra (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_uom',
            field=models.ForeignKey(blank=True, help_text="⚠️ DEPRECATED: Use 'allowed_sale_uoms' en su lugar. Este campo se mantendrá solo para compatibilidad.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_sale', to='inventory.uom', verbose_name='UdM Venta (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unidad base para gestión de stock. Todas las conversiones se hacen a esta unidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.uom', verbose_name='Unidad de Medida Base'),
        ),
    ]
