# Generated by Django 5.2.15 on 2026-07-10 01:31

from django.db import migrations


def backfill_locations(apps, schema_editor):
    StockMove = apps.get_model("inventory", "StockMove")
    InventoryDocumentDetail = apps.get_model("inventory", "InventoryDocumentDetail")
    Location = apps.get_model("inventory", "Location")

    # Get virtual locations
    loc_vendor = Location.objects.get(name="Proveedores", location_type="VENDOR")
    loc_customer = Location.objects.get(name="Clientes", location_type="CUSTOMER")
    loc_loss = Location.objects.get(name="Ajuste por Merma/Pérdida", location_type="VIRTUAL")
    loc_gain = Location.objects.get(name="Ajuste por Sobrante/Ganancia", location_type="VIRTUAL")
    loc_capital = Location.objects.get(name="Capital de Socios", location_type="VIRTUAL")
    loc_reval = Location.objects.get(name="Revalorización", location_type="VIRTUAL")

    # Cache internal locations for quick lookup
    internal_locations = {
        loc.warehouse_id: loc 
        for loc in Location.objects.filter(location_type="INTERNAL")
    }

    # Process StockMoves
    for move in StockMove.objects.all():
        internal_loc = internal_locations.get(move.warehouse_id)
        if not internal_loc:
            continue

        src = None
        dst = None

        if move.move_type == "IN":
            dst = internal_loc
            if move.adjustment_reason == "LOSS":
                src = loc_loss
            elif move.adjustment_reason == "GAIN" or move.adjustment_reason == "CORRECTION":
                src = loc_gain
            elif move.adjustment_reason == "REVALUATION":
                src = loc_reval
            elif move.adjustment_reason == "PARTNER_CONTRIBUTION" or move.adjustment_reason == "PARTNER_WITHDRAWAL":
                src = loc_capital
            elif move.adjustment_reason == "INITIAL":
                src = loc_gain
            else:
                # Assuming Receipt / Default IN
                src = loc_vendor
        else: # OUT
            src = internal_loc
            if move.adjustment_reason == "LOSS":
                dst = loc_loss
            elif move.adjustment_reason == "GAIN" or move.adjustment_reason == "CORRECTION":
                dst = loc_gain
            elif move.adjustment_reason == "REVALUATION":
                dst = loc_reval
            elif move.adjustment_reason == "PARTNER_CONTRIBUTION" or move.adjustment_reason == "PARTNER_WITHDRAWAL":
                dst = loc_capital
            else:
                # Assuming Delivery / Default OUT
                dst = loc_customer
        
        move.source_location = src
        move.destination_location = dst
        move.quantity = abs(move.quantity)
        move.save(update_fields=['source_location', 'destination_location', 'quantity'])

    # Process InventoryDocumentDetails
    for detail in InventoryDocumentDetail.objects.all():
        doc_type = detail.document.document_type
        internal_loc = internal_locations.get(detail.warehouse_id)
        if not internal_loc:
            continue

        src = None
        dst = None

        if doc_type == "RECEIPT":
            src = loc_vendor
            dst = internal_loc
        elif doc_type == "DELIVERY":
            src = internal_loc
            dst = loc_customer
        elif doc_type == "TRANSFER":
            src = internal_locations.get(detail.source_warehouse_id)
            dst = internal_loc
        elif doc_type == "PRODUCTION":
            # Just a placeholder if they had it
            src = internal_loc
            dst = loc_customer # Just fallback
        elif doc_type == "PARTNER_CONTRIBUTION":
            src = loc_capital
            dst = internal_loc
        elif doc_type == "PARTNER_WITHDRAWAL":
            src = internal_loc
            dst = loc_capital
        elif doc_type == "ADJUSTMENT":
            # For documents, if qty > 0 it's a gain, if < 0 it's a loss
            if detail.quantity > 0:
                src = loc_gain
                dst = internal_loc
            else:
                src = internal_loc
                dst = loc_loss

        detail.source_location = src
        detail.destination_location = dst
        detail.quantity = abs(detail.quantity)
        detail.save(update_fields=['source_location', 'destination_location', 'quantity'])


def reverse_backfill_locations(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_seed_locations'),
    ]

    operations = [
        migrations.RunPython(backfill_locations, reverse_backfill_locations)
    ]
