# Generated by Django 5.2.10 on 2026-01-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_product_allowed_sale_uoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_be_purchased',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el producto no aparecerá en órdenes de compra.', verbose_name='Puede ser comprado'),
        ),
        migrations.AddField(
            model_name='product',
            name='can_be_sold',
            field=models.BooleanField(default=True, help_text='Si se desactiva, el producto no aparecerá en ventas ni en POS.', verbose_name='Puede ser vendido'),
        ),
    ]
