# Generated by Django 5.2.9 on 2026-01-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
        ('inventory', '0020_product_can_be_purchased_product_can_be_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='accounting.journalentry'),
        ),
    ]
