# Generated by Django 5.2.15 on 2026-07-10 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_backfill_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstockmove',
            name='adjustment_reason',
        ),
        migrations.RemoveField(
            model_name='historicalstockmove',
            name='move_type',
        ),
        migrations.RemoveField(
            model_name='historicalstockmove',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='inventorydocumentdetail',
            name='source_warehouse',
        ),
        migrations.RemoveField(
            model_name='inventorydocumentdetail',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='adjustment_reason',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='move_type',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='inventorydocumentdetail',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_moves_in', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='inventorydocumentdetail',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_moves_out', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_out', to='inventory.location'),
        ),
    ]
