# Generated by Django 5.2.10 on 2026-01-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_stockmove_journal_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad Mínima')),
                ('max_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad Máxima')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reordering_rules', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reordering_rules', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Regla de Reabastecimiento',
                'verbose_name_plural': 'Reglas de Reabastecimiento',
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
