# Generated by Django 5.2.15 on 2026-07-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_seed_closing_checklist_templates'),
        ('inventory', '0021_drop_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable de contrapartida para ubicaciones virtuales.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounting.account'),
        ),
    ]
