# Generated by Django 5.2.15 on 2026-07-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_location_account'),
    ]

def populate_accounts(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    AccountingSettings = apps.get_model('accounting', 'AccountingSettings')

    settings = AccountingSettings.objects.first()
    if not settings:
        return

    # Proveedor (VENDOR)
    if settings.default_payable_account:
        Location.objects.filter(location_type='VENDOR').update(account=settings.default_payable_account)

    # Cliente (CUSTOMER)
    if settings.default_receivable_account:
        Location.objects.filter(location_type='CUSTOMER').update(account=settings.default_receivable_account)

    # Sobrante/Ganancia (VIRTUAL)
    if settings.adjustment_income_account:
        Location.objects.filter(location_type='VIRTUAL', name='Ajuste por Sobrante/Ganancia').update(account=settings.adjustment_income_account)

    # Merma/Pérdida (VIRTUAL)
    if settings.adjustment_expense_account:
        Location.objects.filter(location_type='VIRTUAL', name='Ajuste por Merma/Pérdida').update(account=settings.adjustment_expense_account)

    # Capital de Socios (VIRTUAL)
    if settings.partner_capital_contribution_account:
        Location.objects.filter(location_type='VIRTUAL', name='Capital de Socios').update(account=settings.partner_capital_contribution_account)

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_location_account'),
    ]

    operations = [
        migrations.RunPython(populate_accounts, reverse_populate)
    ]
