# Generated by Django 5.2.10 on 2026-01-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_reorderingrule'),
        ('purchasing', '0008_alter_purchaseorder_journal_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_to_order', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad a Pedir')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONVERTED', 'Convertido a OC'), ('IGNORED', 'Ignorado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_proposals', to='inventory.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_proposals', to='purchasing.purchaseorder')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='inventory.reorderingrule')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_proposals', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Propuesta de Reabastecimiento',
                'verbose_name_plural': 'Propuestas de Reabastecimiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
