# Generated by Django 5.2.10 on 2026-01-10 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_replenishmentproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves_uom', to='inventory.uom'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.warehouse'),
        ),
    ]
