# Generated by Django 5.2.9 on 2026-01-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_stockmove_uom_alter_stockmove_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfg_auto_finalize',
            field=models.BooleanField(default=False, help_text='Si se activa, la OT se marcará como Terminada automáticamente al generarse (Flujo Express)', verbose_name='Finalizar Automáticamente'),
        ),
    ]
