# Generated by Django 6.0.6 on 2026-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventorycount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorydocument',
            name='source_document_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID documento fuente'),
        ),
        migrations.AddField(
            model_name='historicalinventorydocument',
            name='source_document_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo documento fuente'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='source_document_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID documento fuente'),
        ),
        migrations.AddField(
            model_name='inventorydocument',
            name='source_document_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo documento fuente'),
        ),
    ]
