# Generated by Django 5.2.10 on 2026-01-11 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_product_mfg_auto_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, help_text='Unidad sugerida automáticamente al agregar este producto a una orden de compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_purchase', to='inventory.uom', verbose_name='UdM Compra por Defecto'),
        ),
    ]
