# Generated by Django 5.2.10 on 2026-01-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_product_purchase_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mfg_press_special',
            field=models.BooleanField(default=False, help_text='Solicitar información de impresión especial', verbose_name='Impresión: Especial'),
        ),
    ]
