# Generated by Django 6.0.6 on 2026-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_location_partner_alter_location_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorydocument',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalinventorydocument',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductattribute',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductattribute',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductattributevalue',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductattributevalue',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaluom',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaluom',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaluomcategory',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaluomcategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='inventorydocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='uomcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='uomcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
