# Generated by Django 5.2.10 on 2026-01-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_add_mfg_press_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('FIXED', 'Precio Fijo (Unitario)'), ('PACKAGE_FIXED', 'Precio Paquete (Total)'), ('DISCOUNT_PERCENTAGE', 'Porcentaje de Descuento')], default='FIXED', max_length=20, verbose_name='Tipo de Regla'),
        ),
    ]
