# Generated by Django 5.2.10 on 2026-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_update_pricing_rule_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Desactivar para archivar el producto en lugar de eliminarlo.', verbose_name='Activo'),
        ),
    ]
