# Generated by Django 5.2.9 on 2026-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario')], max_length=20, null=True, verbose_name='Motivo de Ajuste'),
        ),
    ]
