# Generated by Django 5.2.9 on 2026-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_stockmove_adjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio Fijo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Costo Ponderado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio Venta'),
        ),
    ]
