# Generated by Django 5.2.10 on 2026-01-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_pricingrule_fixed_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmove',
            name='journal_entry',
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad original en la unidad de la transacción', max_digits=12, null=True, verbose_name='Cantidad Original'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='source_uom',
            field=models.ForeignKey(blank=True, help_text='Unidad original de la transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves_source', to='inventory.uom'),
        ),
    ]
