# Generated by Django 5.2.10 on 2026-01-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_budgetitem_amount_alter_journalitem_credit_and_more'),
        ('inventory', '0032_remove_stockmove_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='accounting.journalentry', verbose_name='Asiento Contable'),
        ),
    ]
