# Generated by Django 5.2.10 on 2026-01-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_stockmove_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='receiving_warehouse',
            field=models.ForeignKey(blank=True, help_text='Bodega sugerida automáticamente al recibir este producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_products', to='inventory.warehouse', verbose_name='Bodega de Recepción por Defecto'),
        ),
    ]
