# Generated by Django 5.2.10 on 2026-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_product_receiving_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variable_amount',
            field=models.BooleanField(default=False, help_text='Indica si el costo mensual varía (ej: luz, agua)', verbose_name='Monto Variable'),
        ),
        migrations.AddField(
            model_name='product',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual'), ('WEEKLY', 'Semanal')], help_text='Frecuencia de facturación/renovación para productos de tipo Suscripción', max_length=20, null=True, verbose_name='Período de Recurrencia'),
        ),
        migrations.AddField(
            model_name='product',
            name='renewal_notice_days',
            field=models.PositiveIntegerField(default=30, help_text='Días de anticipación para avisar sobre la renovación del servicio', verbose_name='Días de Aviso Renovación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('CONSUMABLE', 'Consumible'), ('STORABLE', 'Almacenable'), ('MANUFACTURABLE', 'Fabricable'), ('SERVICE', 'Servicio (Único)'), ('SUBSCRIPTION', 'Suscripción (Recurrente)')], default='STORABLE', max_length=30, verbose_name='Tipo'),
        ),
    ]
