# Generated by Django 5.2.10 on 2026-01-15 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_default_customer_and_more'),
        ('inventory', '0035_product_is_variable_amount_product_recurrence_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Próximo Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Recurrente')),
                ('currency', models.CharField(default='CLP', max_length=10, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Vencida')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('recurrence_period', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual'), ('WEEKLY', 'Semanal')], default='MONTHLY', max_length=20, verbose_name='Frecuencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-next_payment_date'],
            },
        ),
    ]
