# Generated by Django 5.2.10 on 2026-01-15 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_accountingsettings_default_inventory_account'),
        ('inventory', '0036_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Sobreescribe la cuenta de la categoría para este producto.', limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_expenses', to='accounting.account', verbose_name='Cuenta de Gastos (Personalizada)'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Sobreescribe la cuenta de la categoría para este producto.', limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_incomes', to='accounting.account', verbose_name='Cuenta de Ingresos (Personalizada)'),
        ),
    ]
