# Generated by Django 5.2.10 on 2026-01-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_product_expense_account_product_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_confirmation_required',
            field=models.BooleanField(default=False, help_text='Si está activo, requiere confirmación manual del monto antes de procesar el pago', verbose_name='Requiere Confirmación de Monto'),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_approve_renewals',
            field=models.BooleanField(default=False, help_text='Si está activo, las renovaciones se confirman automáticamente sin revisión manual', verbose_name='Auto-aprobar Renovaciones'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_invoice_type',
            field=models.CharField(blank=True, choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], help_text='Tipo de documento a usar en renovaciones automáticas', max_length=20, null=True, verbose_name='Tipo de Documento por Defecto'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_day',
            field=models.PositiveIntegerField(blank=True, help_text='Día del mes para pago (1-31). Solo aplica si payment_day_type es FIXED_DAY', null=True, verbose_name='Día de Pago'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_day_type',
            field=models.CharField(blank=True, choices=[('INTERVAL', 'Cada N días'), ('FIXED_DAY', 'Día fijo del mes')], help_text='Define si el pago es cada N días o un día fijo del mes', max_length=20, null=True, verbose_name='Tipo de Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='product',
            name='payment_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de días entre pagos. Solo aplica si payment_day_type es INTERVAL', null=True, verbose_name='Intervalo de Días'),
        ),
    ]
