# Generated by Django 5.2.10 on 2026-01-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_default_customer_and_more'),
        ('inventory', '0038_add_subscription_payment_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount_confirmation_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auto_approve_renewals',
        ),
        migrations.AddField(
            model_name='product',
            name='auto_activate_subscription',
            field=models.BooleanField(default=False, help_text='Si está activo, crea el registro de suscripción al guardar el producto', verbose_name='Activar Suscripción Automáticamente'),
        ),
        migrations.AddField(
            model_name='product',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Fecha en que finaliza el contrato (solo si no es indefinida)', null=True, verbose_name='Fecha de Finalización del Contrato'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_indefinite',
            field=models.BooleanField(default=True, help_text='Si está activo, la suscripción no tiene fecha de finalización', verbose_name='Suscripción Indefinida'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto mensual/periódico de la suscripción', max_digits=12, null=True, verbose_name='Monto de Suscripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la suscripción (default: hoy)', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor para activar la suscripción automáticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_products', to='contacts.contact', verbose_name='Proveedor de Suscripción'),
        ),
    ]
