# Generated by Django 5.2.10 on 2026-01-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_add_subscription_activation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento %'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='max_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Solo usado para el operador 'Entre'", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Máxima / Hasta'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='min_quantity',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima / Desde'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto mensual/periódico de la suscripción', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Suscripción'),
        ),
        migrations.AlterField(
            model_name='reorderingrule',
            name='max_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Máxima'),
        ),
        migrations.AlterField(
            model_name='reorderingrule',
            name='min_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima'),
        ),
    ]
