# Generated by Django 5.2.10 on 2026-01-18 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_default_customer_and_more'),
        ('inventory', '0040_alter_pricingrule_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor sugerido para reabastecimiento y órdenes de compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='contacts.contact', verbose_name='Proveedor Preferido'),
        ),
        migrations.AddField(
            model_name='replenishmentproposal',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_proposals', to='contacts.contact'),
        ),
    ]
