# Generated by Django 5.2.10 on 2026-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_product_preferred_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dynamic_pricing',
            field=models.BooleanField(default=False, help_text='Permite asignar el precio manualmente al vender (ignora precio de lista).', verbose_name='Precio Gestionable'),
        ),
    ]
