# Generated by Django 5.2.10 on 2026-01-20 01:21

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_budget_options_alter_journalentry_options'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('inventory', '0042_product_is_dynamic_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['-id'], 'verbose_name': 'Regla de Precio', 'verbose_name_plural': 'Reglas de Precio'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Producto'},
        ),
        migrations.AlterModelOptions(
            name='stockmove',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Kardex'},
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'ordering': ['-id'], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AlterModelOptions(
            name='uomcategory',
            options={'ordering': ['-id'], 'verbose_name': 'Categoría de Medida', 'verbose_name_plural': 'Categorías de Medida'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-id'], 'verbose_name': 'Almacén/Bodega', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, verbose_name='Código Interno')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Código/SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('product_type', models.CharField(choices=[('CONSUMABLE', 'Consumible'), ('STORABLE', 'Almacenable'), ('MANUFACTURABLE', 'Fabricable'), ('SERVICE', 'Servicio (Único)'), ('SUBSCRIPTION', 'Suscripción (Recurrente)')], default='STORABLE', max_length=30, verbose_name='Tipo')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen')),
                ('custom_fields_schema', models.JSONField(blank=True, help_text='Define campos adicionales requeridos al vender (ej: tamaño, copias, folio inicial)', null=True, verbose_name='Esquema de Campos Customizados')),
                ('has_bom', models.BooleanField(default=False, help_text='Indica si este producto tiene componentes definidos que se asignarán a órdenes de trabajo', verbose_name='Tiene Lista de Materiales')),
                ('requires_advanced_manufacturing', models.BooleanField(default=False, help_text='Habilita campos personalizados al vender este producto desde POS o notas de venta', verbose_name='Requiere Fabricación Avanzada')),
                ('mfg_auto_finalize', models.BooleanField(default=False, help_text='Si se activa, la OT se marcará como Terminada automáticamente al generarse (Flujo Express)', verbose_name='Finalizar Automáticamente')),
                ('mfg_enable_prepress', models.BooleanField(default=False, help_text='Activa la etapa de pre-impresión en el flujo de fabricación', verbose_name='Habilitar Pre-Impresión')),
                ('mfg_enable_press', models.BooleanField(default=False, help_text='Activa la etapa de impresión en el flujo de fabricación', verbose_name='Habilitar Impresión')),
                ('mfg_enable_postpress', models.BooleanField(default=False, help_text='Activa la etapa de post-impresión en el flujo de fabricación', verbose_name='Habilitar Post-Impresión')),
                ('mfg_prepress_design', models.BooleanField(default=False, help_text='Solicitar diseño en la etapa de pre-impresión', verbose_name='Pre-Impresión: Diseño Requerido')),
                ('mfg_prepress_specs', models.BooleanField(default=False, help_text='Solicitar especificaciones en la etapa de pre-impresión', verbose_name='Pre-Impresión: Especificaciones')),
                ('mfg_prepress_folio', models.BooleanField(default=False, help_text='Solicitar folio en la etapa de pre-impresión', verbose_name='Pre-Impresión: Folio')),
                ('mfg_press_offset', models.BooleanField(default=False, help_text='Solicitar información de impresión offset', verbose_name='Impresión: Offset')),
                ('mfg_press_digital', models.BooleanField(default=False, help_text='Solicitar información de impresión digital', verbose_name='Impresión: Digital')),
                ('mfg_press_special', models.BooleanField(default=False, help_text='Solicitar información de impresión especial', verbose_name='Impresión: Especial')),
                ('mfg_postpress_finishing', models.BooleanField(default=False, help_text='Solicitar información de acabados', verbose_name='Post-Impresión: Acabados')),
                ('mfg_postpress_binding', models.BooleanField(default=False, help_text='Solicitar información de encuadernación o troquelado', verbose_name='Post-Impresión: Encuadernación/Troquelado')),
                ('mfg_default_delivery_days', models.IntegerField(default=3, help_text='Días a sumar a la fecha actual para la fecha estimada de entrega', verbose_name='Días de Entrega por Defecto')),
                ('recurrence_period', models.CharField(blank=True, choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('SEMIANNUAL', 'Semestral'), ('ANNUAL', 'Anual'), ('WEEKLY', 'Semanal')], help_text='Frecuencia de facturación/renovación para productos de tipo Suscripción', max_length=20, null=True, verbose_name='Período de Recurrencia')),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, help_text='Días de anticipación para avisar sobre la renovación del servicio', verbose_name='Días de Aviso Renovación')),
                ('is_variable_amount', models.BooleanField(default=False, help_text='Indica si el costo mensual varía (ej: luz, agua)', verbose_name='Monto Variable')),
                ('payment_day_type', models.CharField(blank=True, choices=[('INTERVAL', 'Cada N días'), ('FIXED_DAY', 'Día fijo del mes')], help_text='Define si el pago es cada N días o un día fijo del mes', max_length=20, null=True, verbose_name='Tipo de Fecha de Pago')),
                ('payment_day', models.PositiveIntegerField(blank=True, help_text='Día del mes para pago (1-31). Solo aplica si payment_day_type es FIXED_DAY', null=True, verbose_name='Día de Pago')),
                ('payment_interval_days', models.PositiveIntegerField(blank=True, help_text='Cantidad de días entre pagos. Solo aplica si payment_day_type es INTERVAL', null=True, verbose_name='Intervalo de Días')),
                ('default_invoice_type', models.CharField(blank=True, choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], help_text='Tipo de documento a usar en renovaciones automáticas', max_length=20, null=True, verbose_name='Tipo de Documento por Defecto')),
                ('subscription_amount', models.DecimalField(blank=True, decimal_places=0, help_text='Monto mensual/periódico de la suscripción', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de Suscripción')),
                ('subscription_start_date', models.DateField(blank=True, help_text='Fecha de inicio de la suscripción (default: hoy)', null=True, verbose_name='Fecha de Inicio')),
                ('auto_activate_subscription', models.BooleanField(default=False, help_text='Si está activo, crea el registro de suscripción al guardar el producto', verbose_name='Activar Suscripción Automáticamente')),
                ('is_indefinite', models.BooleanField(default=True, help_text='Si está activo, la suscripción no tiene fecha de finalización', verbose_name='Suscripción Indefinida')),
                ('contract_end_date', models.DateField(blank=True, help_text='Fecha en que finaliza el contrato (solo si no es indefinida)', null=True, verbose_name='Fecha de Finalización del Contrato')),
                ('track_inventory', models.BooleanField(default=True, help_text='Desactivar para productos que no requieren control de inventario (fabricables, servicios)', verbose_name='Controlar Stock')),
                ('can_be_sold', models.BooleanField(default=True, help_text='Si se desactiva, el producto no aparecerá en ventas ni en POS.', verbose_name='Puede ser vendido')),
                ('can_be_purchased', models.BooleanField(default=True, help_text='Si se desactiva, el producto no aparecerá en órdenes de compra.', verbose_name='Puede ser comprado')),
                ('is_dynamic_pricing', models.BooleanField(default=False, help_text='Permite asignar el precio manualmente al vender (ignora precio de lista).', verbose_name='Precio Gestionable')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Costo Ponderado')),
                ('active', models.BooleanField(default=True, help_text='Desactivar para archivar el producto en lugar de eliminarlo.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productcategory')),
                ('expense_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Sobreescribe la cuenta de la categoría para este producto.', limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta de Gastos (Personalizada)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('income_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Sobreescribe la cuenta de la categoría para este producto.', limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta de Ingresos (Personalizada)')),
                ('preferred_supplier', models.ForeignKey(blank=True, db_constraint=False, help_text='Proveedor sugerido para reabastecimiento y órdenes de compra.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor Preferido')),
                ('purchase_uom', models.ForeignKey(blank=True, db_constraint=False, help_text='Unidad sugerida automáticamente al agregar este producto a una orden de compra.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom', verbose_name='UdM Compra por Defecto')),
                ('receiving_warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega sugerida automáticamente al recibir este producto.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='Bodega de Recepción por Defecto')),
                ('sale_uom', models.ForeignKey(blank=True, db_constraint=False, help_text="⚠️ DEPRECATED: Use 'allowed_sale_uoms' en su lugar. Este campo se mantendrá solo para compatibilidad.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom', verbose_name='UdM Venta (DEPRECATED)')),
                ('subscription_supplier', models.ForeignKey(blank=True, db_constraint=False, help_text='Proveedor para activar la suscripción automáticamente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor de Suscripción')),
                ('uom', models.ForeignKey(blank=True, db_constraint=False, help_text='Unidad base para gestión de stock. Todas las conversiones se hacen a esta unidad.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom', verbose_name='Unidad de Medida Base')),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
