# Generated by Django 5.2.10 on 2026-01-20 05:11

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_historicaljournalentry'),
        ('inventory', '0043_alter_pricingrule_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockMove',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('move_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('adjustment_reason', models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario')], max_length=20, null=True, verbose_name='Motivo de Ajuste')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('source_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad original en la unidad de la transacción', max_digits=12, null=True, verbose_name='Cantidad Original')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('source_uom', models.ForeignKey(blank=True, db_constraint=False, help_text='Unidad original de la transacción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom')),
                ('uom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Movimiento de Stock',
                'verbose_name_plural': 'historical Kardex',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
