# Generated by Django 5.2.10 on 2026-01-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_historicalstockmove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_moves', to='inventory.warehouse'),
        ),
    ]
