# Generated by Django 5.2.10 on 2026-01-20 19:42

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_stockmove_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPricingRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Regla')),
                ('operator', models.CharField(choices=[('GT', 'Mayor que (>)'), ('LT', 'Menor que (<)'), ('EQ', 'Igual a (=)'), ('GE', 'Mayor o Igual (>=)'), ('LE', 'Menor o Igual (<=)'), ('BT', 'Entre (Rango)')], default='GE', max_length=5, verbose_name='Operador')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima / Desde')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, help_text="Solo usado para el operador 'Entre'", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Máxima / Hasta')),
                ('rule_type', models.CharField(choices=[('FIXED', 'Precio Fijo (Unitario)'), ('PACKAGE_FIXED', 'Precio Paquete (Total)'), ('DISCOUNT_PERCENTAGE', 'Porcentaje de Descuento')], default='FIXED', max_length=20, verbose_name='Tipo de Regla')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento %')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad más alta se aplica primero', verbose_name='Prioridad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('uom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.uom', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'historical Regla de Precio',
                'verbose_name_plural': 'historical Reglas de Precio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReorderingRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('max_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Máxima')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Regla de Reabastecimiento',
                'verbose_name_plural': 'historical Reglas de Reabastecimiento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
