# Generated by Django 5.2.10 on 2026-01-20 20:52

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_historicalpricingrule_historicalreorderingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[core.validators.validate_file_size, core.validators.validate_image_extension], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.UploadPath('products/'), validators=[core.validators.validate_file_size, core.validators.validate_image_extension], verbose_name='Imagen'),
        ),
    ]
