# Generated by Django 5.2.10 on 2026-01-20 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_alter_historicalproduct_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='Costo Ponderado'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=16, verbose_name='Costo Ponderado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Monto Recurrente'),
        ),
    ]
