# Generated by Django 5.2.10 on 2026-01-21 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_uom_cost_price_uom_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uom',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='uom',
            name='sale_price',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Costo Ponderado'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Costo Ponderado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
    ]
