# Generated by Django 5.2.10 on 2026-01-21 01:29

import django.core.validators
from django.db import migrations, models


def populate_gross_prices(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    from decimal import Decimal
    vat_rate = Decimal('1.19')
    for product in Product.objects.all():
        if product.sale_price:
            product.sale_price_gross = (product.sale_price * vat_rate).quantize(Decimal('1'), rounding='ROUND_HALF_UP')
            product.save(update_fields=['sale_price_gross'])

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_remove_uom_cost_price_remove_uom_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='sale_price_gross',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio con IVA incluido, usado para cálculos de venta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta BRUTO (c/IVA)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price_gross',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio con IVA incluido, usado para cálculos de venta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta BRUTO (c/IVA)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio de venta sin IVA (referencia)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta NETO'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio de venta sin IVA (referencia)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta NETO'),
        ),
        migrations.RunPython(populate_gross_prices, reverse_code=migrations.RunPython.noop),
    ]
