# Generated by Django 5.2.10 on 2026-01-21 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_add_sale_price_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpricingrule',
            name='fixed_price_gross',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo (Bruto)'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='fixed_price_gross',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo (Bruto)'),
        ),
        migrations.AlterField(
            model_name='historicalpricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo (Neto)'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Fijo (Neto)'),
        ),
    ]
