# Generated by Django 5.2.10 on 2026-02-02 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_historicalpricingrule_fixed_price_gross_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atributo de Producto',
                'verbose_name_plural': 'Atributos de Producto',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Indica si este producto actúa como plantilla para múltiples variantes.', verbose_name='Tiene Variantes'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='parent_template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Si está definido, este producto es una variante de la plantilla seleccionada.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Plantilla Padre'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='variant_display_name',
            field=models.CharField(blank=True, help_text='Nombre descriptivo para esta variante específica. Si se deja vacío, se generará automáticamente.', max_length=255, null=True, verbose_name='Nombre de Variante'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False, help_text='Indica si este producto actúa como plantilla para múltiples variantes.', verbose_name='Tiene Variantes'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_template',
            field=models.ForeignKey(blank=True, help_text='Si está definido, este producto es una variante de la plantilla seleccionada.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product', verbose_name='Plantilla Padre'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_display_name',
            field=models.CharField(blank=True, help_text='Nombre descriptivo para esta variante específica. Si se deja vacío, se generará automáticamente.', max_length=255, null=True, verbose_name='Nombre de Variante'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.productattribute')),
            ],
            options={
                'verbose_name': 'Valor de Atributo',
                'verbose_name_plural': 'Valores de Atributo',
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Valores que definen esta variante (ej: Color Rojo, Talla L)', related_name='products', to='inventory.productattributevalue', verbose_name='Valores de Atributos'),
        ),
    ]
