# Generated by Django 5.2.12 on 2026-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_alter_historicalstockmove_date_alter_stockmove_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstockmove',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del producto en el momento de este movimiento', max_digits=12, verbose_name='Costo Unitario'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del producto en el momento de este movimiento', max_digits=12, verbose_name='Costo Unitario'),
        ),
    ]
