# Generated by Django 5.2.12 on 2026-03-10 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_add_unit_cost_to_stockmove'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reorderingrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reorderingrule',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reorderingrule',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='replenishmentproposal',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='replenishmentproposal',
            name='product',
        ),
        migrations.RemoveField(
            model_name='replenishmentproposal',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='replenishmentproposal',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='replenishmentproposal',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='HistoricalReorderingRule',
        ),
        migrations.DeleteModel(
            name='ReorderingRule',
        ),
        migrations.DeleteModel(
            name='ReplenishmentProposal',
        ),
    ]
