# Generated by Django 5.2.12 on 2026-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_remove_historicalproduct_custom_fields_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockmove',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario'), ('PARTNER_CONTRIBUTION', 'Aporte de Socio (Inventario)'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio (Inventario)')], max_length=20, null=True, verbose_name='Motivo de Ajuste'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('INITIAL', 'Inventario Inicial'), ('LOSS', 'Merma/Pérdida'), ('GAIN', 'Sobrante/Ganancia'), ('REVALUATION', 'Revalorización'), ('CORRECTION', 'Corrección de Inventario'), ('PARTNER_CONTRIBUTION', 'Aporte de Socio (Inventario)'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio (Inventario)')], max_length=20, null=True, verbose_name='Motivo de Ajuste'),
        ),
    ]
