# Generated by Django 5.2.12 on 2026-04-15 01:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingsettings_billing_model'),
        ('contacts', '0007_contact_partner_dividends_payable_account_and_more'),
        ('inventory', '0001_initial'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerminalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Terminal Barra 1', max_length=100, verbose_name='Nombre / Alias')),
                ('serial_number', models.CharField(help_text='ID único que el proveedor asigna a este dispositivo físico (ej: TU1245)', max_length=100, verbose_name='Número de Serie Interno / ID Dispositivo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('MAINTENANCE', 'En Mantención')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('device_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración del Dispositivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo de Terminal',
                'verbose_name_plural': 'Dispositivos de Terminal',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='processes_via_terminal',
            field=models.BooleanField(default=False, help_text='Si es Verdadero, al usar este método en ventas el sistema derivará a la maquinita configurada.', verbose_name='Procesa Vía Terminal'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='processes_via_terminal',
            field=models.BooleanField(default=False, help_text='Si es Verdadero, al usar este método en ventas el sistema derivará a la maquinita configurada.', verbose_name='Procesa Vía Terminal'),
        ),
        migrations.AlterField(
            model_name='historicaltreasuryaccount',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'ASSET', 'code__startswith': '1.1.01'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Contable'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'ASSET', 'code__startswith': '1.1.01'}, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account', verbose_name='Cuenta Contable'),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentTerminalProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('provider_type', models.CharField(choices=[('TRANSBANK', 'Transbank'), ('TUU', 'TUU / Haulmer'), ('MERCADOPAGO', 'MercadoPago'), ('FINTOC', 'Fintoc'), ('FLOW', 'Flow'), ('MANUAL', 'Manual en Máquina (Genérico)')], default='MANUAL', max_length=20, verbose_name='Tipo de Proveedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('gateway_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de Gateway')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_treasury_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Destino Liquidación')),
                ('commission_expense_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Gasto Comisión')),
                ('commission_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto Servicio Comisión')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Por Cobrar Terminal')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor (Contacto)')),
            ],
            options={
                'verbose_name': 'historical Proveedor de Terminal',
                'verbose_name_plural': 'historical Proveedores de Terminal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalposterminal',
            name='payment_terminal_device',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='La maquinita física amarrada a esta caja del sistema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminaldevice', verbose_name='Dispositivo de Cobro Asociado'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='payment_terminal_device',
            field=models.ForeignKey(blank=True, help_text='La maquinita física amarrada a esta caja del sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='treasury.paymentterminaldevice', verbose_name='Dispositivo de Cobro Asociado'),
        ),
        migrations.CreateModel(
            name='PaymentTerminalProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('provider_type', models.CharField(choices=[('TRANSBANK', 'Transbank'), ('TUU', 'TUU / Haulmer'), ('MERCADOPAGO', 'MercadoPago'), ('FINTOC', 'Fintoc'), ('FLOW', 'Flow'), ('MANUAL', 'Manual en Máquina (Genérico)')], default='MANUAL', max_length=20, verbose_name='Tipo de Proveedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('gateway_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de Gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_providers', to='treasury.treasuryaccount', verbose_name='Cuenta Destino Liquidación')),
                ('commission_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_provider_commission', to='accounting.account', verbose_name='Cuenta Gasto Comisión')),
                ('commission_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_commission_providers', to='inventory.product', verbose_name='Producto Servicio Comisión')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_provider_receivable', to='accounting.account', verbose_name='Cuenta Por Cobrar Terminal')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_providers', to='contacts.contact', verbose_name='Proveedor (Contacto)')),
            ],
            options={
                'verbose_name': 'Proveedor de Terminal',
                'verbose_name_plural': 'Proveedores de Terminal',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paymentterminaldevice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='treasury.paymentterminalprovider', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentTerminalDevice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Terminal Barra 1', max_length=100, verbose_name='Nombre / Alias')),
                ('serial_number', models.CharField(help_text='ID único que el proveedor asigna a este dispositivo físico (ej: TU1245)', max_length=100, verbose_name='Número de Serie Interno / ID Dispositivo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('MAINTENANCE', 'En Mantención')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('device_config', models.JSONField(blank=True, default=dict, verbose_name='Configuración del Dispositivo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminalprovider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'historical Dispositivo de Terminal',
                'verbose_name_plural': 'historical Dispositivos de Terminal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalterminalbatch',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminalprovider', verbose_name='Proveedor de Terminal'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='terminal_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminalprovider', verbose_name='Proveedor Terminal'),
        ),
        migrations.AddField(
            model_name='terminalbatch',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='treasury.paymentterminalprovider', verbose_name='Proveedor de Terminal'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='terminal_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.paymentterminalprovider', verbose_name='Proveedor Terminal'),
        ),
    ]
