# Generated by Django 5.2.9 on 2026-01-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_payment_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_pending_registration',
            field=models.BooleanField(default=False, verbose_name='Transacción Pendiente de Registro'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Transacción'),
        ),
    ]
