# Generated by Django 5.2.9 on 2026-01-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountingsettings_inventory_valuation_method'),
        ('treasury', '0003_payment_is_pending_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='journal',
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.account', verbose_name='Cuenta de Tesorería'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.DeleteModel(
            name='BankJournal',
        ),
    ]
