# Generated by Django 5.2.12 on 2026-04-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_remove_terminalbatch_treasury_te_payment_89882a_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaymentmethod',
            old_name='processes_via_terminal',
            new_name='process_via_terminal',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='processes_via_terminal',
            new_name='process_via_terminal',
        ),
    ]
