# Generated by Django 5.2.9 on 2026-01-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_remove_accountingsettings_default_card_account_and_more'),
        ('treasury', '0004_remove_payment_journal_payment_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_account', to='accounting.account', verbose_name='Cuenta Contable (Snapshot)'),
        ),
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Moneda')),
                ('account_type', models.CharField(choices=[('BANK', 'Banco'), ('CASH', 'Caja')], default='CASH', max_length=10, verbose_name='Tipo')),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounting.account', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Cuenta de Tesorería',
                'verbose_name_plural': 'Cuentas de Tesorería',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='treasury_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pay_treasury', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería'),
        ),
    ]
