# Generated by Django 5.2.9 on 2026-01-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('treasury', '0005_alter_payment_account_treasuryaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contacts.contact'),
        ),
    ]
