# Generated by Django 5.2.9 on 2026-01-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
        ('treasury', '0006_remove_payment_customer_remove_payment_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='accounting.journalentry'),
        ),
    ]
