# Generated by Django 5.2.10 on 2026-01-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_alter_payment_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='allowed_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], default='CASH', max_length=20, null=True, verbose_name='Método de Pago Permitido'),
        ),
    ]
