# Generated by Django 5.2.10 on 2026-01-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_treasuryaccount_allowed_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='allowed_payment_method',
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='allows_card',
            field=models.BooleanField(default=False, verbose_name='Permite Tarjeta'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='allows_cash',
            field=models.BooleanField(default=False, verbose_name='Permite Efectivo'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='allows_transfer',
            field=models.BooleanField(default=False, verbose_name='Permite Transferencia'),
        ),
    ]
