# Generated by Django 5.2.12 on 2026-04-15 21:27

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
        ('treasury', '0009_drop_tuu_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='UUID único enviado al proveedor; previene cobros duplicados.', max_length=36, verbose_name='Clave de Idempotencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado a Terminal'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount', models.PositiveIntegerField(help_text='Monto en pesos sin decimales; mínimo 100 según TUU.', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Monto (CLP entero)')),
                ('dte_type', models.IntegerField(default=48, help_text='48=comprobante pago electrónico (tarjeta).', verbose_name='Tipo DTE')),
                ('payment_method_code', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito')], default=1, verbose_name='Método de Pago Terminal')),
                ('description', models.CharField(blank=True, help_text='Máximo 28 caracteres según validación TUU.', max_length=28, verbose_name='Descripción')),
                ('sequence_number', models.CharField(blank=True, help_text='sequenceNumber devuelto por TUU; clave de reconciliación.', max_length=32, verbose_name='Nº Correlativo Terminal')),
                ('transaction_reference', models.CharField(blank=True, max_length=64, verbose_name='Referencia Transacción')),
                ('acquirer_id', models.CharField(blank=True, max_length=64, verbose_name='ID Adquirente')),
                ('raw_last_response', models.JSONField(blank=True, default=dict, verbose_name='Última Respuesta Cruda')),
                ('failure_reason', models.CharField(blank=True, help_text='Código MR-/RP-/KEY-/TIMEOUT.', max_length=64, verbose_name='Motivo de Falla')),
                ('initiated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Iniciada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, verbose_name='Celery Task ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminaldevice', verbose_name='Dispositivo Terminal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pos_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possession', verbose_name='Sesión POS')),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminalprovider', verbose_name='Proveedor')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='Nota de Venta')),
            ],
            options={
                'verbose_name': 'historical Solicitud de Pago',
                'verbose_name_plural': 'historical Solicitudes de Pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(help_text='UUID único enviado al proveedor; previene cobros duplicados.', max_length=36, unique=True, verbose_name='Clave de Idempotencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado a Terminal'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELED', 'Cancelado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('amount', models.PositiveIntegerField(help_text='Monto en pesos sin decimales; mínimo 100 según TUU.', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Monto (CLP entero)')),
                ('dte_type', models.IntegerField(default=48, help_text='48=comprobante pago electrónico (tarjeta).', verbose_name='Tipo DTE')),
                ('payment_method_code', models.IntegerField(choices=[(1, 'Crédito'), (2, 'Débito')], default=1, verbose_name='Método de Pago Terminal')),
                ('description', models.CharField(blank=True, help_text='Máximo 28 caracteres según validación TUU.', max_length=28, verbose_name='Descripción')),
                ('sequence_number', models.CharField(blank=True, help_text='sequenceNumber devuelto por TUU; clave de reconciliación.', max_length=32, verbose_name='Nº Correlativo Terminal')),
                ('transaction_reference', models.CharField(blank=True, max_length=64, verbose_name='Referencia Transacción')),
                ('acquirer_id', models.CharField(blank=True, max_length=64, verbose_name='ID Adquirente')),
                ('raw_last_response', models.JSONField(blank=True, default=dict, verbose_name='Última Respuesta Cruda')),
                ('failure_reason', models.CharField(blank=True, help_text='Código MR-/RP-/KEY-/TIMEOUT.', max_length=64, verbose_name='Motivo de Falla')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, verbose_name='Celery Task ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='treasury.paymentterminaldevice', verbose_name='Dispositivo Terminal')),
                ('pos_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='treasury.possession', verbose_name='Sesión POS')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='treasury.paymentterminalprovider', verbose_name='Proveedor')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='sales.saleorder', verbose_name='Nota de Venta')),
            ],
            options={
                'verbose_name': 'Solicitud de Pago',
                'verbose_name_plural': 'Solicitudes de Pago',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='treasury_pa_device__d181ea_idx'), models.Index(fields=['sale_order', 'status'], name='treasury_pa_sale_or_affdc2_idx'), models.Index(fields=['-initiated_at', 'status'], name='treasury_pa_initiat_ea3870_idx'), models.Index(fields=['sequence_number'], name='treasury_pa_sequenc_6446eb_idx')],
            },
        ),
    ]
