# Generated by Django 5.2.10 on 2026-01-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_remove_treasuryaccount_allowed_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='treasuryaccount',
            options={'ordering': ['-id'], 'verbose_name': 'Cuenta de Tesorería', 'verbose_name_plural': 'Cuentas de Tesorería'},
        ),
    ]
