# Generated by Django 5.2.10 on 2026-01-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_remove_treasuryaccount_allowed_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='tuu_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tuu API Key'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='tuu_device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuu Device ID'),
        ),
    ]
