# Generated by Django 5.2.12 on 2026-04-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleorder_payment_pending'),
        ('treasury', '0010_payment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentrequest',
            name='terminal_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lote TUU al que pertenece esta transacción (asignado en reconciliación Fase 3).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.terminalbatch', verbose_name='Lote Terminal'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='terminal_batch',
            field=models.ForeignKey(blank=True, help_text='Lote TUU al que pertenece esta transacción (asignado en reconciliación Fase 3).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='treasury.terminalbatch', verbose_name='Lote Terminal'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['terminal_batch'], name='treasury_pa_termina_9cbd1e_idx'),
        ),
    ]
