# Generated by Django 5.2.10 on 2026-01-31 14:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_accountingsettings_manufactured_cogs_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('purchasing', '0020_add_related_note_to_lines'),
        ('sales', '0026_add_work_order_to_delivery_line'),
        ('treasury', '0012_historicalpayment_is_reconciled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReconciliationMatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Grupo de Conciliación',
                'verbose_name_plural': 'historical Grupos de Conciliación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReconciliationRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito de esta regla', verbose_name='Descripción')),
                ('priority', models.IntegerField(default=10, help_text='Menor número = mayor prioridad', verbose_name='Prioridad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('match_config', models.JSONField(default=dict, help_text='Configuración en JSON con criterios de matching', verbose_name='Configuración de Matching')),
                ('auto_confirm', models.BooleanField(default=False, help_text='Si es True, confirma reconciliación automáticamente sin revisión', verbose_name='Auto-confirmar')),
                ('create_payment_if_not_found', models.BooleanField(default=False, help_text='Crear pago automático si no se encuentra match (casos especiales)', verbose_name='Crear Pago si no existe')),
                ('times_applied', models.IntegerField(default=0, help_text='Contador de veces que esta regla ha generado un match', verbose_name='Veces Aplicada')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de matches confirmados vs sugeridos', max_digits=5, verbose_name='Tasa de Éxito')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Regla de Reconciliación',
                'verbose_name_plural': 'historical Reglas de Reconciliación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Grupo de Conciliación',
                'verbose_name_plural': 'Grupos de Conciliación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='auto_confirm',
            field=models.BooleanField(default=False, help_text='Si es True, confirma reconciliación automáticamente sin revisión', verbose_name='Auto-confirmar'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='create_payment_if_not_found',
            field=models.BooleanField(default=False, help_text='Crear pago automático si no se encuentra match (casos especiales)', verbose_name='Crear Pago si no existe'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_reconciliation_rules', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del propósito de esta regla', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de matches confirmados vs sugeridos', max_digits=5, verbose_name='Tasa de Éxito'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='times_applied',
            field=models.IntegerField(default=0, help_text='Contador de veces que esta regla ha generado un match', verbose_name='Veces Aplicada'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_lines', to='treasury.payment', verbose_name='Pago Matched'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.payment', verbose_name='Pago Matched'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de cartola Bancario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.bankstatementline', verbose_name='Línea de cartola Bancario'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['statement_date', 'treasury_account'], name='treasury_ba_stateme_760251_idx'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='treasury_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationrule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreconciliationrule',
            name='treasury_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dejar vacío para aplicar a todas las cuentas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_matches', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='treasury_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_matches', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación'),
        ),
        migrations.AddField(
            model_name='historicalbankstatementline',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reconciliation_state'], name='treasury_ba_reconci_105e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['transaction_date'], name='treasury_ba_transac_120b87_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement', 'reconciliation_state'], name='treasury_ba_stateme_a30002_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['transaction_id'], name='treasury_ba_transac_ce9261_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['treasury_account', 'is_reconciled'], name='treasury_pa_treasur_eae50d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['amount', 'date'], name='treasury_pa_amount_3c0a68_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_reconciled'], name='treasury_pa_is_reco_e514c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_number'], name='treasury_pa_transac_1fe75f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='treasury_pa_referen_1e55e5_idx'),
        ),
    ]
