# Generated by Django 5.2.10 on 2026-02-01 23:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_accountingsettings_bank_commission_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('treasury', '0013_historicalreconciliationmatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 2.95 para 2.95%', max_digits=5, verbose_name='Tasa de Comisión (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo por transacción (además del porcentaje)', max_digits=10, verbose_name='Monto Fijo por Transacción')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, help_text='IVA sobre la comisión', max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('settlement_delay_days', models.IntegerField(default=1, help_text='Días que tarda en abonar desde la transacción (ej: T+1)', verbose_name='Días de Retraso de Abono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_bridge_account', models.ForeignKey(help_text='Pasivo transitorio: Comisiones retenidas pendientes de facturar', on_delete=django.db.models.deletion.PROTECT, related_name='card_commission_bridges', to='accounting.account', verbose_name='Cuenta Puente Comisiones Pendientes')),
                ('receivable_account', models.ForeignKey(help_text='Cuenta de activo donde se registra la venta con tarjeta', on_delete=django.db.models.deletion.PROTECT, related_name='card_provider_receivables', to='accounting.account', verbose_name='Cuenta Tarjetas por Cobrar')),
                ('supplier', models.ForeignKey(help_text='Contacto del proveedor que emite las facturas de comisiones', on_delete=django.db.models.deletion.PROTECT, related_name='card_providers', to='contacts.contact', verbose_name='Proveedor que Factura')),
            ],
            options={
                'verbose_name': 'Proveedor de Pagos con Tarjeta',
                'verbose_name_plural': 'Proveedores de Pagos con Tarjeta',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='card_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Si el pago es con tarjeta, proveedor que procesa la transacción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_provider',
            field=models.ForeignKey(blank=True, help_text='Si el pago es con tarjeta, proveedor que procesa la transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_payments', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.CreateModel(
            name='HistoricalCardPaymentProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Código')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 2.95 para 2.95%', max_digits=5, verbose_name='Tasa de Comisión (%)')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo por transacción (además del porcentaje)', max_digits=10, verbose_name='Monto Fijo por Transacción')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=19, help_text='IVA sobre la comisión', max_digits=5, verbose_name='Tasa de IVA (%)')),
                ('settlement_delay_days', models.IntegerField(default=1, help_text='Días que tarda en abonar desde la transacción (ej: T+1)', verbose_name='Días de Retraso de Abono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commission_bridge_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Pasivo transitorio: Comisiones retenidas pendientes de facturar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Puente Comisiones Pendientes')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receivable_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta de activo donde se registra la venta con tarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Tarjetas por Cobrar')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, help_text='Contacto del proveedor que emite las facturas de comisiones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor que Factura')),
            ],
            options={
                'verbose_name': 'historical Proveedor de Pagos con Tarjeta',
                'verbose_name_plural': 'historical Proveedores de Pagos con Tarjeta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCardTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('authorization_code', models.CharField(blank=True, help_text='Número de autorización del procesador', max_length=50, verbose_name='Código de Autorización')),
                ('card_last_digits', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la transacción/venta', max_digits=12, verbose_name='Monto Bruto')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Comisión neta del proveedor', max_digits=12, verbose_name='Comisión (sin IVA)')),
                ('commission_vat', models.DecimalField(decimal_places=2, help_text='IVA de la comisión (crédito fiscal)', max_digits=12, verbose_name='IVA sobre Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto que efectivamente se abona: bruto - comisión - IVA', max_digits=12, verbose_name='Monto Neto a Recibir')),
                ('expected_settlement_date', models.DateField(blank=True, help_text='Fecha estimada en que el proveedor abonará a banco', null=True, verbose_name='Fecha Esperada de Abono')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciliado')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciliado el')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_statement_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de Extracto Bancario')),
                ('commission_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento de Comisión Diaria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monthly_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura Mensual')),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.payment', verbose_name='Pago Asociado')),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cardpaymentprovider', verbose_name='Proveedor')),
                ('reconciled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reconciliado Por')),
            ],
            options={
                'verbose_name': 'historical Transacción de Tarjeta',
                'verbose_name_plural': 'historical Transacciones de Tarjeta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Fecha de Transacción')),
                ('authorization_code', models.CharField(blank=True, help_text='Número de autorización del procesador', max_length=50, verbose_name='Código de Autorización')),
                ('card_last_digits', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 Dígitos')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto total de la transacción/venta', max_digits=12, verbose_name='Monto Bruto')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Comisión neta del proveedor', max_digits=12, verbose_name='Comisión (sin IVA)')),
                ('commission_vat', models.DecimalField(decimal_places=2, help_text='IVA de la comisión (crédito fiscal)', max_digits=12, verbose_name='IVA sobre Comisión')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto que efectivamente se abona: bruto - comisión - IVA', max_digits=12, verbose_name='Monto Neto a Recibir')),
                ('expected_settlement_date', models.DateField(blank=True, help_text='Fecha estimada en que el proveedor abonará a banco', null=True, verbose_name='Fecha Esperada de Abono')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciliado')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciliado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='treasury.bankstatementline', verbose_name='Línea de Extracto Bancario')),
                ('commission_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_daily_commissions', to='accounting.journalentry', verbose_name='Asiento de Comisión Diaria')),
                ('monthly_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='billing.invoice', verbose_name='Factura Mensual')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card_transaction', to='treasury.payment', verbose_name='Pago Asociado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.cardpaymentprovider', verbose_name='Proveedor')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_card_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Reconciliado Por')),
            ],
            options={
                'verbose_name': 'Transacción de Tarjeta',
                'verbose_name_plural': 'Transacciones de Tarjeta',
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['provider', 'is_reconciled'], name='treasury_ca_provide_720e00_idx'), models.Index(fields=['transaction_date'], name='treasury_ca_transac_bea893_idx'), models.Index(fields=['expected_settlement_date'], name='treasury_ca_expecte_7294af_idx'), models.Index(fields=['is_reconciled'], name='treasury_ca_is_reco_aa2a45_idx')],
            },
        ),
    ]
