# Generated by Django 5.2.12 on 2026-04-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0014_backfill_settlement_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltreasuryaccount',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='historicaltreasuryaccount',
            name='is_physical',
        ),
        migrations.RemoveField(
            model_name='historicaltreasuryaccount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='is_physical',
        ),
        migrations.RemoveField(
            model_name='treasuryaccount',
            name='location',
        ),
    ]
