# Generated by Django 5.2.10 on 2026-02-02 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_accountingsettings_bank_commission_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('treasury', '0014_cardpaymentprovider_historicalpayment_card_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField(verbose_name='Fecha de Abono')),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Bruto')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Comisiones')),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total IVA')),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Neto Abonado')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciliado')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Abono Diario Tarjetas',
                'verbose_name_plural': 'Abonos Diarios Tarjetas',
            },
        ),
        migrations.RemoveField(
            model_name='historicalcardpaymentprovider',
            name='commission_bridge_account',
        ),
        migrations.RemoveField(
            model_name='historicalcardpaymentprovider',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcardpaymentprovider',
            name='receivable_account',
        ),
        migrations.RemoveField(
            model_name='historicalcardpaymentprovider',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='bank_statement_line',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='commission_journal_entry',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='monthly_invoice',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='historicalcardtransaction',
            name='reconciled_by',
        ),
        migrations.AlterModelOptions(
            name='cardpaymentprovider',
            options={'verbose_name': 'Proveedor de Pagos con Tarjeta', 'verbose_name_plural': 'Proveedores de Pagos con Tarjeta'},
        ),
        migrations.AlterModelOptions(
            name='cardtransaction',
            options={'verbose_name': 'Transacción de Tarjeta', 'verbose_name_plural': 'Transacciones de Tarjeta'},
        ),
        migrations.RemoveIndex(
            model_name='cardtransaction',
            name='treasury_ca_provide_720e00_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardtransaction',
            name='treasury_ca_transac_bea893_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardtransaction',
            name='treasury_ca_expecte_7294af_idx',
        ),
        migrations.RemoveIndex(
            model_name='cardtransaction',
            name='treasury_ca_is_reco_aa2a45_idx',
        ),
        migrations.RemoveField(
            model_name='cardpaymentprovider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cardpaymentprovider',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='card_last_digits',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='cardtransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='card_receivable_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta donde se registran las ventas bruto (ej: Transbank por Cobrar)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_card_receivables', to='accounting.account', verbose_name='Cuenta Puente Tarjetas (Bruto)'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=2.95, max_digits=5, verbose_name='Tasa de Comisión (%)'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Fijo'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='receivable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_provider_receivables', to='accounting.account', verbose_name='Cuenta Tarjetas por Cobrar'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='settlement_delay_days',
            field=models.IntegerField(default=1, verbose_name='Días de Retraso de Abono'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='card_providers', to='contacts.contact', verbose_name='Proveedor (Contacto)'),
        ),
        migrations.AlterField(
            model_name='cardpaymentprovider',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='Tasa de IVA (%)'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='treasury.bankstatementline'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='commission_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_daily_commissions', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='commission_vat',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='expected_settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='monthly_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto neto a recibir = bruto - comisión - IVA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card_transaction', to='treasury.payment'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.cardpaymentprovider'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='card_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_settlements', to='treasury.bankstatementline'),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='monthly_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_settlements', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='treasury.cardpaymentprovider'),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='daily_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='treasury.dailysettlement'),
        ),
        migrations.DeleteModel(
            name='HistoricalCardPaymentProvider',
        ),
        migrations.DeleteModel(
            name='HistoricalCardTransaction',
        ),
    ]
