# Generated by Django 5.2.10 on 2026-02-02 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0015_dailysettlement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'ordering': ['-statement_date', '-id'], 'verbose_name': 'Cartola Bancaria', 'verbose_name_plural': 'Cartolas Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='bankstatementline',
            options={'ordering': ['statement', 'line_number'], 'verbose_name': 'Línea de Cartola', 'verbose_name_plural': 'Líneas de Cartola'},
        ),
        migrations.AlterModelOptions(
            name='historicalbankstatement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cartola Bancaria', 'verbose_name_plural': 'historical Cartolas Bancarias'},
        ),
        migrations.AlterModelOptions(
            name='historicalbankstatementline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Línea de Cartola', 'verbose_name_plural': 'historical Líneas de Cartola'},
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='statement_date',
            field=models.DateField(verbose_name='Fecha de la Cartola'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury.bankstatement', verbose_name='Cartola'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatement',
            name='statement_date',
            field=models.DateField(verbose_name='Fecha de la Cartola'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='statement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatement', verbose_name='Cartola'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de Cartola Bancaria'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.bankstatementline', verbose_name='Línea de Cartola Bancaria'),
        ),
    ]
