# Generated by Django 5.2.10 on 2026-02-02 04:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_accountingsettings_card_commission_account'),
        ('treasury', '0016_alter_bankstatement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPOSSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSING', 'En Cierre'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(blank=True, editable=False, verbose_name='Abierta el')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Monto de efectivo declarado al abrir la caja', max_digits=12, verbose_name='Fondo de Caja Inicial')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada el')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Efectivo')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Tarjeta')),
                ('total_transfer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Transferencia')),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Crédito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada Por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta de tesorería (caja) asociada a esta sesión', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Caja')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'historical Sesión de Caja',
                'verbose_name_plural': 'historical Sesiones de Caja',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSING', 'En Cierre'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Abierta el')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Monto de efectivo declarado al abrir la caja', max_digits=12, verbose_name='Fondo de Caja Inicial')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada el')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Efectivo')),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Tarjeta')),
                ('total_transfer_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Transferencia')),
                ('total_credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas Crédito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada Por')),
                ('treasury_account', models.ForeignKey(help_text='Cuenta de tesorería (caja) asociada a esta sesión', on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='treasury.treasuryaccount', verbose_name='Caja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSessionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=2, help_text='Monto calculado por el sistema (fondo + ventas efectivo)', max_digits=12, verbose_name='Monto Esperado')),
                ('actual_amount', models.DecimalField(decimal_places=2, help_text='Monto físico contado por el cajero', max_digits=12, verbose_name='Monto Contado')),
                ('difference', models.DecimalField(decimal_places=2, help_text='Diferencia: actual - esperado (+ sobrante, - faltante)', max_digits=12, verbose_name='Diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del Arqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_session_audit', to='accounting.journalentry', verbose_name='Asiento de Ajuste')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='treasury.possession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
            },
        ),
    ]
