# Generated by Django 5.2.10 on 2026-02-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0017_pos_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='pos_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possession', verbose_name='Sesión de Caja'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pos_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.possession', verbose_name='Sesión de Caja'),
        ),
    ]
