# Generated by Django 5.2.13 on 2026-04-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0017_remove_paymentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo Directo'), ('CARD', 'Tarjeta (Manual)'), ('DEBIT_CARD', 'Tarjeta Débito Empresa'), ('CREDIT_CARD', 'Tarjeta Crédito Empresa'), ('CARD_TERMINAL', 'Tarjeta (Terminal POS Integrado)'), ('TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
        migrations.AlterField(
            model_name='historicaltreasuryaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Cuenta Bancaria (Corriente/Vista)'), ('CREDIT_CARD', 'Tarjeta de Crédito (Cta. Propia)'), ('DEBIT_CARD', 'Tarjeta de Débito (Cta. Propia)'), ('CHECKBOOK', 'Chequera / Instrumentos'), ('CASH', 'Caja Física (Efectivo)'), ('BRIDGE', 'Cuenta Puente (Liquidación/Clearing)'), ('MERCHANT', 'Cuenta Recaudadora (Pasarela/Wallet)')], default='CASH', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo Directo'), ('CARD', 'Tarjeta (Manual)'), ('DEBIT_CARD', 'Tarjeta Débito Empresa'), ('CREDIT_CARD', 'Tarjeta Crédito Empresa'), ('CARD_TERMINAL', 'Tarjeta (Terminal POS Integrado)'), ('TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Cuenta Bancaria (Corriente/Vista)'), ('CREDIT_CARD', 'Tarjeta de Crédito (Cta. Propia)'), ('DEBIT_CARD', 'Tarjeta de Débito (Cta. Propia)'), ('CHECKBOOK', 'Chequera / Instrumentos'), ('CASH', 'Caja Física (Efectivo)'), ('BRIDGE', 'Cuenta Puente (Liquidación/Clearing)'), ('MERCHANT', 'Cuenta Recaudadora (Pasarela/Wallet)')], default='CASH', max_length=20, verbose_name='Tipo'),
        ),
    ]
