# Generated by Django 5.2.10 on 2026-02-03 18:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0018_add_pos_session_to_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPOSTerminal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: 'Caja 1', 'Mostrador Principal', 'Terminal Móvil'", max_length=100, verbose_name='Nombre del Terminal')),
                ('code', models.CharField(db_index=True, help_text='Identificador único del terminal', max_length=20, verbose_name='Código')),
                ('location', models.CharField(blank=True, help_text='Ubicación física del terminal', max_length=200, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('allowed_payment_methods', models.JSONField(default=list, help_text="Lista de métodos permitidos: ['CASH', 'CARD', 'TRANSFER']", verbose_name='Métodos de Pago Permitidos')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('default_treasury_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta donde se registran las operaciones de este terminal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería por Defecto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Terminal POS',
                'verbose_name_plural': 'historical Terminales POS',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: 'Caja 1', 'Mostrador Principal', 'Terminal Móvil'", max_length=100, verbose_name='Nombre del Terminal')),
                ('code', models.CharField(help_text='Identificador único del terminal', max_length=20, unique=True, verbose_name='Código')),
                ('location', models.CharField(blank=True, help_text='Ubicación física del terminal', max_length=200, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('allowed_payment_methods', models.JSONField(default=list, help_text="Lista de métodos permitidos: ['CASH', 'CARD', 'TRANSFER']", verbose_name='Métodos de Pago Permitidos')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_treasury_account', models.ForeignKey(help_text='Cuenta donde se registran las operaciones de este terminal', on_delete=django.db.models.deletion.PROTECT, related_name='default_for_terminals', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería por Defecto')),
            ],
            options={
                'verbose_name': 'Terminal POS',
                'verbose_name_plural': 'Terminales POS',
                'ordering': ['code'],
            },
        ),
    ]
