# Generated by Django 5.2.10 on 2026-02-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0019_historicalposterminal_posterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpossession',
            name='terminal',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Terminal donde se realizó esta sesión', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.posterminal', verbose_name='Terminal POS'),
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal donde se realizó esta sesión', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='treasury.posterminal', verbose_name='Terminal POS'),
        ),
        migrations.AlterField(
            model_name='historicalpossession',
            name='treasury_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED: Use terminal.default_treasury_account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Caja (Legacy)'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='treasury_account',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use terminal.default_treasury_account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='treasury.treasuryaccount', verbose_name='Caja (Legacy)'),
        ),
    ]
