# Generated by Django 5.2.10 on 2026-02-03 18:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_add_pos_diff_accounts'),
        ('treasury', '0020_historicalpossession_terminal_possession_terminal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possessionaudit',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='True si la diferencia excede el umbral de aprobación', verbose_name='Requiere Aprobación'),
        ),
        migrations.CreateModel(
            name='CashContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('container_type', models.CharField(choices=[('SAFE', 'Caja Fuerte'), ('PETTY_CASH', 'Caja Menor'), ('CHANGE_FUND', 'Fondo de Cambio'), ('TILL', 'Gaveta/Caja Registradora')], max_length=20, verbose_name='Tipo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo físico actual en el contenedor', max_digits=12, verbose_name='Saldo Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cash_containers', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('treasury_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_containers', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería Asociada')),
            ],
            options={
                'verbose_name': 'Contenedor de Efectivo',
                'verbose_name_plural': 'Contenedores de Efectivo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='+ para sobrante, - para faltante', max_digits=12, verbose_name='Monto')),
                ('reason', models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Revisión'), ('APPROVED', 'Aprobada'), ('DISPUTED', 'En Disputa'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reportado el')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('reporter_notes', models.TextField(blank=True, verbose_name='Notas del Reportante')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_differences', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_difference', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('pos_session_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='treasury.possessionaudit', verbose_name='Arqueo Asociado')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_differences', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'verbose_name': 'Diferencia de Efectivo',
                'verbose_name_plural': 'Diferencias de Efectivo',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Transferencia'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='CONFIRMED', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('from_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='treasury.cashcontainer', verbose_name='Desde Contenedor')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('pos_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='treasury.possession', verbose_name='Sesión POS Relacionada')),
                ('to_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='treasury.cashcontainer', verbose_name='Hacia Contenedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Efectivo',
                'verbose_name_plural': 'Movimientos de Efectivo',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCashContainer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('container_type', models.CharField(choices=[('SAFE', 'Caja Fuerte'), ('PETTY_CASH', 'Caja Menor'), ('CHANGE_FUND', 'Fondo de Cambio'), ('TILL', 'Gaveta/Caja Registradora')], max_length=20, verbose_name='Tipo')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Saldo físico actual en el contenedor', max_digits=12, verbose_name='Saldo Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('custodian', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería Asociada')),
            ],
            options={
                'verbose_name': 'historical Contenedor de Efectivo',
                'verbose_name_plural': 'historical Contenedores de Efectivo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashDifference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='+ para sobrante, - para faltante', max_digits=12, verbose_name='Monto')),
                ('reason', models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Revisión'), ('APPROVED', 'Aprobada'), ('DISPUTED', 'En Disputa'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('reported_at', models.DateTimeField(blank=True, editable=False, verbose_name='Reportado el')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Notas de Aprobación')),
                ('reporter_notes', models.TextField(blank=True, verbose_name='Notas del Reportante')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('pos_session_audit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possessionaudit', verbose_name='Arqueo Asociado')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'verbose_name': 'historical Diferencia de Efectivo',
                'verbose_name_plural': 'historical Diferencias de Efectivo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCashMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Transferencia'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='CONFIRMED', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('from_container', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cashcontainer', verbose_name='Desde Contenedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento Contable')),
                ('pos_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possession', verbose_name='Sesión POS Relacionada')),
                ('to_container', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cashcontainer', verbose_name='Hacia Contenedor')),
            ],
            options={
                'verbose_name': 'historical Movimiento de Efectivo',
                'verbose_name_plural': 'historical Movimientos de Efectivo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
