# Generated by Django 5.2.13 on 2026-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_add_tax_withholding_account'),
        ('treasury', '0020_rule_success_rate_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmatch',
            name='transfer_journal_entries',
            field=models.ManyToManyField(blank=True, related_name='reconciliation_matches_transfers', to='accounting.journalentry', verbose_name='Asientos de Transferencia'),
        ),
    ]
