# Generated by Django 5.2.13 on 2026-04-28 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingsettings_auto_post_reconciliation_adjustments'),
        ('billing', '0007_alter_historicalinvoice_dte_type_and_more'),
        ('contacts', '0007_contact_partner_dividends_payable_account_and_more'),
        ('hr', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0005_payment_method_ref'),
        ('treasury', '0021_reconciliationmatch_transfer_journal_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['from_account', 'date', 'is_reconciled'], name='idx_movement_from_date_recon'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['to_account', 'date', 'is_reconciled'], name='idx_movement_to_date_recon'),
        ),
    ]
