# Generated by Django 5.2.10 on 2026-02-03 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0021_possessionaudit_requires_approval_cashcontainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovement',
            name='to_container',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='from_container',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='to_container',
        ),
        migrations.RemoveField(
            model_name='cashmovement',
            name='from_container',
        ),
        migrations.RemoveField(
            model_name='historicalcashcontainer',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='historicalcashcontainer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcashcontainer',
            name='treasury_account',
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='treasury.treasuryaccount', verbose_name='Desde Cuenta'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta'),
        ),
        migrations.AddField(
            model_name='historicalcashmovement',
            name='from_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Desde Cuenta'),
        ),
        migrations.AddField(
            model_name='historicalcashmovement',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_of_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Custodio'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='is_physical',
            field=models.BooleanField(default=False, help_text='Marcar si esta cuenta representa un lugar físico de almacenamiento de dinero', verbose_name='Es Contenedor Físico'),
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación física (ej: Caja Fuerte Principal, Gaveta 1)', max_length=200, verbose_name='Ubicación'),
        ),
        migrations.DeleteModel(
            name='CashContainer',
        ),
        migrations.DeleteModel(
            name='HistoricalCashContainer',
        ),
    ]
