# Generated by Django 5.2.10 on 2026-02-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0023_pos_terminal_multiple_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalposterminal',
            name='allowed_treasury_accounts',
        ),
        migrations.AddField(
            model_name='historicalpossession',
            name='total_other_cash_inflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Ingresos Efectivo'),
        ),
        migrations.AddField(
            model_name='historicalpossession',
            name='total_other_cash_outflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egresos Efectivo'),
        ),
        migrations.AddField(
            model_name='possession',
            name='total_other_cash_inflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Ingresos Efectivo'),
        ),
        migrations.AddField(
            model_name='possession',
            name='total_other_cash_outflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Egresos Efectivo'),
        ),
    ]
