# Generated by Django 5.2.11 on 2026-02-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0025_alter_cashdifference_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdifference',
            name='reason',
            field=models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Transferencia'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='historicalcashdifference',
            name='reason',
            field=models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Transferencia'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón'),
        ),
    ]
