# Generated by Django 5.2.11 on 2026-02-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0026_alter_cashdifference_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdifference',
            name='transfer_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasuryaccount', verbose_name='Cuenta de Destino (Transferencia)'),
        ),
        migrations.AddField(
            model_name='historicalcashdifference',
            name='transfer_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Destino (Transferencia)'),
        ),
    ]
