# Generated by Django 5.2.11 on 2026-02-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0027_cashdifference_transfer_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdifference',
            name='reason',
            field=models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='cashdifference',
            name='transfer_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.treasuryaccount', verbose_name='Cuenta de Destino (Traspaso)'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Traspaso de Efectivo'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalcashdifference',
            name='reason',
            field=models.CharField(choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=20, verbose_name='Razón'),
        ),
        migrations.AlterField(
            model_name='historicalcashdifference',
            name='transfer_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Destino (Traspaso)'),
        ),
        migrations.AlterField(
            model_name='historicalcashmovement',
            name='movement_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Traspaso de Efectivo'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='allows_transfer',
            field=models.BooleanField(default=False, verbose_name='Permite Traspaso'),
        ),
    ]
