# Generated by Django 5.2.13 on 2026-04-29 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_historicalinvoice_dte_type_and_more'),
        ('purchasing', '0001_initial'),
        ('sales', '0005_payment_method_ref'),
        ('treasury', '0028_paymentallocation_s51'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpaymentallocation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Distribución de Pago', 'verbose_name_plural': 'historical Distribuciones de Pago'},
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de Cartola'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='purchase_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder', verbose_name='Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='Orden de Venta'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='treasury_movement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Tesorería'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
