# Generated by Django 5.2.10 on 2026-02-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0028_alter_cashdifference_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Traspaso de Efectivo'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste'), ('SALE', 'Venta'), ('EXPENSE', 'Gasto/Compra')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalcashmovement',
            name='movement_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Retiro'), ('TRANSFER', 'Traspaso de Efectivo'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('ADJUSTMENT', 'Ajuste'), ('SALE', 'Venta'), ('EXPENSE', 'Gasto/Compra')], max_length=20, verbose_name='Tipo'),
        ),
    ]
