# Generated by Django 5.2.13 on 2026-04-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0030_migrate_legacy_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatementline',
            name='matched_payment',
        ),
        migrations.RemoveField(
            model_name='historicalbankstatementline',
            name='matched_payment',
        ),
    ]
