# Generated by Django 5.2.11 on 2026-02-06 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0030_add_payment_cashmovement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcashmovement',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vincula este movimiento a un pago a terceros', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.payment', verbose_name='Pago Asociado'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='cash_movement',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vincula este pago a un movimiento físico de efectivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cashmovement', verbose_name='Movimiento de Efectivo Asociado'),
        ),
    ]
