# Generated by Django 5.2.10 on 2026-02-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0031_historicalcashmovement_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='justify_reason',
            field=models.CharField(choices=[('CAPITAL_CONTRIBUTION', 'Aporte de Capital'), ('PURCHASE_REFUND', 'Devolución de Compra'), ('TIP', 'Propina'), ('EXPENSE', 'Gasto / Caja Chica'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('SUPPLIER_PAYMENT', 'Pago a Proveedor'), ('THEFT', 'Robo / Faltante'), ('ROUNDING', 'Redondeo'), ('CASHBACK', 'Vuelto Incorrecto'), ('COUNTING_ERROR', 'Error de Conteo'), ('SYSTEM_ERROR', 'Error de Sistema'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=30, verbose_name='Razón / Motivo'),
        ),
        migrations.AddField(
            model_name='historicalcashmovement',
            name='justify_reason',
            field=models.CharField(choices=[('CAPITAL_CONTRIBUTION', 'Aporte de Capital'), ('PURCHASE_REFUND', 'Devolución de Compra'), ('TIP', 'Propina'), ('EXPENSE', 'Gasto / Caja Chica'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('SUPPLIER_PAYMENT', 'Pago a Proveedor'), ('THEFT', 'Robo / Faltante'), ('ROUNDING', 'Redondeo'), ('CASHBACK', 'Vuelto Incorrecto'), ('COUNTING_ERROR', 'Error de Conteo'), ('SYSTEM_ERROR', 'Error de Sistema'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=30, verbose_name='Razón / Motivo'),
        ),
    ]
