# Generated by Django 5.2.10 on 2026-02-07 15:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingsettings_pos_cashback_error_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('purchasing', '0020_add_related_note_to_lines'),
        ('sales', '0028_draftcart_wizard_state'),
        ('treasury', '0032_cashmovement_justify_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='TreasuryMovement',
        ),
        migrations.RenameModel(
            old_name='HistoricalPayment',
            new_name='HistoricalTreasuryMovement',
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_accounts', to='treasury.bank', verbose_name='Banco'),
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banco',
                'verbose_name_plural': 'historical Bancos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_reference', models.BooleanField(default=False, verbose_name='Requiere Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_reference', models.BooleanField(default=False, verbose_name='Requiere Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'historical Método de Pago',
                'verbose_name_plural': 'historical Métodos de Pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        # Add the transition fields and adjust others
        migrations.AddField(
            model_name='treasurymovement',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo', default='INBOUND'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo', default='INBOUND'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='payment_method_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.paymentmethod', verbose_name='Método de Pago (Nuevo)'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='payment_method_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentmethod', verbose_name='Método de Pago (Nuevo)'),
        ),
        # Remove legacy things that might conflict
        migrations.RemoveField(
            model_name='treasurymovement',
            name='cash_movement',
        ),
        migrations.RemoveField(
            model_name='historicaltreasurymovement',
            name='cash_movement',
        ),
        # Rename original options of TreasuryMovement (since it was renamed from Payment)
        migrations.AlterModelOptions(
            name='treasurymovement',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Movimiento de Tesorería', 'verbose_name_plural': 'Movimientos de Tesorería'},
        ),
        migrations.AlterModelOptions(
            name='historicaltreasurymovement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Movimiento de Tesorería', 'verbose_name_plural': 'historical Movimientos de Tesorería'},
        ),
        # Now we can safely delete CashMovement as it's been consolidated
        migrations.DeleteModel(
            name='CashMovement',
        ),
        migrations.DeleteModel(
            name='HistoricalCashMovement',
        ),
    ]
