# Generated by Django 5.2.10 on 2026-02-07 15:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingsettings_pos_cashback_error_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('purchasing', '0020_add_related_note_to_lines'),
        ('sales', '0028_draftcart_wizard_state'),
        ('treasury', '0032_cashmovement_justify_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cash_movement',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='cash_movement',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='pos_session',
        ),
        migrations.RemoveField(
            model_name='historicalcashmovement',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='bank_statement_line',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='card_provider',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='pos_session',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='reconciliation_match',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='treasury_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_statement_line',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_provider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pos_session',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reconciliation_match',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sale_order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='treasury_account',
        ),
        migrations.AddField(
            model_name='treasuryaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_accounts', to='treasury.bank', verbose_name='Banco'),
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Banco',
                'verbose_name_plural': 'historical Bancos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_reference', models.BooleanField(default=False, verbose_name='Requiere Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'historical Método de Pago',
                'verbose_name_plural': 'historical Métodos de Pago',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('method_type', models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_reference', models.BooleanField(default=False, verbose_name='Requiere Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTreasuryMovement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Transacción')),
                ('is_pending_registration', models.BooleanField(default=False, verbose_name='Transacción Pendiente de Registro')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciliado')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reconciliación')),
                ('justify_reason', models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Contable (Snapshot)')),
                ('bank_statement_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de Cartola Bancaria')),
                ('card_provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta')),
                ('contact', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('from_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Desde Cuenta (Origen)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('pos_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possession', verbose_name='Sesión de Caja')),
                ('purchase_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='purchasing.purchaseorder')),
                ('reconciled_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reconciliado Por')),
                ('reconciliation_match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder')),
                ('to_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta (Destino)')),
                ('payment_method_new', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentmethod', verbose_name='Método de Pago (Nuevo)')),
            ],
            options={
                'verbose_name': 'historical Movimiento de Tesorería',
                'verbose_name_plural': 'historical Movimientos de Tesorería',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TreasuryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Transacción')),
                ('is_pending_registration', models.BooleanField(default=False, verbose_name='Transacción Pendiente de Registro')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='Reconciliado')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Reconciliación')),
                ('justify_reason', models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='accounting.account', verbose_name='Cuenta Contable (Snapshot)')),
                ('bank_statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_movements', to='treasury.bankstatementline', verbose_name='Línea de Cartola Bancaria')),
                ('card_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='treasury.treasuryaccount', verbose_name='Desde Cuenta (Origen)')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movement', to='accounting.journalentry')),
                ('payment_method_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.paymentmethod', verbose_name='Método de Pago (Nuevo)')),
                ('pos_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.possession', verbose_name='Sesión de Caja')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchasing.purchaseorder')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_movements', to=settings.AUTH_USER_MODEL, verbose_name='Reconciliado Por')),
                ('reconciliation_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.saleorder')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta (Destino)')),
            ],
            options={
                'verbose_name': 'Movimiento de Tesorería',
                'verbose_name_plural': 'Movimientos de Tesorería',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_lines', to='treasury.treasurymovement', verbose_name='Movimiento Matched'),
        ),
        migrations.AlterField(
            model_name='cardtransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card_transaction', to='treasury.treasurymovement'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento Matched'),
        ),
        migrations.DeleteModel(
            name='CashMovement',
        ),
        migrations.DeleteModel(
            name='HistoricalCashMovement',
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['from_account', 'date'], name='treasury_tr_from_ac_e15586_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['to_account', 'date'], name='treasury_tr_to_acco_415795_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['is_reconciled'], name='treasury_tr_is_reco_e3051a_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['transaction_number'], name='treasury_tr_transac_015b55_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['reference'], name='treasury_tr_referen_a9e09f_idx'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
