# Generated by Django 5.2.13 on 2026-04-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0032_make_reconciliationmatch_createdby_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='reconciled_lines',
        ),
        migrations.RemoveField(
            model_name='historicalbankstatement',
            name='reconciled_lines',
        ),
    ]
