# Generated by Django 5.2.13 on 2026-05-03 03:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def create_initial_settings(apps, schema_editor):
    TreasuryAccount = apps.get_model('treasury', 'TreasuryAccount')
    ReconciliationSettings = apps.get_model('treasury', 'ReconciliationSettings')
    for account in TreasuryAccount.objects.all():
        ReconciliationSettings.objects.get_or_create(treasury_account=account)


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0033_remove_bankstatement_reconciled_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReconciliationSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount_weight', models.IntegerField(default=40, verbose_name='Peso del Monto')),
                ('date_weight', models.IntegerField(default=30, verbose_name='Peso de la Fecha')),
                ('reference_weight', models.IntegerField(default=20, verbose_name='Peso de la Referencia')),
                ('contact_weight', models.IntegerField(default=10, verbose_name='Peso del Contacto')),
                ('confidence_threshold', models.IntegerField(default=90, help_text='Puntaje mínimo para sugerir o auto-conciliar (0-100)', verbose_name='Umbral de Confianza')),
                ('date_range_days', models.IntegerField(default=30, help_text='Días hacia atrás/adelante para buscar candidatos', verbose_name='Rango de Búsqueda (Días)')),
                ('auto_confirm', models.BooleanField(default=False, help_text='Si es True, el sistema concilia automáticamente sobre el umbral de confianza', verbose_name='Auto-confirmar')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treasury_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'historical Configuración de Conciliación',
                'verbose_name_plural': 'historical Configuraciones de Conciliación',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReconciliationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_weight', models.IntegerField(default=40, verbose_name='Peso del Monto')),
                ('date_weight', models.IntegerField(default=30, verbose_name='Peso de la Fecha')),
                ('reference_weight', models.IntegerField(default=20, verbose_name='Peso de la Referencia')),
                ('contact_weight', models.IntegerField(default=10, verbose_name='Peso del Contacto')),
                ('confidence_threshold', models.IntegerField(default=90, help_text='Puntaje mínimo para sugerir o auto-conciliar (0-100)', verbose_name='Umbral de Confianza')),
                ('date_range_days', models.IntegerField(default=30, help_text='Días hacia atrás/adelante para buscar candidatos', verbose_name='Rango de Búsqueda (Días)')),
                ('auto_confirm', models.BooleanField(default=False, help_text='Si es True, el sistema concilia automáticamente sobre el umbral de confianza', verbose_name='Auto-confirmar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('treasury_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_settings', to='treasury.treasuryaccount', verbose_name='Cuenta de Tesorería')),
            ],
            options={
                'verbose_name': 'Configuración de Conciliación',
                'verbose_name_plural': 'Configuraciones de Conciliación',
            },
        ),
        migrations.RunPython(create_initial_settings),
    ]
