# Generated by Django 5.2.10 on 2026-02-07 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingsettings_pos_cashback_error_account_and_more'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('purchasing', '0020_add_related_note_to_lines'),
        ('sales', '0028_draftcart_wizard_state'),
        ('treasury', '0033_unified_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='treasurymovement',
            name='treasury_pa_treasur_eae50d_idx',
        ),
        migrations.RemoveIndex(
            model_name='treasurymovement',
            name='treasury_pa_amount_3c0a68_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='treasury_tr_is_reco_e3051a_idx',
            old_name='treasury_pa_is_reco_e514c4_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='treasury_tr_transac_015b55_idx',
            old_name='treasury_pa_transac_1fe75f_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurymovement',
            new_name='treasury_tr_referen_a9e09f_idx',
            old_name='treasury_pa_referen_1e55e5_idx',
        ),
        migrations.RemoveField(
            model_name='historicaltreasurymovement',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='historicaltreasurymovement',
            name='treasury_account',
        ),
        migrations.RemoveField(
            model_name='treasurymovement',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='treasurymovement',
            name='treasury_account',
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='from_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Desde Cuenta (Origen)'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='justify_reason',
            field=models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='to_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta (Destino)'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='treasury.treasuryaccount', verbose_name='Desde Cuenta (Origen)'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='justify_reason',
            field=models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='treasury.treasuryaccount', verbose_name='Hacia Cuenta (Destino)'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_lines', to='treasury.treasurymovement', verbose_name='Movimiento Matched'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='matched_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED: Use reconciliation_match instead', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento Matched'),
        ),
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='accounting.account', verbose_name='Cuenta Contable (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_movements', to='treasury.bankstatementline', verbose_name='Línea de Cartola Bancaria'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='card_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movement', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='movement_type',
            field=models.CharField(choices=[('INBOUND', 'Entrante (Cobro/Venta)'), ('OUTBOUND', 'Saliente (Pago/Gasto)'), ('TRANSFER', 'Traspaso Interno'), ('ADJUSTMENT', 'Ajuste')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='pos_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.possession', verbose_name='Sesión de Caja'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_movements', to=settings.AUTH_USER_MODEL, verbose_name='Reconciliado Por'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='reconciliation_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['from_account', 'date'], name='treasury_tr_from_ac_e15586_idx'),
        ),
        migrations.AddIndex(
            model_name='treasurymovement',
            index=models.Index(fields=['to_account', 'date'], name='treasury_tr_to_acco_415795_idx'),
        ),
    ]
