# Generated by Django 5.2.13 on 2026-05-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0034_historicalreconciliationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reconciliationrule',
            name='treasury_account',
        ),
        migrations.DeleteModel(
            name='HistoricalReconciliationRule',
        ),
        migrations.DeleteModel(
            name='ReconciliationRule',
        ),
    ]
