# Generated by Django 5.2.10 on 2026-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0034_cleanup_and_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='allow_for_purchases',
            field=models.BooleanField(default=True, verbose_name='Permitir en Compras'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='allow_for_sales',
            field=models.BooleanField(default=True, verbose_name='Permitir en Ventas'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='allow_for_purchases',
            field=models.BooleanField(default=True, verbose_name='Permitir en Compras'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='allow_for_sales',
            field=models.BooleanField(default=True, verbose_name='Permitir en Ventas'),
        ),
    ]
