# Generated by Django 5.2.10 on 2026-02-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0038_expand_account_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbank',
            name='swift_code',
            field=models.CharField(blank=True, help_text='Código internacional para transferencias', max_length=11, null=True, verbose_name='Código SWIFT/BIC'),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='allowed_payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Métodos de pago específicos permitidos en este terminal', related_name='pos_terminals', to='treasury.paymentmethod', verbose_name='Métodos de Pago Permitidos'),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='allowed_treasury_accounts',
            field=models.ManyToManyField(blank=True, help_text='DEPRECATED: Use allowed_payment_methods instead', related_name='pos_terminals', to='treasury.treasuryaccount', verbose_name='Cuentas de Tesorería (Legacy)'),
        ),
    ]
