# Generated by Antigravity manual migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0039_terminalbatch_sales_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposterminal',
            name='payment_terminal_device',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dispositivo físico vinculado a esta caja para cobros integrados', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentterminaldevice', verbose_name='Dispositivo de Terminal'),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='payment_terminal_device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo físico vinculado a esta caja para cobros integrados', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='treasury.paymentterminaldevice', verbose_name='Dispositivo de Terminal'),
        ),
    ]
