# Generated by Django 5.2.10 on 2026-02-08 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0039_historicalbank_swift_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='card_provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='treasury.cardpaymentprovider', verbose_name='Proveedor de Tarjeta'),
        ),
    ]
