# Generated by Django 5.2.10 on 2026-02-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0040_historicalpaymentmethod_card_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='is_terminal',
            field=models.BooleanField(default=False, help_text='Indica si es un terminal de terceros (Transbank, etc.) para recaudar ventas. Si es Falso, se considera un medio de pago de la empresa (Caja, Tarjeta Propia, etc.).', verbose_name='Es Terminal de Cobro'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_terminal',
            field=models.BooleanField(default=False, help_text='Indica si es un terminal de terceros (Transbank, etc.) para recaudar ventas. Si es Falso, se considera un medio de pago de la empresa (Caja, Tarjeta Propia, etc.).', verbose_name='Es Terminal de Cobro'),
        ),
    ]
