# Generated by Django 5.2.10 on 2026-02-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0041_historicalpaymentmethod_is_terminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('CARD_TERMINAL', 'Terminal de Cobros (Transbank/Otros)'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('CARD_TERMINAL', 'Terminal de Cobros (Transbank/Otros)'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque'), ('CREDIT_LINE', 'Línea de Crédito'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Método'),
        ),
    ]
