# Generated by Django 5.2.10 on 2026-02-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0042_alter_historicalpaymentmethod_method_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('CARD_TERMINAL', 'Terminal de Cobros'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('CARD_TERMINAL', 'Terminal de Cobros'), ('TRANSFER', 'Transferencia'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
    ]
