# Generated by Django 5.2.14 on 2026-05-08 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0043_reconciliationsettings_timestampedmodel_t14'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreconciliationsettings',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 5, 8, 0, 17, 36, 285335, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Creado el'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo Directo'), ('CARD', 'Tarjeta (Manual)'), ('DEBIT_CARD', 'Tarjeta Débito Empresa'), ('CREDIT_CARD', 'Tarjeta Crédito Empresa'), ('CARD_TERMINAL', 'Tarjeta (Terminal POS Integrado)'), ('TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
        migrations.AlterField(
            model_name='historicalreconciliationsettings',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Efectivo Directo'), ('CARD', 'Tarjeta (Manual)'), ('DEBIT_CARD', 'Tarjeta Débito Empresa'), ('CREDIT_CARD', 'Tarjeta Crédito Empresa'), ('CARD_TERMINAL', 'Tarjeta (Terminal POS Integrado)'), ('TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque')], max_length=20, verbose_name='Tipo de Método'),
        ),
    ]
