# Generated by Django 5.2.10 on 2026-02-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0043_alter_historicalpaymentmethod_method_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryaccount',
            name='allows_check',
            field=models.BooleanField(default=False, verbose_name='Permite Cheque'),
        ),
    ]
