# Generated by Django 5.2.11 on 2026-02-09 00:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_accountingsettings_pos_cashback_error_account_and_more'),
        ('treasury', '0044_treasuryaccount_allows_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTreasuryAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('currency', models.CharField(default='CLP', max_length=3, verbose_name='Moneda')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Cuenta Corriente'), ('CREDIT_CARD', 'Tarjeta de Crédito'), ('DEBIT_CARD', 'Tarjeta de Débito'), ('CHECKBOOK', 'Chequera'), ('CASH', 'Efectivo')], default='CASH', max_length=20, verbose_name='Tipo')),
                ('account_number', models.CharField(blank=True, help_text='Número de cuenta bancaria (solo para cuentas corrientes)', max_length=50, null=True, verbose_name='N° de Cuenta Bancaria')),
                ('allows_cash', models.BooleanField(default=False, verbose_name='Permite Efectivo')),
                ('allows_card', models.BooleanField(default=False, verbose_name='Permite Tarjeta')),
                ('allows_transfer', models.BooleanField(default=False, verbose_name='Permite Traspaso')),
                ('allows_check', models.BooleanField(default=False, verbose_name='Permite Cheque')),
                ('location', models.CharField(blank=True, help_text='Ubicación física (ej: Caja Fuerte Principal, Gaveta 1)', max_length=200, verbose_name='Ubicación')),
                ('is_physical', models.BooleanField(default=False, help_text='Marcar si esta cuenta representa un lugar físico de almacenamiento de dinero', verbose_name='Es Contenedor Físico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Contable')),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bank', verbose_name='Banco')),
                ('card_receivable_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta donde se registran las ventas bruto (ej: Transbank por Cobrar)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Puente Tarjetas (Bruto)')),
                ('custodian', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable / Custodio')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cuenta de Tesorería',
                'verbose_name_plural': 'historical Cuentas de Tesorería',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
