# Generated by Django 5.2.14 on 2026-05-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('treasury', '0044_historicalreconciliationsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='allocated_content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='allocated_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='allocated_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='allocated_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
