# Generated by Django 5.2.11 on 2026-02-09 18:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_accountingsettings_card_commission_account'),
        ('billing', '0013_noteworkflow'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('treasury', '0045_historicaltreasuryaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='provider',
                ),
                migrations.RemoveField(
                    model_name='treasurymovement',
                    name='card_provider',
                ),
                migrations.RemoveField(
                    model_name='paymentmethod',
                    name='card_provider',
                ),
                migrations.RemoveField(
                    model_name='historicalpaymentmethod',
                    name='card_provider',
                ),
                migrations.RemoveField(
                    model_name='historicaltreasurymovement',
                    name='card_provider',
                ),
                migrations.RemoveField(
                    model_name='dailysettlement',
                    name='provider',
                ),
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='bank_statement_line',
                ),
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='commission_journal_entry',
                ),
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='daily_settlement',
                ),
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='monthly_invoice',
                ),
                migrations.RemoveField(
                    model_name='cardtransaction',
                    name='payment',
                ),
                migrations.RemoveField(
                    model_name='dailysettlement',
                    name='bank_statement_line',
                ),
                migrations.RemoveField(
                    model_name='dailysettlement',
                    name='monthly_invoice',
                ),
                migrations.RemoveField(
                    model_name='historicaltreasuryaccount',
                    name='card_receivable_account',
                ),
                migrations.RemoveField(
                    model_name='treasuryaccount',
                    name='card_receivable_account',
                ),
            ],
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='commission_expense_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Cuenta de gasto donde se registran las comisiones. Ejemplo: '5-1-003 Comisiones Transbank' o '5-1-004 Comisiones Mercado Pago'", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Gasto Comisión'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Proveedor que retiene comisiones (ej: Transbank, Mercado Pago)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor del Terminal'),
        ),
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='terminal_receivable_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Cuenta transitoria donde se registran ventas hasta recibir liquidación. Ejemplo: '1-1-004 Por Cobrar Transbank' o '1-1-005 Por Cobrar Mercado Pago'", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Por Cobrar Terminal'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='commission_expense_account',
            field=models.ForeignKey(blank=True, help_text="Cuenta de gasto donde se registran las comisiones. Ejemplo: '5-1-003 Comisiones Transbank' o '5-1-004 Comisiones Mercado Pago'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_commission_expenses', to='accounting.account', verbose_name='Cuenta Gasto Comisión'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor que retiene comisiones (ej: Transbank, Mercado Pago)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_payment_methods', to='contacts.contact', verbose_name='Proveedor del Terminal'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='terminal_receivable_account',
            field=models.ForeignKey(blank=True, help_text="Cuenta transitoria donde se registran ventas hasta recibir liquidación. Ejemplo: '1-1-004 Por Cobrar Transbank' o '1-1-005 Por Cobrar Mercado Pago'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_receivables', to='accounting.account', verbose_name='Cuenta Por Cobrar Terminal'),
        ),
        migrations.CreateModel(
            name='HistoricalTerminalBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sales_date', models.DateField(help_text='Día en que se realizaron las ventas', verbose_name='Fecha de Ventas')),
                ('settlement_date', models.DateField(help_text='Día en que el terminal informó la comisión', verbose_name='Fecha de Liquidación')),
                ('deposit_date', models.DateField(blank=True, help_text='Día en que llegó el dinero al banco', null=True, verbose_name='Fecha de Depósito')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total de ventas del día', max_digits=12, verbose_name='Monto Bruto')),
                ('commission_base', models.DecimalField(decimal_places=2, help_text='Comisión sin IVA', max_digits=12, verbose_name='Comisión Neta')),
                ('commission_tax', models.DecimalField(decimal_places=2, help_text='IVA sobre la comisión', max_digits=12, verbose_name='IVA Comisión')),
                ('commission_total', models.DecimalField(decimal_places=2, help_text='Comisión + IVA', max_digits=12, verbose_name='Comisión Total')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto que llegó al banco', max_digits=12, verbose_name='Monto Neto Depositado')),
                ('terminal_reference', models.CharField(blank=True, help_text='Número de lote o referencia del terminal', max_length=100, verbose_name='Referencia Terminal')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Liquidación'), ('SETTLED', 'Liquidado'), ('RECONCILED', 'Reconciliado'), ('INVOICED', 'Facturado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_statement_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankstatementline', verbose_name='Línea de Cartola')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.paymentmethod', verbose_name='Método de Pago (Terminal)')),
                ('reconciliation_match', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación')),
                ('settlement_journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry', verbose_name='Asiento de Liquidación')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Proveedor Terminal')),
                ('supplier_invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura Proveedor')),
            ],
            options={
                'verbose_name': 'historical Lote Terminal',
                'verbose_name_plural': 'historical Lotes Terminal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TerminalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateField(help_text='Día en que se realizaron las ventas', verbose_name='Fecha de Ventas')),
                ('settlement_date', models.DateField(help_text='Día en que el terminal informó la comisión', verbose_name='Fecha de Liquidación')),
                ('deposit_date', models.DateField(blank=True, help_text='Día en que llegó el dinero al banco', null=True, verbose_name='Fecha de Depósito')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total de ventas del día', max_digits=12, verbose_name='Monto Bruto')),
                ('commission_base', models.DecimalField(decimal_places=2, help_text='Comisión sin IVA', max_digits=12, verbose_name='Comisión Neta')),
                ('commission_tax', models.DecimalField(decimal_places=2, help_text='IVA sobre la comisión', max_digits=12, verbose_name='IVA Comisión')),
                ('commission_total', models.DecimalField(decimal_places=2, help_text='Comisión + IVA', max_digits=12, verbose_name='Comisión Total')),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto que llegó al banco', max_digits=12, verbose_name='Monto Neto Depositado')),
                ('terminal_reference', models.CharField(blank=True, help_text='Número de lote o referencia del terminal', max_length=100, verbose_name='Referencia Terminal')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente Liquidación'), ('SETTLED', 'Liquidado'), ('RECONCILED', 'Reconciliado'), ('INVOICED', 'Facturado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('bank_statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_batches', to='treasury.bankstatementline', verbose_name='Línea de Cartola')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terminal_batches', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='treasury.paymentmethod', verbose_name='Método de Pago (Terminal)')),
                ('reconciliation_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_batches', to='treasury.reconciliationmatch', verbose_name='Grupo de Conciliación')),
                ('settlement_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_batch_settlements', to='accounting.journalentry', verbose_name='Asiento de Liquidación')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_batches', to='contacts.contact', verbose_name='Proveedor Terminal')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_batches', to='billing.invoice', verbose_name='Factura Proveedor')),
            ],
            options={
                'verbose_name': 'Lote Terminal',
                'verbose_name_plural': 'Lotes Terminal',
                'ordering': ['-sales_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='terminal_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lote al que pertenece este pago (si es terminal)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.terminalbatch', verbose_name='Lote Terminal'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='terminal_batch',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece este pago (si es terminal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='treasury.terminalbatch', verbose_name='Lote Terminal'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='CardPaymentProvider',
                ),
                migrations.DeleteModel(
                    name='CardTransaction',
                ),
                migrations.DeleteModel(
                    name='DailySettlement',
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='terminalbatch',
            index=models.Index(fields=['payment_method', 'sales_date'], name='treasury_te_payment_89882a_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalbatch',
            index=models.Index(fields=['status'], name='treasury_te_status_764a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalbatch',
            index=models.Index(fields=['supplier', 'sales_date'], name='treasury_te_supplie_83b6db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='terminalbatch',
            unique_together={('payment_method', 'sales_date', 'terminal_reference')},
        ),
    ]
