# Generated by Django 5.2.14 on 2026-05-08 02:03

from django.db import migrations

def forwards(apps, schema_editor):
    TreasuryMovement = apps.get_model('treasury', 'TreasuryMovement')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    fields = {
        'invoice': ('billing', 'Invoice'),
        'sale_order': ('sales', 'SaleOrder'),
        'purchase_order': ('purchasing', 'PurchaseOrder'),
        'payroll': ('hr', 'Payroll'),
    }

    for field, (app_label, model_name) in fields.items():
        try:
            ModelClass = apps.get_model(app_label, model_name)
            ct = ContentType.objects.get_for_model(ModelClass)
        except LookupError:
            continue

        query = {f'{field}__isnull': False}
        for tm in TreasuryMovement.objects.filter(**query).iterator():
            if not tm.allocated_content_type_id:
                tm.allocated_content_type_id = ct.id
                tm.allocated_object_id = getattr(tm, f'{field}_id')
                tm.save(update_fields=['allocated_content_type', 'allocated_object_id'])

def backwards(apps, schema_editor):
    TreasuryMovement = apps.get_model('treasury', 'TreasuryMovement')
    TreasuryMovement.objects.update(allocated_content_type=None, allocated_object_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0045_treasury_movement_gfk_allocated'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('billing', '0001_initial'),
        ('sales', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
