# Generated by Django 5.2.10 on 2026-02-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_remove_accountingsettings_card_commission_account'),
        ('treasury', '0046_remove_cardtransaction_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='terminal_vat_bridge_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta transitoria para el IVA de comisiones hasta recibir la factura mensual.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.account', verbose_name='Cuenta Puente IVA Comisión'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='terminal_vat_bridge_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta transitoria para el IVA de comisiones hasta recibir la factura mensual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_vat_bridges', to='accounting.account', verbose_name='Cuenta Puente IVA Comisión'),
        ),
    ]
