# Generated by Django 5.2.10 on 2026-02-11 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0047_historicalpaymentmethod_terminal_vat_bridge_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentmethod',
            name='terminal_vat_bridge_account',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='terminal_vat_bridge_account',
        ),
    ]
