# Generated by Django 6.0.5 on 2026-06-02 16:19

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_fts_gin_index'),
        ('contacts', '0010_contact_roles_historicalcontact_roles'),
        ('sales', '0010_fts_gin_index'),
        ('treasury', '0048_alter_historicaltreasuryaccount_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreasuryaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Cuenta Bancaria (Corriente/Vista)'), ('CREDIT_CARD', 'Tarjeta de Crédito (Cta. Propia)'), ('DEBIT_CARD', 'Tarjeta de Débito (Cta. Propia)'), ('CHECKBOOK', 'Chequera / Instrumentos'), ('CASH', 'Caja Física (Efectivo)'), ('BRIDGE', 'Puente'), ('MERCHANT', 'Cuenta Recaudadora'), ('CHECK_PORTFOLIO', 'Cheques en Cartera')], default='CASH', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Cuenta Bancaria (Corriente/Vista)'), ('CREDIT_CARD', 'Tarjeta de Crédito (Cta. Propia)'), ('DEBIT_CARD', 'Tarjeta de Débito (Cta. Propia)'), ('CHECKBOOK', 'Chequera / Instrumentos'), ('CASH', 'Caja Física (Efectivo)'), ('BRIDGE', 'Puente'), ('MERCHANT', 'Cuenta Recaudadora'), ('CHECK_PORTFOLIO', 'Cheques en Cartera')], default='CASH', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='HistoricalCheck',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('direction', models.CharField(choices=[('RECEIVED', 'Recibido'), ('ISSUED', 'Girado')], default='RECEIVED', max_length=10, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('IN_PORTFOLIO', 'En Cartera'), ('DEPOSITED', 'Depositado (En Tránsito)'), ('CLEARED', 'Cobrado / Liquidado'), ('BOUNCED', 'Protestado / Rechazado'), ('VOIDED', 'Anulado')], default='IN_PORTFOLIO', max_length=15, verbose_name='Estado')),
                ('check_number', models.CharField(max_length=50, verbose_name='N° de Cheque')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(help_text='Para cheques a fecha: día a partir del cual es cobrable.', verbose_name='Fecha de Cobro / Vencimiento')),
                ('drawer_name', models.CharField(blank=True, help_text='Nombre libre si el girador no es un contacto del sistema.', max_length=150, verbose_name='Nombre Girador')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('deposited_at', models.DateTimeField(blank=True, null=True, verbose_name='Depositado el')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='Cobrado el')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='Protestado el')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bank', verbose_name='Banco Emisor')),
                ('counterparty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Girador / Emisor')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('deposit_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Bancaria de Depósito')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice', verbose_name='Factura')),
                ('portfolio_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Cheques en Cartera')),
                ('receipt_movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Recepción')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder', verbose_name='Orden de Venta')),
                ('settlement_movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Depósito / Liquidación')),
            ],
            options={
                'verbose_name': 'historical Cheque',
                'verbose_name_plural': 'historical Cheques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('RECEIVED', 'Recibido'), ('ISSUED', 'Girado')], default='RECEIVED', max_length=10, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('IN_PORTFOLIO', 'En Cartera'), ('DEPOSITED', 'Depositado (En Tránsito)'), ('CLEARED', 'Cobrado / Liquidado'), ('BOUNCED', 'Protestado / Rechazado'), ('VOIDED', 'Anulado')], default='IN_PORTFOLIO', max_length=15, verbose_name='Estado')),
                ('check_number', models.CharField(max_length=50, verbose_name='N° de Cheque')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(help_text='Para cheques a fecha: día a partir del cual es cobrable.', verbose_name='Fecha de Cobro / Vencimiento')),
                ('drawer_name', models.CharField(blank=True, help_text='Nombre libre si el girador no es un contacto del sistema.', max_length=150, verbose_name='Nombre Girador')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('deposited_at', models.DateTimeField(blank=True, null=True, verbose_name='Depositado el')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='Cobrado el')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='Protestado el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='treasury.bank', verbose_name='Banco Emisor')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_received', to='contacts.contact', verbose_name='Girador / Emisor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks_deposited', to='treasury.treasuryaccount', verbose_name='Cuenta Bancaria de Depósito')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_payments', to='billing.invoice', verbose_name='Factura')),
                ('portfolio_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks_in_portfolio', to='treasury.treasuryaccount', verbose_name='Cuenta Cheques en Cartera')),
                ('receipt_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_receipt', to='treasury.treasurymovement', verbose_name='Movimiento de Recepción')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_payments', to='sales.saleorder', verbose_name='Orden de Venta')),
                ('settlement_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_settlement', to='treasury.treasurymovement', verbose_name='Movimiento de Depósito / Liquidación')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['due_date', '-id'],
                'indexes': [models.Index(fields=['status'], name='treasury_ch_status_e05350_idx'), models.Index(fields=['due_date'], name='treasury_ch_due_dat_b43171_idx'), models.Index(fields=['counterparty', 'status'], name='treasury_ch_counter_63153a_idx')],
            },
        ),
    ]
