# Generated by Django 5.2.10 on 2026-04-15 00:00

import treasury.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0048_remove_historicalpaymentmethod_terminal_vat_bridge_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='date',
            field=models.DateField(default=treasury.models.get_default_date, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='date',
            field=models.DateField(default=treasury.models.get_default_date, verbose_name='Fecha'),
        ),
    ]
