# Generated by Django 5.2.10 on 2026-04-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_productattribute_historicalproduct_has_variants_and_more'),
        ('treasury', '0049_alter_historicaltreasurymovement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentmethod',
            name='commission_product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Producto de servicio utilizado para facturar las comisiones en la factura mensual.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product', verbose_name='Producto de Servicio (Comisión)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='commission_product',
            field=models.ForeignKey(blank=True, help_text='Producto de servicio utilizado para facturar las comisiones en la factura mensual.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='inventory.product', verbose_name='Producto de Servicio (Comisión)'),
        ),
    ]
