# Generated by Django 5.2.10 on 2026-02-13 00:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0050_historicalpaymentmethod_commission_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
    ]
