# Generated by Django 6.0.5 on 2026-06-03 01:35

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0050_alter_treasuryaccount_remove_legacy_account_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, help_text='Identificador del crédito en el banco (opcional).', max_length=60, verbose_name='N° de Operación / Crédito')),
                ('currency', models.CharField(choices=[('CLP', 'Pesos Chilenos (CLP)'), ('UF', 'Unidad de Fomento (UF)')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('principal', models.DecimalField(decimal_places=2, help_text='Monto original del crédito en la moneda elegida.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capital (monto original)')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Tasa en % (ej. 1.2000 = 1.2%). Ver `rate_basis` para periodicidad.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa de Interés')),
                ('rate_basis', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', help_text='Mensual: % directo por cuota. Anual: se divide por 12 al calcular la cuota.', max_length=10, verbose_name='Base de Tasa')),
                ('amortization_system', models.CharField(choices=[('FRENCH', 'Francés (cuota fija)'), ('LINEAR', 'Lineal (capital fijo)')], default='FRENCH', max_length=10, verbose_name='Sistema de Amortización')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo (meses)')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('first_due_date', models.DateField(verbose_name='Primer Vencimiento')),
                ('insurance_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Seguro desgravamen/cesantía mensual. Sumado a cada cuota.', max_digits=18, verbose_name='Seguro Mensual (opcional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Vigente'), ('PAID', 'Pagado'), ('REFINANCED', 'Refinanciado'), ('DEFAULTED', 'En Mora / Incobrable')], default='DRAFT', max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('collateral_notes', models.CharField(blank=True, help_text='Descripción libre de garantías. Modelo dedicado queda fuera del MVP.', max_length=255, verbose_name='Garantías (notas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('disbursement_account', models.ForeignKey(help_text='Cuenta de tesorería tipo CHECKING/CASH donde se recibe el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='loans_disbursed', to='treasury.treasuryaccount', verbose_name='Cuenta de Desembolso (Banco)')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='treasury.bank', verbose_name='Banco Acreedor')),
                ('liability_account', models.ForeignKey(help_text='Cuenta de tesorería tipo LIABILITY que materializa la deuda.', on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_liability', to='treasury.treasuryaccount', verbose_name='Cuenta Pasivo (Préstamo por Pagar)')),
            ],
            options={
                'verbose_name': 'Crédito Bancario',
                'verbose_name_plural': 'Créditos Bancarios',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankLoan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, help_text='Identificador del crédito en el banco (opcional).', max_length=60, verbose_name='N° de Operación / Crédito')),
                ('currency', models.CharField(choices=[('CLP', 'Pesos Chilenos (CLP)'), ('UF', 'Unidad de Fomento (UF)')], default='CLP', max_length=3, verbose_name='Moneda')),
                ('principal', models.DecimalField(decimal_places=2, help_text='Monto original del crédito en la moneda elegida.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capital (monto original)')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Tasa en % (ej. 1.2000 = 1.2%). Ver `rate_basis` para periodicidad.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa de Interés')),
                ('rate_basis', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', help_text='Mensual: % directo por cuota. Anual: se divide por 12 al calcular la cuota.', max_length=10, verbose_name='Base de Tasa')),
                ('amortization_system', models.CharField(choices=[('FRENCH', 'Francés (cuota fija)'), ('LINEAR', 'Lineal (capital fijo)')], default='FRENCH', max_length=10, verbose_name='Sistema de Amortización')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo (meses)')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('first_due_date', models.DateField(verbose_name='Primer Vencimiento')),
                ('insurance_monthly', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Seguro desgravamen/cesantía mensual. Sumado a cada cuota.', max_digits=18, verbose_name='Seguro Mensual (opcional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Vigente'), ('PAID', 'Pagado'), ('REFINANCED', 'Refinanciado'), ('DEFAULTED', 'En Mora / Incobrable')], default='DRAFT', max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('collateral_notes', models.CharField(blank=True, help_text='Descripción libre de garantías. Modelo dedicado queda fuera del MVP.', max_length=255, verbose_name='Garantías (notas)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('disbursement_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta de tesorería tipo CHECKING/CASH donde se recibe el dinero.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta de Desembolso (Banco)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bank', verbose_name='Banco Acreedor')),
                ('liability_account', models.ForeignKey(blank=True, db_constraint=False, help_text='Cuenta de tesorería tipo LIABILITY que materializa la deuda.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Cuenta Pasivo (Préstamo por Pagar)')),
            ],
            options={
                'verbose_name': 'historical Crédito Bancario',
                'verbose_name_plural': 'historical Créditos Bancarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLoanInstallment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='N° de Cuota')),
                ('due_date', models.DateField(verbose_name='Vencimiento')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Interés')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Seguro')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='principal + interest + insurance (en la moneda del crédito).', max_digits=18, verbose_name='Cuota Total')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, help_text='Saldo del crédito después de pagar esta cuota.', max_digits=18, verbose_name='Saldo Insoluto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('PARTIAL', 'Pago Parcial'), ('CANCELED', 'Anulada (refinanciación)')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada el')),
                ('uf_value_used', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor UF al Pago')),
                ('clp_amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente pagado en CLP (para créditos UF).', max_digits=18, null=True, verbose_name='CLP Pagado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.bankloan', verbose_name='Crédito')),
                ('payment_movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasurymovement', verbose_name='Movimiento de Pago')),
            ],
            options={
                'verbose_name': 'historical Cuota de Crédito',
                'verbose_name_plural': 'historical Cuotas de Crédito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='N° de Cuota')),
                ('due_date', models.DateField(verbose_name='Vencimiento')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Interés')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Seguro')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='principal + interest + insurance (en la moneda del crédito).', max_digits=18, verbose_name='Cuota Total')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, help_text='Saldo del crédito después de pagar esta cuota.', max_digits=18, verbose_name='Saldo Insoluto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('PARTIAL', 'Pago Parcial'), ('CANCELED', 'Anulada (refinanciación)')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada el')),
                ('uf_value_used', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Valor UF al Pago')),
                ('clp_amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente pagado en CLP (para créditos UF).', max_digits=18, null=True, verbose_name='CLP Pagado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='treasury.bankloan', verbose_name='Crédito')),
                ('payment_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payment', to='treasury.treasurymovement', verbose_name='Movimiento de Pago')),
            ],
            options={
                'verbose_name': 'Cuota de Crédito',
                'verbose_name_plural': 'Cuotas de Crédito',
                'ordering': ['loan', 'number'],
            },
        ),
        migrations.AddIndex(
            model_name='bankloan',
            index=models.Index(fields=['status'], name='treasury_ba_status_e87a91_idx'),
        ),
        migrations.AddIndex(
            model_name='bankloan',
            index=models.Index(fields=['lender', 'status'], name='treasury_ba_lender__e5073d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankloan',
            index=models.Index(fields=['currency'], name='treasury_ba_currenc_eeaaed_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['loan', 'status'], name='treasury_lo_loan_id_0fcb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['status', 'due_date'], name='treasury_lo_status_28868d_idx'),
        ),
        migrations.AddIndex(
            model_name='loaninstallment',
            index=models.Index(fields=['due_date'], name='treasury_lo_due_dat_86edd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'number'), name='uniq_installment_per_loan'),
        ),
    ]
