# Generated by Django 6.0.5 on 2026-06-03 02:47

from decimal import Decimal

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0051_bankloan_historicalbankloan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCreditCardStatement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("period_year", models.PositiveIntegerField(verbose_name="Año del Período")),
                ("period_month", models.PositiveIntegerField(verbose_name="Mes del Período")),
                ("cut_off_date", models.DateField(verbose_name="Fecha de Cierre")),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "billed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total facturado por la tarjeta en el período (compras + cargos).",
                        max_digits=18,
                        verbose_name="Monto Facturado",
                    ),
                ),
                (
                    "minimum_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Pago mínimo exigido por el banco.",
                        max_digits=18,
                        verbose_name="Pago Mínimo",
                    ),
                ),
                (
                    "interest_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Intereses cargados en el estado de cuenta (gasto financiero).",
                        max_digits=18,
                        verbose_name="Interés del Período",
                    ),
                ),
                (
                    "fees_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Comisiones y otros cargos del período (gasto financiero).",
                        max_digits=18,
                        verbose_name="Comisiones del Período",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cupo total de la tarjeta al cierre del período.",
                        max_digits=18,
                        null=True,
                        verbose_name="Cupo Disponible (Snapshot)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("PAID", "Pagado"),
                            ("OVERDUE", "Vencido"),
                            ("CANCELED", "Anulado"),
                        ],
                        default="OPEN",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Pagado el")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "card_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"account_type": "CREDIT_CARD"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="treasury.treasuryaccount",
                        verbose_name="Cuenta Tarjeta de Crédito",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Cuenta bancaria origen del pago (CHECKING/CASH).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="treasury.treasuryaccount",
                        verbose_name="Cuenta desde la que se pagó",
                    ),
                ),
                (
                    "payment_movement",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="treasury.treasurymovement",
                        verbose_name="Movimiento de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estado de Cuenta Tarjeta",
                "verbose_name_plural": "historical Estados de Cuenta Tarjeta",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CreditCardStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_year", models.PositiveIntegerField(verbose_name="Año del Período")),
                ("period_month", models.PositiveIntegerField(verbose_name="Mes del Período")),
                ("cut_off_date", models.DateField(verbose_name="Fecha de Cierre")),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "billed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total facturado por la tarjeta en el período (compras + cargos).",
                        max_digits=18,
                        verbose_name="Monto Facturado",
                    ),
                ),
                (
                    "minimum_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Pago mínimo exigido por el banco.",
                        max_digits=18,
                        verbose_name="Pago Mínimo",
                    ),
                ),
                (
                    "interest_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Intereses cargados en el estado de cuenta (gasto financiero).",
                        max_digits=18,
                        verbose_name="Interés del Período",
                    ),
                ),
                (
                    "fees_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Comisiones y otros cargos del período (gasto financiero).",
                        max_digits=18,
                        verbose_name="Comisiones del Período",
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cupo total de la tarjeta al cierre del período.",
                        max_digits=18,
                        null=True,
                        verbose_name="Cupo Disponible (Snapshot)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierto"),
                            ("PAID", "Pagado"),
                            ("OVERDUE", "Vencido"),
                            ("CANCELED", "Anulado"),
                        ],
                        default="OPEN",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Pagado el")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_account",
                    models.ForeignKey(
                        limit_choices_to={"account_type": "CREDIT_CARD"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_statements",
                        to="treasury.treasuryaccount",
                        verbose_name="Cuenta Tarjeta de Crédito",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_statements_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta bancaria origen del pago (CHECKING/CASH).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_statement_payments_made",
                        to="treasury.treasuryaccount",
                        verbose_name="Cuenta desde la que se pagó",
                    ),
                ),
                (
                    "payment_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_statement_payment",
                        to="treasury.treasurymovement",
                        verbose_name="Movimiento de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Cuenta Tarjeta",
                "verbose_name_plural": "Estados de Cuenta Tarjeta",
                "ordering": ["-period_year", "-period_month", "-id"],
                "indexes": [
                    models.Index(
                        fields=["card_account", "status"], name="treasury_cr_card_ac_568c7b_idx"
                    ),
                    models.Index(
                        fields=["status", "due_date"], name="treasury_cr_status_07d6d8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("card_account", "period_year", "period_month"),
                        name="uniq_card_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_month__gte", 1), ("period_month__lte", 12)),
                        name="ck_period_month_range",
                    ),
                ],
            },
        ),
    ]
