# Generated by Django 5.2.10 on 2026-02-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0051_alter_historicaltreasurymovement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='pos_session_audit',
        ),
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='historicalcashdifference',
            name='transfer_target',
        ),
        migrations.RemoveField(
            model_name='possessionaudit',
            name='requires_approval',
        ),
        migrations.DeleteModel(
            name='CashDifference',
        ),
        migrations.DeleteModel(
            name='HistoricalCashDifference',
        ),
    ]
