# Generated by Django 6.0.5 on 2026-06-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_contact_roles_historicalcontact_roles"),
        ("treasury", "0052_credit_card_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="endorsed_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor a quien se endosó el cheque recibido.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks_endorsed_to",
                to="contacts.contact",
                verbose_name="Endosado a",
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="endorsement_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="check_endorsement",
                to="treasury.treasurymovement",
                verbose_name="Movimiento de Endoso",
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="issued_check_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta puente LIABILITY para cheques propios girados.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks_issued_liability",
                to="treasury.treasuryaccount",
                verbose_name="Cuenta 'Cheques Girados' (Pasivo)",
            ),
        ),
        migrations.AddField(
            model_name="check",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Para cheques propios: cuenta bancaria desde la que se giró.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks_drawn_from",
                to="treasury.treasuryaccount",
                verbose_name="Cuenta de Cobro (Banco)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheck",
            name="endorsed_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Proveedor a quien se endosó el cheque recibido.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contacts.contact",
                verbose_name="Endosado a",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheck",
            name="endorsement_movement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.treasurymovement",
                verbose_name="Movimiento de Endoso",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheck",
            name="issued_check_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Cuenta puente LIABILITY para cheques propios girados.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.treasuryaccount",
                verbose_name="Cuenta 'Cheques Girados' (Pasivo)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcheck",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Para cheques propios: cuenta bancaria desde la que se giró.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.treasuryaccount",
                verbose_name="Cuenta de Cobro (Banco)",
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PORTFOLIO", "En Cartera"),
                    ("DEPOSITED", "Depositado (En Tránsito)"),
                    ("CLEARED", "Cobrado / Liquidado"),
                    ("BOUNCED", "Protestado / Rechazado"),
                    ("VOIDED", "Anulado"),
                    ("ISSUED", "Girado (Pendiente de Cobro)"),
                    ("ENDORSSED", "Endosado"),
                ],
                default="IN_PORTFOLIO",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcheck",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PORTFOLIO", "En Cartera"),
                    ("DEPOSITED", "Depositado (En Tránsito)"),
                    ("CLEARED", "Cobrado / Liquidado"),
                    ("BOUNCED", "Protestado / Rechazado"),
                    ("VOIDED", "Anulado"),
                    ("ISSUED", "Girado (Pendiente de Cobro)"),
                    ("ENDORSSED", "Endosado"),
                ],
                default="IN_PORTFOLIO",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltreasuryaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Cuenta Bancaria (Corriente/Vista)"),
                    ("CREDIT_CARD", "Tarjeta de Crédito (Cta. Propia)"),
                    ("CASH", "Caja Física (Efectivo)"),
                    ("BRIDGE", "Puente"),
                    ("MERCHANT", "Cuenta Recaudadora"),
                    ("CHECK_PORTFOLIO", "Cheques en Cartera"),
                    ("ISSUED_CHECKS", "Cheques Girados por Pagar"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="treasuryaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Cuenta Bancaria (Corriente/Vista)"),
                    ("CREDIT_CARD", "Tarjeta de Crédito (Cta. Propia)"),
                    ("CASH", "Caja Física (Efectivo)"),
                    ("BRIDGE", "Puente"),
                    ("MERCHANT", "Cuenta Recaudadora"),
                    ("CHECK_PORTFOLIO", "Cheques en Cartera"),
                    ("ISSUED_CHECKS", "Cheques Girados por Pagar"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
