# Generated by Django 5.2.12 on 2026-03-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_advance_and_payment'),
        ('treasury', '0052_remove_historicalcashdifference_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='payroll',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.payroll'),
        ),
        migrations.AddField(
            model_name='historicaltreasurymovement',
            name='payroll_payment_type',
            field=models.CharField(blank=True, choices=[('SALARY', 'Sueldo'), ('PREVIRED', 'Previred'), ('ADVANCE', 'Anticipo')], max_length=20, null=True, verbose_name='Tipo de Pago RRHH'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to='hr.payroll'),
        ),
        migrations.AddField(
            model_name='treasurymovement',
            name='payroll_payment_type',
            field=models.CharField(blank=True, choices=[('SALARY', 'Sueldo'), ('PREVIRED', 'Previred'), ('ADVANCE', 'Anticipo')], max_length=20, null=True, verbose_name='Tipo de Pago RRHH'),
        ),
    ]
