# Generated by Django 5.2.12 on 2026-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0053_payroll_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('WRITE_OFF', 'Castigo de Deuda'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('WRITE_OFF', 'Castigo de Deuda'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
