# Generated by Django 5.2.12 on 2026-03-15 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_remove_historicaljournalentry_state_and_more'),
        ('treasury', '0054_alter_historicaltreasurymovement_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankstatementline',
            name='treasury_ba_reconci_105e2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankstatementline',
            name='treasury_ba_stateme_a30002_idx',
        ),
        migrations.RenameField(
            model_name='bankstatement',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='bankstatementline',
            old_name='reconciliation_state',
            new_name='reconciliation_status',
        ),
        migrations.RenameField(
            model_name='historicalbankstatement',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='historicalbankstatementline',
            old_name='reconciliation_state',
            new_name='reconciliation_status',
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='reconciliation_status',
            field=models.CharField(choices=[('UNRECONCILED', 'No Reconciliado'), ('MATCHED', 'Matched (Pendiente Confirmar)'), ('RECONCILED', 'Reconciliado'), ('DISPUTED', 'En Disputa'), ('EXCLUDED', 'Excluido')], default='UNRECONCILED', max_length=20, verbose_name='Estado de Reconciliación'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='reconciliation_status',
            field=models.CharField(choices=[('UNRECONCILED', 'No Reconciliado'), ('MATCHED', 'Matched (Pendiente Confirmar)'), ('RECONCILED', 'Reconciliado'), ('DISPUTED', 'En Disputa'), ('EXCLUDED', 'Excluido')], default='UNRECONCILED', max_length=20, verbose_name='Estado de Reconciliación'),
        ),
        migrations.AlterField(
            model_name='historicalpossession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['reconciliation_status'], name='treasury_ba_reconci_e795ae_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['statement', 'reconciliation_status'], name='treasury_ba_stateme_3bf0e3_idx'),
        ),
    ]
