# Generated by Django 5.2.12 on 2026-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0056_alter_historicaltreasurymovement_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='justify_reason',
            field=models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('CAPITAL_CONTRIBUTION', 'Aporte de Capital (Socio)'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='justify_reason',
            field=models.CharField(blank=True, choices=[('COUNTING_ERROR', 'Error de Conteo'), ('THEFT', 'Robo/Faltante'), ('ROUNDING', 'Redondeo'), ('TIP', 'Propina'), ('CASHBACK', 'Vuelto Incorrecto'), ('SYSTEM_ERROR', 'Error del Sistema'), ('TRANSFER', 'Traspaso de Efectivo'), ('PARTNER_WITHDRAWAL', 'Retiro de Socio'), ('CAPITAL_CONTRIBUTION', 'Aporte de Capital (Socio)'), ('OTHER_IN', 'Otro Ingreso'), ('OTHER_OUT', 'Otro Egreso'), ('OPENING_ADJUSTMENT', 'Ajuste de Apertura'), ('RETIREMENT', 'Retiro de Cierre'), ('UNKNOWN', 'Desconocido')], help_text='Código de justificación para movimientos manuales', max_length=50, null=True, verbose_name='Justificación'),
        ),
    ]
