# Generated by Django 5.2.14 on 2026-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0061_repair_historical_pos_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltreasuryaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Cuenta Bancaria (Corriente/Vista)"),
                    ("CREDIT_CARD", "Tarjeta de Crédito (Cta. Propia)"),
                    ("CASH", "Caja Física (Efectivo)"),
                    ("BRIDGE", "Puente"),
                    ("CHECK_PORTFOLIO", "Cheques en Cartera"),
                    ("ISSUED_CHECKS", "Cheques Girados por Pagar"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="treasuryaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Cuenta Bancaria (Corriente/Vista)"),
                    ("CREDIT_CARD", "Tarjeta de Crédito (Cta. Propia)"),
                    ("CASH", "Caja Física (Efectivo)"),
                    ("BRIDGE", "Puente"),
                    ("CHECK_PORTFOLIO", "Cheques en Cartera"),
                    ("ISSUED_CHECKS", "Cheques Girados por Pagar"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
