# Generated by Django 6.0.5 on 2026-06-05 20:50

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_contact_roles_historicalcontact_roles"),
        ("treasury", "0068_creditcardstatement_charges_movement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltreasurymovement",
            name="installment_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Posición de la cuota dentro del grupo (1..N).",
                null=True,
                verbose_name="Número de Cuota",
            ),
        ),
        migrations.AddField(
            model_name="historicaltreasurymovement",
            name="is_installment_interest",
            field=models.BooleanField(
                default=False,
                help_text="True si este movimiento es un ADJUSTMENT que imputa el interés explícito de una cuota (no el interés punitorio del emisor).",
                verbose_name="Interés de Cuota",
            ),
        ),
        migrations.AddField(
            model_name="treasurymovement",
            name="installment_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Posición de la cuota dentro del grupo (1..N).",
                null=True,
                verbose_name="Número de Cuota",
            ),
        ),
        migrations.AddField(
            model_name="treasurymovement",
            name="is_installment_interest",
            field=models.BooleanField(
                default=False,
                help_text="True si este movimiento es un ADJUSTMENT que imputa el interés explícito de una cuota (no el interés punitorio del emisor).",
                verbose_name="Interés de Cuota",
            ),
        ),
        migrations.CreateModel(
            name="CardPurchaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador externo del grupo (idempotencia).",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Monto Total",
                    ),
                ),
                (
                    "installments",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cantidad de Cuotas",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Tasa de interés explícita por cuota (ej. 0.015 = 1.5% mensual). 0 = cuotas sin interés.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tasa Mensual (0–1)",
                    ),
                ),
                (
                    "principal_per_installment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot del cálculo: `total_amount / installments` redondeado a 2 decimales. La última cuota absorbe el residuo.",
                        max_digits=18,
                        verbose_name="Principal por Cuota (sin residuo)",
                    ),
                ),
                ("first_installment_date", models.DateField(verbose_name="Fecha Primera Cuota")),
                (
                    "client_reference",
                    models.CharField(
                        blank=True,
                        help_text="ID externo opcional para idempotencia. Si llega un segundo POST con la misma `client_reference`, retorna el grupo existente sin duplicar cuotas.",
                        max_length=128,
                        verbose_name="Referencia Cliente",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="card_purchase_groups",
                        to="treasury.treasuryaccount",
                        verbose_name="Tarjeta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_purchase_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_purchase_groups",
                        to="contacts.contact",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Compra en Cuotas",
                "verbose_name_plural": "Grupos de Compra en Cuotas",
                "ordering": ["-first_installment_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="historicaltreasurymovement",
            name="card_purchase_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Si el movimiento es una cuota de una compra con tarjeta, FK al grupo. Permite listar y conciliar todas las cuotas de una misma compra.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.cardpurchasegroup",
                verbose_name="Grupo de Compra en Cuotas",
            ),
        ),
        migrations.AddField(
            model_name="treasurymovement",
            name="card_purchase_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Si el movimiento es una cuota de una compra con tarjeta, FK al grupo. Permite listar y conciliar todas las cuotas de una misma compra.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="treasury.cardpurchasegroup",
                verbose_name="Grupo de Compra en Cuotas",
            ),
        ),
        migrations.AddIndex(
            model_name="cardpurchasegroup",
            index=models.Index(
                fields=["card_account", "first_installment_date"],
                name="treasury_ca_card_ac_e45678_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cardpurchasegroup",
            index=models.Index(
                fields=["partner", "first_installment_date"], name="treasury_ca_partner_018362_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cardpurchasegroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_reference", ""), _negated=True),
                fields=("client_reference",),
                name="uniq_card_purchase_client_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardpurchasegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("installments__gte", 1), ("installments__lte", 36)),
                name="ck_card_purchase_installments_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardpurchasegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_rate__gte", 0), ("monthly_rate__lt", 1)),
                name="ck_card_purchase_monthly_rate_range",
            ),
        ),
    ]
