# Generated by Django 6.0.5 on 2026-06-06 01:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0069_historicaltreasurymovement_installment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankloan',
            name='opening_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Comisión cobrada al desembolso (gasto). En la moneda del crédito.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Comisión de Apertura'),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tasa de interés penal mensual sobre la cuota vencida (ej. 1.5 = 1.5%/mes). 0 = sin mora.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa de Mora (mensual %)'),
        ),
        migrations.AddField(
            model_name='bankloan',
            name='stamp_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ITE cobrado al desembolso (gasto). En la moneda del crédito.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Impuesto de Timbres y Estampillas'),
        ),
        migrations.AddField(
            model_name='historicalbankloan',
            name='opening_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Comisión cobrada al desembolso (gasto). En la moneda del crédito.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Comisión de Apertura'),
        ),
        migrations.AddField(
            model_name='historicalbankloan',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tasa de interés penal mensual sobre la cuota vencida (ej. 1.5 = 1.5%/mes). 0 = sin mora.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tasa de Mora (mensual %)'),
        ),
        migrations.AddField(
            model_name='historicalbankloan',
            name='stamp_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ITE cobrado al desembolso (gasto). En la moneda del crédito.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Impuesto de Timbres y Estampillas'),
        ),
        migrations.AddField(
            model_name='historicalloaninstallment',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Interés penal cobrado al pagar esta cuota vencida (en CLP).', max_digits=18, verbose_name='Mora Pagada (CLP)'),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Interés penal cobrado al pagar esta cuota vencida (en CLP).', max_digits=18, verbose_name='Mora Pagada (CLP)'),
        ),
    ]
