# Generated by Django 6.0.5 on 2026-06-06 02:08

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0070_bankloan_opening_fee_bankloan_penalty_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardstatement",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Suma de pagos parciales aplicados a este statement. Cuando alcanza `outstanding_balance`, el status pasa a PAID.",
                max_digits=18,
                verbose_name="Monto Pagado (acumulado)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcreditcardstatement",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Suma de pagos parciales aplicados a este statement. Cuando alcanza `outstanding_balance`, el status pasa a PAID.",
                max_digits=18,
                verbose_name="Monto Pagado (acumulado)",
            ),
        ),
        migrations.AlterField(
            model_name="creditcardstatement",
            name="payment_movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="card_statement_payments",
                to="treasury.treasurymovement",
                verbose_name="Movimiento de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="creditcardstatement",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Abierto"),
                    ("PARTIALLY_PAID", "Pagado Parcialmente"),
                    ("PAID", "Pagado"),
                    ("OVERDUE", "Vencido"),
                    ("CANCELED", "Anulado"),
                ],
                default="OPEN",
                max_length=14,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcreditcardstatement",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Abierto"),
                    ("PARTIALLY_PAID", "Pagado Parcialmente"),
                    ("PAID", "Pagado"),
                    ("OVERDUE", "Vencido"),
                    ("CANCELED", "Anulado"),
                ],
                default="OPEN",
                max_length=14,
                verbose_name="Estado",
            ),
        ),
    ]
