# Generated by Django 6.0.5 on 2026-06-06 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0071_creditcardstatement_amount_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltreasurymovement",
            name="from_card_statement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Si este movimiento es un pago (parcial o total) de un statement de tarjeta, FK al statement. Permite listar todos los pagos de un statement via payment_movements.all().",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.creditcardstatement",
                verbose_name="Statement de Tarjeta Pagado",
            ),
        ),
        migrations.AddField(
            model_name="treasurymovement",
            name="from_card_statement",
            field=models.ForeignKey(
                blank=True,
                help_text="Si este movimiento es un pago (parcial o total) de un statement de tarjeta, FK al statement. Permite listar todos los pagos de un statement via payment_movements.all().",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_movements",
                to="treasury.creditcardstatement",
                verbose_name="Statement de Tarjeta Pagado",
            ),
        ),
    ]
