# Generated by Django 6.0.5 on 2026-06-08 23:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0074_treasury_movement_billed_in_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPurchaseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Posición de la cuota dentro del grupo (1..N).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Cuota')),
                ('due_date', models.DateField(help_text='Mes en que la cuota se factura en el statement.', verbose_name='Fecha de Vencimiento')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Principal de la Cuota')),
                ('is_billed', models.BooleanField(db_index=True, default=False, help_text='True si la cuota ya fue incluida en el billed_amount de un CreditCardStatement.', verbose_name='Facturada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billed_in_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_charges', to='treasury.creditcardstatement', verbose_name='Facturada en Statement')),
                ('card_purchase_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='treasury.cardpurchasegroup', verbose_name='Grupo de Compra')),
            ],
            options={
                'verbose_name': 'Cuota de Compra TC',
                'verbose_name_plural': 'Cuotas de Compra TC',
                'ordering': ['card_purchase_group', 'number'],
                'indexes': [models.Index(fields=['is_billed', 'due_date'], name='treasury_ca_is_bill_e9e82e_idx')],
                'constraints': [models.UniqueConstraint(fields=('card_purchase_group', 'number'), name='uniq_card_purchase_installment_number')],
            },
        ),
    ]
