# Generated by Django 6.0.5 on 2026-06-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0024_accountingsettings_card_minimum_payment_block_and_more"),
        ("treasury", "0075_cardpurchaseinstallment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPendingCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Monto"),
                ),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("COMMISSION", "Comisión"),
                            ("TAX", "Impuesto"),
                            ("FEE", "Cargo"),
                            ("INSURANCE", "Seguro"),
                            ("OTHER", "Otro"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Tipo de Cargo",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descripción")),
                ("date", models.DateField(verbose_name="Fecha")),
                ("is_billed", models.BooleanField(default=False, verbose_name="Facturado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billed_in_statement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_charges",
                        to="treasury.creditcardstatement",
                        verbose_name="Facturado en Statement",
                    ),
                ),
                (
                    "card_account",
                    models.ForeignKey(
                        limit_choices_to={"account_type": "CREDIT_CARD"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_charges",
                        to="treasury.treasuryaccount",
                        verbose_name="Cuenta Tarjeta de Crédito",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_pending_charge",
                        to="accounting.journalentry",
                        verbose_name="Asiento Contable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo Pendiente de Tarjeta",
                "verbose_name_plural": "Cargos Pendientes de Tarjeta",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["card_account", "is_billed"], name="treasury_ca_card_a_5f2c88_idx"
                    ),
                    models.Index(
                        fields=["card_account", "date"], name="treasury_ca_card_a_5b18d9_idx"
                    ),
                ],
            },
        ),
    ]
