# Generated by Django 5.2.15 on 2026-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0080_add_interest_charge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltreasurymovement",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Tarjeta (Manual)"),
                    ("DEBIT_CARD", "Tarjeta Débito Empresa"),
                    ("CREDIT_CARD", "Tarjeta Crédito Empresa"),
                    ("CARD_TERMINAL", "Tarjeta (Terminal de cobro)"),
                    ("TRANSFER", "Transferencia"),
                    ("CHECK", "Cheque"),
                    ("CREDIT", "Crédito"),
                    ("WRITE_OFF", "Castigo de Deuda"),
                    ("CREDIT_BALANCE", "Saldo a Favor"),
                    ("OTHER", "Otro"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Método de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="treasurymovement",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Tarjeta (Manual)"),
                    ("DEBIT_CARD", "Tarjeta Débito Empresa"),
                    ("CREDIT_CARD", "Tarjeta Crédito Empresa"),
                    ("CARD_TERMINAL", "Tarjeta (Terminal de cobro)"),
                    ("TRANSFER", "Transferencia"),
                    ("CHECK", "Cheque"),
                    ("CREDIT", "Crédito"),
                    ("WRITE_OFF", "Castigo de Deuda"),
                    ("CREDIT_BALANCE", "Saldo a Favor"),
                    ("OTHER", "Otro"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Método de Pago",
            ),
        ),
    ]
