# Generated by Django 6.0.5 on 2026-06-22 16:35

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treasury", "0083_add_default_deposit_account_to_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Identificador de la línea en el banco (opcional).",
                        max_length=60,
                        verbose_name="Código",
                    ),
                ),
                (
                    "credit_line_type",
                    models.CharField(
                        choices=[("REVOLVING", "Rotativa")],
                        default="REVOLVING",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("currency", models.CharField(default="CLP", max_length=3, verbose_name="Moneda")),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto total de crédito aprobado por el banco.",
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="Monto Aprobado",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Tasa de referencia en % (ej. 1.2000 = 1.2%). Ver rate_basis.",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Tasa de Interés",
                    ),
                ),
                (
                    "rate_basis",
                    models.CharField(
                        blank=True,
                        choices=[("MONTHLY", "Mensual"), ("ANNUAL", "Anual")],
                        help_text="Mensual/Anual para la tasa de referencia.",
                        max_length=10,
                        verbose_name="Base de Tasa",
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Spread sobre tasa base (puntos porcentuales).",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Spread",
                    ),
                ),
                (
                    "commitment_fee",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Comisión anual % sobre el saldo no dispuesto (commitment fee).",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="Comisión por No Utilizado",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Vigencia Desde")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de vencimiento de la línea. Si es null, no expira.",
                        null=True,
                        verbose_name="Vigencia Hasta",
                    ),
                ),
                (
                    "auto_renewal",
                    models.BooleanField(default=False, verbose_name="Renovación Automática"),
                ),
                (
                    "renewal_term_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Si la renovación es automática, plazo en meses de la renovación.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Plazo de Renovación (meses)",
                    ),
                ),
                (
                    "collateral_notes",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de garantías asociadas a la línea.",
                        verbose_name="Garantías",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Vigente"),
                            ("EXPIRED", "Vencida"),
                            ("CANCELED", "Cancelada"),
                            ("SUSPENDED", "Suspendida"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_lines",
                        to="treasury.bank",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_lines_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Crédito",
                "verbose_name_plural": "Líneas de Crédito",
                "ordering": ["-valid_from", "-id"],
            },
        ),
        migrations.AddField(
            model_name="bankloan",
            name="credit_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea de crédito de la cual se dispone este préstamo. Si se asigna, valida que el principal no exceda el cupo disponible.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="treasury.creditline",
                verbose_name="Línea de Crédito",
            ),
        ),
        migrations.AddField(
            model_name="historicalbankloan",
            name="credit_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Línea de crédito de la cual se dispone este préstamo. Si se asigna, valida que el principal no exceda el cupo disponible.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="treasury.creditline",
                verbose_name="Línea de Crédito",
            ),
        ),
        migrations.AddIndex(
            model_name="creditline",
            index=models.Index(fields=["status"], name="treasury_cr_status_c6aa30_idx"),
        ),
        migrations.AddIndex(
            model_name="creditline",
            index=models.Index(fields=["bank", "status"], name="treasury_cr_bank_id_48b9dc_idx"),
        ),
        migrations.AddIndex(
            model_name="creditline",
            index=models.Index(fields=["currency"], name="treasury_cr_currenc_76c05f_idx"),
        ),
    ]
