# Generated by Django 6.0.5 on 2026-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0087_add_card_number_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreconciliationsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
