# Generated by Django 6.0.6 on 2026-07-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0089_bank_deleted_at_bankloan_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='cardpendingcharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='cardpurchasegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='cardpurchaseinstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='check',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatement',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatement',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalbankstatementline',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalcardpendingcharge',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalcardpurchasegroup',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalcardpurchaseinstallment',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalcheck',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalloaninstallment',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalloaninstallment',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentallocation',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpossession',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalpossession',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalpossessionaudit',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalreconciliationmatch',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalreconciliationsettings',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalreconciliationsettings',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalterminalbatch',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaltreasuryaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicaltreasuryaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicaltreasurymovement',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='loaninstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='possessionaudit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='reconciliationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='reconciliationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='terminalbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='treasuryaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizado el'),
        ),
    ]
