# Generated by Django 6.0.6 on 2026-08-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0092_remove_historicalcardpurchasegroup_card_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpossession',
            name='treasury_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Snapshot de la cuenta de tesorería al abrir la sesión (copiado de terminal.default_treasury_account). No editable.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.treasuryaccount', verbose_name='Caja (snapshot al abrir)'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='treasury_account',
            field=models.ForeignKey(blank=True, help_text='Snapshot de la cuenta de tesorería al abrir la sesión (copiado de terminal.default_treasury_account). No editable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='treasury.treasuryaccount', verbose_name='Caja (snapshot al abrir)'),
        ),
    ]
