# Generated by Django 5.2.9 on 2025-12-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
