# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('billing', '0005_initial'),
        ('contacts', '0003_initial'),
        ('inventory', '0001_initial'),
        ('production', '0002_initial'),
        ('sales', '0002_initial'),
        ('treasury', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='credit_approval_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.task', verbose_name='Tarea de Aprobación de Crédito'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='pos_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasury.possession', verbose_name='Sesión de Caja'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='salesperson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalereturn',
            name='credit_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='historicalsalereturn',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsalereturn',
            name='journal_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='historicalsalereturn',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega de recepción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_delivery', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_deliveries', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='warehouse',
            field=models.ForeignKey(help_text='Bodega desde donde se despacha', on_delete=django.db.models.deletion.PROTECT, related_name='sale_deliveries', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saledelivery'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='stock_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_delivery_line', to='inventory.stockmove'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.uom'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='OT generada para este despacho (productos fabricables express)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='production.workorder'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='related_note',
            field=models.ForeignKey(blank=True, help_text='Nota que originó esta línea adicional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sale_lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.uom', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='sale_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='sales.saleline'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='credit_approval_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_sale_orders', to='workflow.task', verbose_name='Tarea de Aprobación de Crédito'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_order', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='pos_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='treasury.possession', verbose_name='Sesión de Caja'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='historicalsalereturn',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='historicalsaledelivery',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_return', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='sale_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='warehouse',
            field=models.ForeignKey(help_text='Bodega de recepción', on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='return_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salereturn'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='stock_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_return_line', to='inventory.stockmove'),
        ),
        migrations.AddField(
            model_name='salereturnline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.uom'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_global_discount_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario con permiso para Descuento Global'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_line_discount_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario con permiso para Descuento por Línea'),
        ),
        migrations.AddIndex(
            model_name='draftcart',
            index=models.Index(fields=['pos_session', '-updated_at'], name='sales_draft_pos_ses_6265b2_idx'),
        ),
    ]
