# Generated by Django 5.2.9 on 2025-12-31 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0003_saleorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.product'),
        ),
    ]
