# Generated by Django 5.2.9 on 2025-12-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='channel',
            field=models.CharField(choices=[('SYSTEM', 'Sistema'), ('POS', 'Punto de Venta (POS)')], default='SYSTEM', max_length=20, verbose_name='Canal'),
        ),
    ]
