# Generated by Django 5.2.9 on 2026-01-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saleorder_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='CONFIRMED', max_length=20, verbose_name='Estado'),
        ),
    ]
