# Generated by Django 5.2.9 on 2026-01-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_stock_sales', models.BooleanField(default=False, help_text='Si está activo, impide vender productos almacenables si no hay stock suficiente.', verbose_name='Restringir Ventas Sin Stock')),
            ],
            options={
                'verbose_name': 'Configuración de Ventas',
                'verbose_name_plural': 'Configuración de Ventas',
            },
        ),
    ]
