# Generated by Django 5.2.9 on 2026-01-02 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_accountingsettings_default_card_treasury_account_and_more'),
        ('inventory', '0003_merge_20260102_1735'),
        ('sales', '0007_salessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='quantity_delivered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total despachada de esta línea', max_digits=10, verbose_name='Cantidad Despachada'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Planificada'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20, verbose_name='Estado de Despacho'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='immediate_dispatch',
            field=models.BooleanField(default=False, verbose_name='Despacho Inmediato'),
        ),
        migrations.CreateModel(
            name='SaleDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Despacho')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_delivery', to='accounting.journalentry')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.saleorder')),
                ('warehouse', models.ForeignKey(help_text='Bodega desde donde se despacha', on_delete=django.db.models.deletion.PROTECT, related_name='sale_deliveries', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Despacho de Venta',
                'verbose_name_plural': 'Despachos de Venta',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleDeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, help_text='Cantidad despachada en este despacho', max_digits=10, verbose_name='Cantidad Despachada')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Costo unitario del producto al momento del despacho', max_digits=12, verbose_name='Costo Unitario')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Costo Total')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saledelivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.product')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='sales.saleline')),
                ('stock_move', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_delivery_line', to='inventory.stockmove')),
            ],
            options={
                'verbose_name': 'Línea de Despacho',
                'verbose_name_plural': 'Líneas de Despacho',
            },
        ),
    ]
