# Generated by Django 5.2.9 on 2026-01-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sales', '0008_saleline_quantity_delivered_saleorder_delivery_date_and_more'),
        ('treasury', '0006_remove_payment_customer_remove_payment_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='contacts.contact'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
