# Generated by Django 5.2.14 on 2026-05-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salessettings_timestampedmodel_t14'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledelivery',
            options={'verbose_name': 'Despacho de Venta', 'verbose_name_plural': 'Despachos de Venta'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'verbose_name': 'Nota de Venta', 'verbose_name_plural': 'Notas de Venta'},
        ),
        migrations.AlterModelOptions(
            name='salereturn',
            options={'verbose_name': 'Devolución de Venta', 'verbose_name_plural': 'Devoluciones de Venta'},
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Descuento Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
