# Generated by Django 5.2.9 on 2026-01-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_uom_uomcategory_product_purchase_uom_product_uom_and_more'),
        ('sales', '0009_alter_saleorder_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.uom', verbose_name='Unidad'),
        ),
    ]
