# Generated by Django 5.2.9 on 2026-01-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_saleline_first_name_saleline_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='manufacturing_data',
            field=models.JSONField(blank=True, help_text='Metadatos capturados para fabricación avanzada (diseño, fechas, contactos, etc.)', null=True, verbose_name='Datos de Fabricación'),
        ),
    ]
