# Generated by Django 5.2.10 on 2026-01-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_saleline_manufacturing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledeliveryline',
            name='quantity_delivered',
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad despachada en este despacho', max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='saledeliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Unitario'),
        ),
    ]
