# Generated by Django 5.2.10 on 2026-01-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_saledeliveryline_quantity_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledelivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Total (COGS)'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
    ]
