# Generated by Django 5.2.9 on 2026-01-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_add_consumable_account'),
        ('sales', '0013_saledelivery_total_saledelivery_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledelivery',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_delivery', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_order', to='accounting.journalentry'),
        ),
    ]
