# Generated by Django 5.2.10 on 2026-01-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_stockmove_uom_alter_stockmove_date_and_more'),
        ('sales', '0014_alter_saledelivery_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledeliveryline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.uom'),
        ),
    ]
