# Generated by Django 5.2.9 on 2026-01-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_saledeliveryline_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledelivery',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Costo Total (COGS)'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_net',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=12, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
