# Generated by Django 5.2.10 on 2026-01-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_saledelivery_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledeliveryline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad despachada en este despacho', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='quantity_delivered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad total despachada de esta línea', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Despachada'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa Impuesto %'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
    ]
