# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_timestampedmodel_sales_purchasing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftcart',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalsaledelivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsaledelivery',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalsaleorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsaleorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicalsalereturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsalereturn',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='saledelivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='saledelivery',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='saledeliveryline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saledeliveryline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='saledeliveryline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saleline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saleline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='saleline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='saleorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='salereturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salereturn',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='salereturnline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salereturnline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='salereturnline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salessettings',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='historicalsalereturn',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='salessettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
