# Generated by Django 5.2.10 on 2026-01-20 01:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_budget_options_alter_journalentry_options'),
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('sales', '0017_alter_saledeliveryline_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledelivery',
            options={'ordering': ['-id'], 'verbose_name': 'Despacho de Venta', 'verbose_name_plural': 'Despachos de Venta'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-id'], 'verbose_name': 'Nota de Venta', 'verbose_name_plural': 'Notas de Venta'},
        ),
        migrations.CreateModel(
            name='HistoricalSaleOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('INVOICED', 'Facturado'), ('PAID', 'Pagado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito')], default='CREDIT', max_length=20, verbose_name='Método de Pago')),
                ('channel', models.CharField(choices=[('SYSTEM', 'Sistema'), ('POS', 'Punto de Venta (POS)')], default='SYSTEM', max_length=20, verbose_name='Canal')),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20, verbose_name='Estado de Despacho')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Planificada')),
                ('immediate_dispatch', models.BooleanField(default=False, verbose_name='Despacho Inmediato')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('salesperson', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Nota de Venta',
                'verbose_name_plural': 'historical Notas de Venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
