# Generated by Django 5.2.10 on 2026-01-20 05:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_budget_options_alter_journalentry_options'),
        ('inventory', '0043_alter_pricingrule_options_alter_product_options_and_more'),
        ('sales', '0018_alter_saledelivery_options_alter_saleorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSaleDelivery',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número')),
                ('delivery_date', models.DateField(verbose_name='Fecha de Despacho')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Anulado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('total_net', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Neto')),
                ('total_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Impuesto')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Costo Total (COGS)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega desde donde se despacha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Despacho de Venta',
                'verbose_name_plural': 'historical Despachos de Venta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
