# Generated by Django 5.2.10 on 2026-01-20 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_historicalsaledelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Costo Total (COGS)'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsaledelivery',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Costo Total (COGS)'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='saledelivery',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=16, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Impuesto'),
        ),
    ]
