# Generated by Django 5.2.10 on 2026-01-21 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_historicalsaleorder_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='saledeliveryline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Neto'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto'),
        ),
    ]
