# Generated by Django 5.2.10 on 2026-01-21 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_historicalsaleorder_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledeliveryline',
            name='unit_price_gross',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Bruto'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='unit_price_gross',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Bruto'),
        ),
    ]
