# Generated by Django 5.2.10 on 2026-01-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_noteworkflow'),
        ('sales', '0023_historicalsalereturn_salereturn_salereturnline'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaledelivery',
            name='related_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='saledelivery',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_deliveries', to='billing.invoice'),
        ),
    ]
