# Generated by Django 5.2.10 on 2026-01-27 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_noteworkflow'),
        ('sales', '0024_historicalsaledelivery_related_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='related_note',
            field=models.ForeignKey(blank=True, help_text='Nota que originó esta línea adicional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_sale_lines', to='billing.invoice'),
        ),
    ]
