# Generated by Django 5.2.10 on 2026-01-27 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_add_related_note_to_workorder'),
        ('sales', '0025_add_related_note_to_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledeliveryline',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='OT generada para este despacho (productos fabricables express)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='production.workorder'),
        ),
    ]
