# Generated by Django 5.2.10 on 2026-02-03 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('sales', '0026_add_work_order_to_delivery_line'),
        ('treasury', '0018_add_pos_session_to_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre descriptivo del borrador', max_length=255, verbose_name='Nombre')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('items', models.JSONField(help_text='Estructura JSON con los items del carrito', verbose_name='Items del Carrito')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Neto')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Bruto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draft_carts', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_carts', to='contacts.contact', verbose_name='Cliente')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_draft_carts', to=settings.AUTH_USER_MODEL, verbose_name='Última Modificación Por')),
                ('pos_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_carts', to='treasury.possession', verbose_name='Sesión POS')),
            ],
            options={
                'verbose_name': 'Borrador de Carrito',
                'verbose_name_plural': 'Borradores de Carrito',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['pos_session', '-updated_at'], name='sales_draft_pos_ses_6265b2_idx')],
            },
        ),
    ]
