# Generated by Django 5.2.11 on 2026-02-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_draftcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcart',
            name='wizard_state',
            field=models.JSONField(blank=True, help_text='Estado actual del wizard de ventas (paso, datos de DTE, pago, etc.)', null=True, verbose_name='Estado del Wizard'),
        ),
    ]
