# Generated by Django 5.2.10 on 2026-02-13 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_historicalsaleorder_pos_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
