# Generated by Django 5.2.10 on 2026-02-13 00:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_historicalsaleorder_date_alter_saleorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
    ]
