# Generated by Django 5.2.12 on 2026-03-06 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_historicalsaleorder_date_alter_saleorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcart',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento Total'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento Total'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Descuento'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Descuento %'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento Total'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_enable_line_discounts',
            field=models.BooleanField(default=True, verbose_name='POS: Habilitar Descuentos por Línea'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_enable_total_discounts',
            field=models.BooleanField(default=True, verbose_name='POS: Habilitar Descuento Total'),
        ),
    ]
