# Generated by Django 5.2.12 on 2026-03-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_draftcart_total_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salessettings',
            name='pos_global_discount_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grupo con permiso para Descuento Global'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_global_discount_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario con permiso para Descuento Global'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_line_discount_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grupo con permiso para Descuento por Línea'),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='pos_line_discount_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario con permiso para Descuento por Línea'),
        ),
    ]
