# Generated by Django 5.2.12 on 2026-03-14 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_salessettings_pos_global_discount_group_and_more'),
        ('workflow', '0005_workflowsettings_low_margin_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='credit_approval_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.task', verbose_name='Tarea de Aprobación de Crédito'),
        ),
        migrations.AddField(
            model_name='historicalsaleorder',
            name='credit_assignment_origin',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual (Aprobación)'), ('FALLBACK', 'Fallback (% Venta)'), ('CONTACT_FILE', 'Ficha de Contacto')], max_length=20, null=True, verbose_name='Origen de Asignación de Crédito'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='credit_approval_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_sale_orders', to='workflow.task', verbose_name='Tarea de Aprobación de Crédito'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='credit_assignment_origin',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual (Aprobación)'), ('FALLBACK', 'Fallback (% Venta)'), ('CONTACT_FILE', 'Ficha de Contacto')], max_length=20, null=True, verbose_name='Origen de Asignación de Crédito'),
        ),
    ]
