# Generated by Django 5.2.12 on 2026-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_historicalsaleorder_credit_approval_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='credit_assignment_origin',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual (Aprobación)'), ('FALLBACK', 'Pre-Aprobado (% Venta)'), ('CREDIT_PORTFOLIO', 'Cartera de Crédito')], max_length=20, null=True, verbose_name='Origen de Asignación de Crédito'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='credit_assignment_origin',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual (Aprobación)'), ('FALLBACK', 'Pre-Aprobado (% Venta)'), ('CREDIT_PORTFOLIO', 'Cartera de Crédito')], max_length=20, null=True, verbose_name='Origen de Asignación de Crédito'),
        ),
    ]
