# Generated by Django 5.2.12 on 2026-03-24 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_alter_historicalsaleorder_credit_assignment_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturnline',
            name='unit_price_gross',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Bruto'),
        ),
    ]
