# Generated by Django 5.2.12 on 2026-03-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_salereturnline_unit_price_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CREDIT', 'Crédito'), ('CREDIT_BALANCE', 'Saldo a Favor')], default='CREDIT', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
