# Generated by Django 5.2.12 on 2026-03-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_alter_historicalsaleorder_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcart',
            name='lock_session_key',
            field=models.CharField(blank=True, default='', help_text='UUID único de la pestaña del navegador que tiene el lock', max_length=64, verbose_name='Clave de Sesión del Lock'),
        ),
        migrations.AddField(
            model_name='draftcart',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Última renovación del heartbeat del lock', null=True, verbose_name='Bloqueado Desde'),
        ),
        migrations.AddField(
            model_name='draftcart',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_draft_carts', to=settings.AUTH_USER_MODEL, verbose_name='Bloqueado Por'),
        ),
    ]
