# Generated by Django 6.0.5 on 2026-06-03 01:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('UF', 'Unidad de Fomento (UF)'), ('UTM', 'Unidad Tributaria Mensual (UTM)'), ('USD', 'Dólar Observado (USD)')], max_length=10, verbose_name='Indicador')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('value', models.DecimalField(decimal_places=4, help_text='Valor del indicador en CLP (o USD mismo para USD).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Valor')),
                ('source', models.CharField(blank=True, help_text="Origen del valor: 'manual' (UI) o 'mindicador.cl' (feed).", max_length=50, verbose_name='Origen')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valor de Indicador',
                'verbose_name_plural': 'Valores de Indicadores',
                'ordering': ['-date', 'indicator'],
                'indexes': [models.Index(fields=['indicator', '-date'], name='finances_in_indicat_1aa1e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('indicator', 'date'), name='uniq_indicator_value_per_date')],
            },
        ),
    ]
