# Generated by Django 5.2.15 on 2026-06-19 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndicatorValue",
        ),
    ]
