from django.apps import AppConfig

class WorkflowConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'workflow'

    def ready(self):
        # Register signals
        import workflow.signals

        try:
            from core.permissions import PermissionRegistry
            PermissionRegistry.register('workflow', [
                ('view_dashboard_workflow', 'Can view workflow dashboard'),
                # Add task permissions if they are not auto-generated by Django (Django generates view_task, add_task etc for models)
                # But we might need them registered for strict checking or sidebar if we add it there?
                # For now, just ensuring the app config exists and registers something is good practice.
            ])
        except ImportError:
            pass

        try:
            from core.registry import UniversalRegistry, SearchableEntity
            from workflow.models import Task
            UniversalRegistry.register(SearchableEntity(
                model=Task,
                label='workflow.task',
                icon='circle-check',
                search_fields=('title', 'description'),
                display_template='{title}',
                list_url='/workflow/tasks',
                detail_url_pattern='/workflow/tasks/{id}',
                permission='workflow.view_task',
            ))
        except Exception:
            pass
