# Generated by Django 5.2.9 on 2025-12-31 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número OT')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='PLANNED', max_length=20, verbose_name='Estado')),
                ('specifications', models.TextField(blank=True, help_text='Papel, Tintas, Terminaciones, etc.', verbose_name='Especificaciones Técnicas')),
                ('qty_planned', models.IntegerField(default=0, verbose_name='Cantidad Planificada')),
                ('qty_produced', models.IntegerField(default=0, verbose_name='Cantidad Producida')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_order', models.ForeignKey(blank=True, help_text='Nota de Venta asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='ProductionConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.product')),
                ('stock_move', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_consumption', to='inventory.stockmove')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.warehouse')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.workorder')),
            ],
            options={
                'verbose_name': 'Consumo Material',
                'verbose_name_plural': 'Consumos Materiales',
            },
        ),
    ]
