# Generated by Django 5.2.12 on 2026-04-04 00:10

import core.utils
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_initial'),
        ('contacts', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('date', models.DateField(default=core.utils.get_current_date, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Consumo Material',
                'verbose_name_plural': 'Consumos Materiales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número OT')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Es Manual')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('current_stage', models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('RECTIFICATION', 'Rectificación'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual')),
                ('stage_data', models.JSONField(blank=True, default=dict, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas')),
                ('specifications', models.TextField(blank=True, help_text='Papel, Tintas, Terminaciones, etc.', verbose_name='Especificaciones Técnicas')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('actual_quantity_produced', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad real fabricada declarada en la rectificación (OTs manuales)', max_digits=12, null=True, verbose_name='Cantidad Real Producida')),
                ('is_rectified', models.BooleanField(default=False, help_text='Indica si la OT pasó por el paso de rectificación antes de finalizar', verbose_name='Rectificada')),
                ('no_materials_required', models.BooleanField(default=False, help_text='Si se marca, se omite el paso de aprobación de materiales', verbose_name='Sin materiales de stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Ordenes de Trabajo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de OT',
                'verbose_name_plural': 'Historiales de OT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Planificada')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Consumida')),
                ('source', models.CharField(choices=[('BOM', 'Lista de Materiales'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Origen')),
                ('is_outsourced', models.BooleanField(default=False, verbose_name='Es Tercerizado')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario OC')),
                ('document_type', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], default='FACTURA', max_length=20, verbose_name='Tipo de Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material de OT',
                'verbose_name_plural': 'Materiales de OT',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: BOM Camiseta Roja v1', max_length=255, verbose_name='Nombre')),
                ('active', models.BooleanField(default=True, help_text='Solo puede haber un BOM activo por producto', verbose_name='Activo')),
                ('yield_quantity', models.DecimalField(decimal_places=4, default=1, help_text='Cantidad producida por esta receta', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Rendimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Producto fabricable', limit_choices_to={'product_type': 'MANUFACTURABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product')),
                ('yield_uom', models.ForeignKey(blank=True, help_text='Unidad en la que se expresa el rendimiento (se usa la unidad base del producto si se omite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_yields', to='inventory.uom', verbose_name='Unidad de Rendimiento')),
            ],
            options={
                'verbose_name': 'Lista de Materiales (BOM)',
                'verbose_name_plural': 'Listas de Materiales (BOMs)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Cantidad necesaria por unidad producida', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('is_outsourced', models.BooleanField(default=False, verbose_name='Es Tercerizado')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, help_text='Precio neto por unidad (sin IVA)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Neto')),
                ('document_type', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], default='FACTURA', max_length=20, verbose_name='Tipo de Documento')),
                ('sequence', models.IntegerField(default=10, help_text='Orden de visualización', verbose_name='Secuencia')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterials')),
                ('component', models.ForeignKey(help_text='Producto componente/material', on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_lines', to='contacts.contact', verbose_name='Proveedor')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.uom', verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Línea de BOM',
                'verbose_name_plural': 'Líneas de BOM',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número OT')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Es Manual')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('current_stage', models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('RECTIFICATION', 'Rectificación'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual')),
                ('stage_data', models.JSONField(blank=True, default=dict, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas')),
                ('specifications', models.TextField(blank=True, help_text='Papel, Tintas, Terminaciones, etc.', verbose_name='Especificaciones Técnicas')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('actual_quantity_produced', models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad real fabricada declarada en la rectificación (OTs manuales)', max_digits=12, null=True, verbose_name='Cantidad Real Producida')),
                ('is_rectified', models.BooleanField(default=False, help_text='Indica si la OT pasó por el paso de rectificación antes de finalizar', verbose_name='Rectificada')),
                ('no_materials_required', models.BooleanField(default=False, help_text='Si se marca, se omite el paso de aprobación de materiales', verbose_name='Sin materiales de stock')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='Producto fabricable (para OTs manuales)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('related_contact', models.ForeignKey(blank=True, db_constraint=False, help_text='Contacto relacionado con esta OT (ej: cliente del cliente, dato de facturación)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Contacto Relacionado')),
                ('related_note', models.ForeignKey(blank=True, db_constraint=False, help_text='Nota de Débito/Crédito que originó esta OT', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'historical Orden de Trabajo',
                'verbose_name_plural': 'historical Ordenes de Trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
