# Generated by Django 5.2.12 on 2026-04-04 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_initial'),
        ('contacts', '0003_initial'),
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='sale_line',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Línea de venta asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleline'),
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='sale_order',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Nota de Venta asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega de donde se obtendrán los materiales', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='stock_move',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_consumption', to='inventory.stockmove'),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto fabricable (para OTs manuales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_work_orders', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='related_contact',
            field=models.ForeignKey(blank=True, help_text='Contacto relacionado con esta OT (ej: cliente del cliente, dato de facturación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_work_orders', to='contacts.contact', verbose_name='Contacto Relacionado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='related_note',
            field=models.ForeignKey(blank=True, help_text='Nota de Débito/Crédito que originó esta OT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sale_line',
            field=models.ForeignKey(blank=True, help_text='Línea de venta asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='sales.saleline'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sale_order',
            field=models.ForeignKey(blank=True, help_text='Nota de Venta asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='sales.saleorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Bodega de donde se obtendrán los materiales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='productionconsumption',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.workorder'),
        ),
        migrations.AddField(
            model_name='workorderhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='production.workorder'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_material_usages', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='purchasing.purchaseline', verbose_name='Línea de Compra'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='contacts.contact', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_materials', to='inventory.uom'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.workorder'),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterialsline',
            unique_together={('bom', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='workordermaterial',
            unique_together={('work_order', 'component')},
        ),
    ]
