# Generated by Django 5.2.9 on 2026-01-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productattribute_product_variant_of_and_more'),
        ('production', '0002_workorder_bom_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(help_text='Producto fabricable', limit_choices_to={'product_type': 'MANUFACTURABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización'),
        ),
    ]
