# Generated by Django 5.2.10 on 2026-01-07 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_refine_product_types'),
        ('production', '0003_alter_billofmaterials_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(help_text='Producto fabricable', limit_choices_to={'product_type__in': ['MANUFACTURABLE_STANDARD', 'MANUFACTURABLE_CUSTOM']}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product'),
        ),
    ]
