# Generated by Django 5.2.9 on 2026-01-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_billofmaterials'),
        ('production', '0004_alter_billofmaterials_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(help_text='Producto fabricable', limit_choices_to={'product_type': 'MANUFACTURABLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product'),
        ),
    ]
