# Generated by Django 5.2.14 on 2026-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_planned_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
    ]
