# Generated by Django 5.2.10 on 2026-01-10 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_product_mfg_show_contacts_and_more'),
        ('production', '0005_alter_billofmaterials_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterialsline',
            name='unit',
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='inventory.uom', verbose_name='Unidad de Medida'),
        ),
    ]
