# Generated by Django 5.2.9 on 2026-01-11 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_stockmove_uom_alter_stockmove_date_and_more'),
        ('production', '0006_remove_billofmaterialsline_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='current_stage',
            field=models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Materiales'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Es Manual'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto fabricable (para OTs manuales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_work_orders', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='stage_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Bodega de donde se obtendrán los materiales', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='production.workorder')),
            ],
            options={
                'verbose_name': 'Historial de OT',
                'verbose_name_plural': 'Historiales de OT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad Planificada')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad Consumida')),
                ('source', models.CharField(choices=[('BOM', 'Lista de Materiales'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_material_usages', to='inventory.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_materials', to='inventory.uom')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.workorder')),
            ],
            options={
                'verbose_name': 'Material de OT',
                'verbose_name_plural': 'Materiales de OT',
                'unique_together': {('work_order', 'component')},
            },
        ),
    ]
