# Generated by Django 5.2.14 on 2026-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_fts_gin_index'),
        ('inventory', '0007_fts_gin_index'),
        ('production', '0006_task201_workorder_unique_saleline_task207_material_variant'),
        ('purchasing', '0005_fts_gin_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workordermaterial',
            name='unique_workorder_material_variant',
        ),
        migrations.AddConstraint(
            model_name='workordermaterial',
            constraint=models.UniqueConstraint(fields=('work_order', 'component', 'is_outsourced', 'supplier', 'uom'), name='unique_workorder_material_variant', nulls_distinct=False),
        ),
    ]
