# Generated by Django 5.2.10 on 2026-01-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_workorder_current_stage_workorder_is_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
