# Generated by Django 5.2.10 on 2026-01-15 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_default_customer_and_more'),
        ('production', '0008_workorder_start_date'),
        ('purchasing', '0010_purchasereceiptline_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Es Tercerizado'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='purchasing.purchaseline', verbose_name='Línea de Compra'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_materials', to='contacts.contact', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Precio Unitario OC'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='source',
            field=models.CharField(choices=[('BOM', 'Lista de Materiales'), ('MANUAL', 'Manual')], max_length=20, verbose_name='Origen'),
        ),
    ]
