# Generated by Django 5.2.10 on 2026-01-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_workordermaterial_is_outsourced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='document_type',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], default='FACTURA', max_length=20, verbose_name='Tipo de Documento'),
        ),
    ]
