# Generated by Django 5.2.14 on 2026-05-15 21:06

import production.models
from django.db import migrations, models

def set_stage_data_version(apps, schema_editor):
    WorkOrder = apps.get_model('production', 'WorkOrder')
    for order in WorkOrder.objects.all():
        data = order.stage_data or {}
        if '_version' not in data:
            data['_version'] = 1
            order.stage_data = data
            order.save(update_fields=['stage_data'])

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_workordermaterial_unit_cost_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkorder',
            name='stage_data',
            field=models.JSONField(blank=True, default=production.models.default_stage_data, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='stage_data',
            field=models.JSONField(blank=True, default=production.models.default_stage_data, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas'),
        ),
        migrations.RunPython(set_stage_data_version, migrations.RunPython.noop),
    ]
