# Generated by Django 5.2.10 on 2026-01-17 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_workordermaterial_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterialsline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Cantidad necesaria por unidad producida', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productionconsumption',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='quantity_consumed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Consumida'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='quantity_planned',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Planificada'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario OC'),
        ),
    ]
