# Generated by Django 5.2.10 on 2026-01-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_billofmaterialsline_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['-id'], 'verbose_name': 'Lista de Materiales (BOM)', 'verbose_name_plural': 'Listas de Materiales (BOMs)'},
        ),
        migrations.AlterModelOptions(
            name='productionconsumption',
            options={'ordering': ['-id'], 'verbose_name': 'Consumo Material', 'verbose_name_plural': 'Consumos Materiales'},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-id'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Ordenes de Trabajo'},
        ),
    ]
