# Generated by Django 5.2.10 on 2026-01-20 05:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_historicalstockmove'),
        ('production', '0012_alter_billofmaterials_options_and_more'),
        ('sales', '0019_historicalsaledelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Número OT')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Es Manual')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En Proceso'), ('FINISHED', 'Terminada'), ('CANCELLED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('current_stage', models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Materiales'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual')),
                ('stage_data', models.JSONField(blank=True, default=dict, help_text='Datos de diseño, folios, confirmaciones de impresión, etc.', verbose_name='Datos de Etapas')),
                ('specifications', models.TextField(blank=True, help_text='Papel, Tintas, Terminaciones, etc.', verbose_name='Especificaciones Técnicas')),
                ('estimated_completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Finalización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='Producto fabricable (para OTs manuales)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('sale_line', models.ForeignKey(blank=True, db_constraint=False, help_text='Línea de venta asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleline')),
                ('sale_order', models.ForeignKey(blank=True, db_constraint=False, help_text='Nota de Venta asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.saleorder')),
                ('warehouse', models.ForeignKey(blank=True, db_constraint=False, help_text='Bodega de donde se obtendrán los materiales', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'historical Orden de Trabajo',
                'verbose_name_plural': 'historical Ordenes de Trabajo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
