# Generated by Django 5.2.10 on 2026-01-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_historicalworkorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderhistory',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='production.workorder'),
        ),
    ]
