# Generated by Django 6.0.5 on 2026-05-26 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0013_bom_estimated_minutes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalworkorder",
            name="specifications",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="specifications",
        ),
    ]
