# Generated by Django 5.2.10 on 2026-01-20 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_workorderhistory_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermaterial',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario OC'),
        ),
    ]
