# Generated by Django 5.2.10 on 2026-01-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_noteworkflow'),
        ('production', '0014_alter_workorderhistory_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='origin_note',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Nota (Débito) que originó esta producción', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='origin_note',
            field=models.ForeignKey(blank=True, help_text='Nota (Débito) que originó esta producción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_work_orders', to='billing.invoice'),
        ),
    ]
