# Generated by Django 5.2.10 on 2026-01-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_noteworkflow'),
        ('production', '0015_historicalworkorder_origin_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='origin_note',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='origin_note',
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='related_note',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Nota de Débito/Crédito que originó esta OT', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='related_note',
            field=models.ForeignKey(blank=True, help_text='Nota de Débito/Crédito que originó esta OT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='billing.invoice'),
        ),
    ]
