# Generated by Django 5.2.15 on 2026-06-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_alter_workordermaterial_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertemplate',
            name='customer',
        ),
        migrations.DeleteModel(
            name='ScanToken',
        ),
        migrations.DeleteModel(
            name='WorkOrderTemplate',
        ),
    ]
