# Generated by Django 5.2.10 on 2026-01-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_add_related_note_to_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='no_materials_required',
            field=models.BooleanField(default=False, help_text='Si se marca, se omite el paso de aprobación de materiales', verbose_name='Sin materiales de stock'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='no_materials_required',
            field=models.BooleanField(default=False, help_text='Si se marca, se omite el paso de aprobación de materiales', verbose_name='Sin materiales de stock'),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='current_stage',
            field=models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='current_stage',
            field=models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual'),
        ),
    ]
