# Generated by Django 5.2.10 on 2026-01-28 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('production', '0017_historicalworkorder_no_materials_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='related_contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Contacto relacionado con esta OT (ej: cliente del cliente, dato de facturación)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact', verbose_name='Contacto Relacionado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='related_contact',
            field=models.ForeignKey(blank=True, help_text='Contacto relacionado con esta OT (ej: cliente del cliente, dato de facturación)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_work_orders', to='contacts.contact', verbose_name='Contacto Relacionado'),
        ),
    ]
