# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_timestampedmodel_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='billofmaterialsline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billofmaterialsline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='billofmaterialsline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productionconsumption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productionconsumption',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productionconsumption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productionsettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productionsettings',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productionsettings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workorderhistory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workorderhistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workordermaterial',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='workordermaterial',
            name='updated_at',
        ),
    ]
