# Generated by Django 5.2.10 on 2026-01-28 15:31

from django.db import migrations


def populate_related_contact(apps, schema_editor):
    """
    Populate related_contact from stage_data['contact_id'] for existing WorkOrders.
    """
    WorkOrder = apps.get_model('production', 'WorkOrder')
    Contact = apps.get_model('contacts', 'Contact')
    
    work_orders = WorkOrder.objects.all()
    updated_count = 0
    
    for wo in work_orders:
        if wo.stage_data and isinstance(wo.stage_data, dict):
            contact_id = wo.stage_data.get('contact_id')
            if contact_id:
                try:
                    contact = Contact.objects.get(id=contact_id)
                    wo.related_contact = contact
                    wo.save(update_fields=['related_contact'])
                    updated_count += 1
                except Contact.DoesNotExist:
                    # Contact no longer exists, skip
                    pass
    
    if updated_count > 0:
        print(f"Populated related_contact for {updated_count} WorkOrders")


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_add_related_contact_to_workorder'),
    ]

    operations = [
        migrations.RunPython(populate_related_contact, reverse_code=migrations.RunPython.noop),
    ]
