# Generated by Django 5.2.10 on 2026-02-13 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_populate_related_contact_from_stage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionconsumption',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
