# Generated by Django 5.2.10 on 2026-02-13 00:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_alter_productionconsumption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionconsumption',
            name='date',
            field=models.DateField(default=core.utils.get_current_date, verbose_name='Fecha'),
        ),
    ]
