# Generated by Django 5.2.12 on 2026-03-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_alter_productionconsumption_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='actual_quantity_produced',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad real fabricada declarada en la rectificación (OTs manuales)', max_digits=12, null=True, verbose_name='Cantidad Real Producida'),
        ),
        migrations.AddField(
            model_name='historicalworkorder',
            name='is_rectified',
            field=models.BooleanField(default=False, help_text='Indica si la OT pasó por el paso de rectificación antes de finalizar', verbose_name='Rectificada'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_quantity_produced',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cantidad real fabricada declarada en la rectificación (OTs manuales)', max_digits=12, null=True, verbose_name='Cantidad Real Producida'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_rectified',
            field=models.BooleanField(default=False, help_text='Indica si la OT pasó por el paso de rectificación antes de finalizar', verbose_name='Rectificada'),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='current_stage',
            field=models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('RECTIFICATION', 'Rectificación'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='current_stage',
            field=models.CharField(choices=[('MATERIAL_ASSIGNMENT', 'Asignación de Materiales'), ('MATERIAL_APPROVAL', 'Aprobación de Stock'), ('OUTSOURCING_ASSIGNMENT', 'Asignación de Tercerizados'), ('PREPRESS', 'Pre-Impresión'), ('PRESS', 'Impresión'), ('POSTPRESS', 'Post-Impresión'), ('OUTSOURCING_VERIFICATION', 'Verificación de Tercerizados'), ('RECTIFICATION', 'Rectificación'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='MATERIAL_ASSIGNMENT', max_length=30, verbose_name='Etapa Actual'),
        ),
    ]
