# Generated by Django 5.2.12 on 2026-03-09 04:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_add_unit_cost_to_stockmove'),
        ('production', '0022_add_rectification_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='yield_quantity',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Cantidad producida por esta receta', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Rendimiento'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='yield_uom',
            field=models.ForeignKey(blank=True, help_text='Unidad en la que se expresa el rendimiento (se usa la unidad base del producto si se omite)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_yields', to='inventory.uom', verbose_name='Unidad de Rendimiento'),
        ),
    ]
