# Generated by Django 5.2.12 on 2026-03-27 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contact_credit_auto_blocked_and_more'),
        ('production', '0023_billofmaterials_yield_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterialsline',
            name='document_type',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], default='FACTURA', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='is_outsourced',
            field=models.BooleanField(default=False, verbose_name='Es Tercerizado'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_lines', to='contacts.contact', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='billofmaterialsline',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Precio neto por unidad (sin IVA)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario Neto'),
        ),
    ]
