# Generated by Django 5.2.12 on 2026-03-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_add_outsourcing_to_bomline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='billofmaterialsline',
            name='notes',
        ),
    ]
