# Generated by Django 5.2.10 on 2026-01-29 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignmentrule',
            name='assigned_group',
            field=models.ForeignKey(blank=True, help_text='Si no hay un usuario específico, la tarea se ofrecerá a este grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to='auth.group', verbose_name='Grupo Asignado por Defecto'),
        ),
    ]
