# Generated by Django 5.2.10 on 2026-01-29 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('APPROVAL', 'Aprobación de Flujo'), ('TASK', 'Tarea Operativa')], db_index=True, default='APPROVAL', help_text='APPROVAL: Aprobación de flujo | TASK: Tarea operativa', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que completó/aprobó esta tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Completada por'),
        ),
    ]
