# Generated by Django 5.2.10 on 2026-01-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0002_task_category_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='auth.group', verbose_name='Grupo Asignado'),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
