# Generated by Django 5.2.12 on 2026-03-09 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_task_assigned_group_task_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f29_creation_day', models.PositiveIntegerField(default=12, help_text='Día del mes para generar la tarea de creación del F29', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día Creación F29')),
                ('f29_payment_day', models.PositiveIntegerField(default=20, help_text='Día del mes para generar la tarea de pago del F29', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día Pago F29')),
                ('period_close_day', models.PositiveIntegerField(default=5, help_text='Día del mes para generar la tarea de cierre de periodo contable', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Día Cierre Periodo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Flujo',
                'verbose_name_plural': 'Configuración de Flujos',
            },
        ),
    ]
