# Generated by Django 5.2.14 on 2026-05-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_comment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='workflow_co_content_c512dc_idx',
            old_name='workflow_co_content_idx',
        ),
    ]
