# Generated by Django 5.2.12 on 2026-03-10 22:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0004_workflowsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsettings',
            name='low_margin_threshold_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Si el margen de un producto baja de este porcentaje, se envía una notificación (0 para desactivar).', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Umbral de Margen Bajo (%)'),
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='Identificador único (ej: POS_CREDIT_APPROVAL, SUBSCRIPTION_OC_CREATED)', max_length=100, unique=True, verbose_name='Tipo de Notificación')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('notify_creator', models.BooleanField(default=True, help_text='Si está marcado, se notificará al usuario que inició la acción (ej: quien pidió el crédito).', verbose_name='Notificar al Creador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to='auth.group', verbose_name='Grupo Extra a Notificar')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Extra a Notificar')),
            ],
            options={
                'verbose_name': 'Regla de Notificación',
                'verbose_name_plural': 'Reglas de Notificación',
            },
        ),
    ]
