# Generated by Django 6.0.5 on 2026-06-11 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_rename_workflow_co_content_idx_workflow_co_content_c512dc_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=100, verbose_name='Entidad')),
                ('entity_id', models.PositiveIntegerField(db_index=True, verbose_name='ID')),
                ('transition', models.CharField(choices=[('cancel', 'Cancelación'), ('annul', 'Anulación'), ('purge', 'Purga')], db_index=True, max_length=20, verbose_name='Transición')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transición de Documento',
                'verbose_name_plural': 'Transiciones de Documento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='workflow_tr_entity__38af50_idx')],
            },
        ),
    ]
