# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_timestampedmodel_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taskassignmentrule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workflowsettings',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='workflowsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='workflowsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
