# Generated by Django 5.2.12 on 2026-04-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='historicalcompanysettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='historicalcompanysettings',
            name='secondary_color',
        ),
    ]
