# Generated by Django 5.2.14 on 2026-05-10 22:37

import django.db.models.deletion
from django.db import migrations, models

import core.db_compat


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_fts_gin_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.CharField(db_index=True, max_length=50)),
                ("search_vector", core.db_compat.SearchVectorField(null=True)),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=255, verbose_name="Subtítulo"),
                ),
                (
                    "extra_info",
                    models.CharField(blank=True, max_length=255, verbose_name="Información Extra"),
                ),
                ("icon", models.CharField(blank=True, max_length=50, verbose_name="Icono")),
                ("entity_label", models.CharField(db_index=True, max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Índice de Búsqueda Global",
                "verbose_name_plural": "Índices de Búsqueda Global",
                "indexes": [
                    core.db_compat.GinIndex(
                        fields=["search_vector"], name="idx_global_search_vector"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"], name="core_global_content_9baf63_idx"
                    ),
                    models.Index(fields=["entity_label"], name="core_global_entity__99083a_idx"),
                ],
            },
        ),
    ]
