# Generated by Django 5.2.10 on 2026-01-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_migrate_roles_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
