# Generated by Django 5.2.10 on 2026-01-28 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_options_historicalcontact'),
        ('core', '0006_remove_legacy_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vínculo con la entidad física de Contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(blank=True, help_text='Vínculo con la entidad física de Contacto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_user', to='contacts.contact'),
        ),
    ]
