# Generated by Django 5.2.12 on 2026-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicaluser_contact_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pos_default_credit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de la venta que se puede asignar como crédito por defecto si el cliente no tiene línea de crédito.', max_digits=5, verbose_name='Porcentaje de Crédito Fallback POS'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='pos_default_credit_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de la venta que se puede asignar como crédito por defecto si el cliente no tiene línea de crédito.', max_digits=5, verbose_name='Porcentaje de Crédito Fallback POS'),
        ),
    ]
