# Generated by Django 5.2.15 on 2026-06-18 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_idempotencyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="Clave")),
                ("value", models.JSONField(blank=True, default=dict, verbose_name="Valor")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado en")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Usuario",
                "verbose_name_plural": "Preferencias de Usuario",
                "unique_together": {("user", "key")},
            },
        ),
    ]
