# Generated by Django 6.0.5 on 2026-06-25 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('job_type', models.CharField(choices=[('IMPORT', 'Importación'), ('EXPORT', 'Exportación'), ('REPORT', 'Reporte Pesado')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('title', models.CharField(help_text='Ej: Exportación de Productos', max_length=255, verbose_name='Título')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='Progreso %')),
                ('result_file_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL de Resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trabajo en Segundo Plano',
                'verbose_name_plural': 'Trabajos en Segundo Plano',
                'ordering': ['-created_at'],
            },
        ),
    ]
