# Generated by Django 5.2.12 on 2026-03-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings_pos_default_credit_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='pos_default_credit_percentage',
        ),
        migrations.RemoveField(
            model_name='historicalcompanysettings',
            name='pos_default_credit_percentage',
        ),
    ]
