# Generated by Django 6.0.6 on 2026-07-01 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_backgroundjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodReopenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('ACCOUNTING', 'Periodo Contable'), ('TAX', 'Periodo Tributario (F29)')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('period_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status_before', models.CharField(max_length=30)),
                ('status_after', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_reopen_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Reapertura',
                'verbose_name_plural': 'Registros de Reapertura',
                'ordering': ['-created_at'],
            },
        ),
    ]
