# Generated by Django 5.2.12 on 2026-03-08 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_credit_blocked_and_more'),
        ('core', '0009_remove_companysettings_pos_default_credit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='business_activity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Giro / Actividad Económica'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Vínculo con el contacto que representa a esta empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='business_activity',
            field=models.CharField(blank=True, max_length=255, verbose_name='Giro / Actividad Económica'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Vínculo con el contacto que representa a esta empresa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='primary_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Color Primario'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='secondary_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, verbose_name='Color Secundario'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='trade_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='historicalcompanysettings',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Razón Social'),
        ),
    ]
