# Generated by Django 5.2.12 on 2026-03-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companysettings_business_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='pos_pin',
            field=models.CharField(blank=True, help_text='PIN para Punto de Venta (hasheado)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pos_pin',
            field=models.CharField(blank=True, help_text='PIN para Punto de Venta (hasheado)', max_length=128, null=True),
        ),
    ]
