# Generated by Django 5.2.15 on 2026-07-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_backgroundjob_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundjob',
            name='deleted_at',
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
    ]
